= ["For Business Users"]
:last_updated: 11/05/2021
:linkattrs:
:experimental:
:page-aliases: /admin/ts-cloud/business-user.adocc
:description: Business users view data insights to inform and support critical business decisions.

{% include content/liveboards-announcement.md %}

Business users view data insights to inform and support critical business decisions.

Your job is vital to your organization, and using ThoughtSpot makes it easier.

* link:business-user-onboarding.html[Onboarding for Business users] + Get a quick overview of how ThoughtSpot can support you.
* <a href="{{ "/end-user/thoughtspot-one/thoughtspot-one-homepage.html "| prepend: site.baseurl }}">Home page [.badge.badge-update]#New#</a> + This is where you get direct access to exisiting Answers, Liveboards, and visualizations.
* link:pinboards.html[More about Liveboards and Answers] + Quick tips on how you can use and customize Liveboards and Charts.
* <a href="{{ "/end-user/search/search-overview.html "| prepend: site.baseurl }}">ThoughtSpot Search</a> + We expanded our flagship Search functionality.
In addition to the traditional <a href="{{ "/end-user/search/search-data.html "| prepend: site.baseurl }}">Search over Data</a>, ThoughtSpot now supports a powerful set of features that helps users get their information from existing content through <a href="{{ "/end-user/search/search-answers.html "| prepend: site.baseurl }}">Search over Answers [.badge.badge-update]#New#.</a>
* link:search-assist.html[Search Assist] + See how ThoughtSpot Search Assist gives you insights into your own data.
* <a href="{{ "/admin/mobile/use-mobile.html "| prepend: site.baseurl }}">Mobile App</a> + Access your ThoughtSpot cluster to search Answers and Liveboards, and create Liveboards.
