= Finding your way around
:last_updated: 11/15/2019


ThoughtSpot is organized into several sections to make navigation easy. You can reach them by using the menu bar.
:toc: true

These are the different sections in ThoughtSpot:

== Home

Click the ThoughtSpot logo to go to the application home page.
At the top of the home page you can see a search bar, and several areas that show activity in ThoughtSpot.
+++<dlentry>+++Favorites::::  Answers and Pinboards that you mark as favorite appear here.+++</dlentry>++++++<dlentry>+++Following::::  When you follow a metric on a Pinboard, we track it for you, and post daily updates here.+++</dlentry>++++++<dlentry>+++Recently viewed::::  For quick access, jump to the Answers and Pinboards you saw most recently.+++</dlentry>++++++<dlentry>+++Recently trending::::  [default] + These are the Pinboards that other people in your organization accessed the most, recently.+++</dlentry>++++++<dlentry>+++All-time popular::::  [select option] + Check out all-time popular Answers and Pinboards.+++</dlentry>+++

The items on this page are limited to Answers, Pinboards, Worksheets, and other objects that you have permission to access.

[#search]
== Search

*Search* is where you will spend most of your time.
It allows you to search and explore your data.
Choose your data sources and type in the search bar at the top.
As you type your search, results will appear in the main part of the screen as either a table or a chart.

If SearchIQ [.label.label-beta]#Beta# is enabled by your administrator, this label is *Search+*, to differentiate it from SearchIQ.
Use the search bar on the homepage to use SearchIQ.

To learn more about this section, visit link:{{ site.baseurl }}/end-user/search/about-starting-a-new-search.html#[About search].

To learn more about SearchIQ, visit link:{{ site.baseurl }}/end-user/search/about-searchiq.html#[About SearchIQ].

[#answers]
== Answers

Answers are the result of a single search.
You can save an answer you want to work more on later, or just keep it for your personal use.
Answers are for you alone, until you share them with others.

[#pinboards]
== Pinboards

Pinboards are collections of related search results.
You can create your own pinboard or add to an existing one.
After saving a pinboard, it can be shared with others or viewed as a slideshow.
The *Pinboards* page shows a list of saved pinboards.
Click one to view, edit, or share it.

To learn more about pinboards, visit link:{{ site.baseurl }}/end-user/pinboards/about-pinboards.html[About pinboards].

== SpotIQ

If SpotIQ is enabled by your administrator, you can go here to view the status of your analysis requests to see the results.

To learn more about this section, visit link:{{ site.baseurl }}/spotiq/whatisspotiq.html#[About SpotIQ].

[#data]
== Data

*Data* contains a list of data sources (tables and worksheets).
These are usually loaded and managed by your administrator.
However, you may be able to import a spreadsheet (Excel or CSV) here, if you have the correct privileges.

To learn more about this section, visit link:{{ site.baseurl }}/end-user/data-view/data-intro-end-user.html#[Working with data].

[#admin]
== Admin

*Admin* only appears if you have administrator privileges.

This section is covered in the link:{{ site.baseurl }}/admin/intro.html#[ThoughtSpot Administrator Guide].

[#help-icon]
== Help Icon

You can find information and support resources for ThoughtSpot here.
There are short videos, a keyword reference, links to documentation, and other useful materials.
You can also find the support contact information and software version number here.

To learn more about this section, visit link:{{ site.baseurl }}/end-user/help-center/what-you-can-find-in-the-help-center.html#[More help and support].

[#user-icon]
== User Icon

The *user icon* allows you to either view your preferences or log out.
You can also change your icon here.

To learn more about this section, visit link:{{ site.baseurl }}/end-user/introduction/about-user.html[About the user profile].

[#related-information]
== Related information

link:{{ site.baseurl }}/end-user/locale.html[Set your ThoughtSpot locale]
