= Amazon Linux 2 installation prerequisites
:last_updated: 10/19/2020


Prepare the system and ThoughtSpot clusters for installation.

[cols=2*]
|===
| &#10063;
| <<set-up-hosts,1.
Set up hosts for the ThoughtSpot cluster>>

| &#10063;
| <<aws-ssm,2.
[Optional] Set up AWS Systems Manager Agent>>

| &#10063;
| <<partition-hosts,3.
Partition the hosts>>

| &#10063;
| <<enable-hosts,4.
Enable the hosts to download Amazon Linux 2 packages>>

| &#10063;
| <<enable-ansible,5.
Enable an Ansible Control Server>>

| &#10063;
| <<disable-selinux,6.
Disable SELinux or run it in permissive mode>>
|===

[#set-up-hosts]
== Set up hosts for the ThoughtSpot cluster

Set up hosts for the ThoughtSpot cluster on Amazon Web Services.

. Refer to link:{{ site.baseurl }}/appliance/aws/configuration-options.html[AWS configuration options] for the exact specification for the hosts:
 ** CPU
 ** memory
 ** disks
. Refer to link:{{ site.baseurl }}/appliance/aws/launch-an-instance.html[Set up AWS resources for ThoughtSpot] to create and launch your AWS virtual machines.
 ** Ensure that your link:{{ site.baseurl }}/appliance/aws/launch-an-instance.html#al2-ami[AMI] is an Amazon Linux 2 image.

[#aws-ssm]
== [Optional] Set up AWS Systems Manager Agent

If you plan to use the https://docs.aws.amazon.com/systems-manager/latest/userguide/ssm-agent.html[AWS SSM agent] as an alternative to SSH, create a new IAM role while creating VMs.
This IAM role must have an SSM policy to grant AWS SSM permission to perform actions on your instances.
Refer to https://docs.aws.amazon.com/systems-manager/latest/userguide/setup-instance-profile.html[Create an IAM instance profile for Systems Manager].

You must install the SSM agent on each node.
Refer to https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-manual-agent-install.html[Manually install SSM Agent on EC2 instances for Linux], if the SSM agent is not already on each node.

[#partition-hosts]
== Partition the hosts

Ensure that all ThoughtSpot hosts meet the following partition and sizing requirements.
All drives must be SSDs.

. At least 20 GB available on the root drive, for yum packages and system logs.
. At least 200 GB for ThoughtSpot installation, either on a secondary drive or as a separate partition on the root drive.
+
{% include note.html content="This drive must be separate from the data drive(s)." %}

[#enable-hosts]
== Enable the hosts to download Amazon Linux 2 packages

*Repositories*

* *Yum repositories*: you must enable the following Yum repositories in your cluster: `epel`, `nux-desktop`, `google-cloud-sdk`, and `azure-cli`.

* *Python repository*: for Python, ensure the machine is able to reach the `PyPI` repository located at https://pypi.python.org/.

* *R repository*: for R, ensure the machine is able to reach the `CRAN` repository located at https://cran.rstudio.com/.

Make sure that you can download Amazon Linux 2 packages to all hosts, either from the <<official-repositories,official package repositories>>, or from a <<mirror-repositories,mirror repository>> owned and managed by your organization.

If you cannot access the Amazon Linux 2 repositories, there is no mirror repository in your organization, or you are unable to access Yum, Python, or R repositories, please link:{{ site.baseurl }}/appliance/contact.html[contact ThoughtSpot Support].

*Official package repositories*

If the hosts of your ThoughtSpot cluster can access external repositories, either directly or through a proxy, your cluster is online.
You can then proceed to download <<yum-repositories,Yum>>, <<python-repositories,Python>>, and <<r-repositories,R>> package repositories.

*Internal mirror repository*

If the hosts of your ThoughtSpot cluster have access to an internal repository that mirrors the public repositories, copy the <<yum-repositories,Yum>>, <<python-repositories,Python>>, and <<r-repositories,R>> package repositories to your hosts.

[#enable-ansible]
== Enable an Ansible Control Server

Configure an Ansible Control Server, on a separate host, to run the Ansible playbook that ThoughtSpot supplies.
You must install both `rsync` and Ansible on the Ansible Control Server host.

[#disable-selinux]
== Disable SELinux or run it in permissive mode

ThoughtSpot does not support policies that enforce SELinux.
We recommend that you disable SELinux, or run it in permissive mode.

== Next steps

Next, link:{{ site.baseurl }}/appliance/amazon-linux-2/al2-ts-artifacts.html[get ThoughtSpot artifacts].
