= Configure SAML
:last_updated: 8/16/2021
:linkattrs:
:page_aliases: /app-integrate/SAML/configure-SAML-with-tscli.adoc, /admin/ts-cloud/authentication-integration.adoc, /admin/setup/configure-SAML-with-tscli.adoc

You can configure Security Assertion Markup Language (SAML) using ThoughtSpot's command line interface, tscli.

ThoughtSpot enables you to use the Security Assertion Markup Language (SAML) to authenticate users.
You can set up SAML through the shell on ThoughtSpot <<saml-configure-tscli,using a `tscli`-based configurator>>, or <<admin-portal,through the Admin Console>>. It is configured to work using service provided by an Identity Provider (IDP).

Popular Identity Providers that ThoughtSpot supports include https://developer.okta.com/docs/guides/build-sso-integration/saml2/overview/[Okta], https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/configure-saml2-settings-azure-ad[Azure Active Directory], https://docs.pingidentity.com/bundle/solution-guides/page/ozz1597769517562.html[PingFederate], https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/configure-saml2-settings[Microsoft AD FS], and https://developers.onelogin.com/quickstart/saml[Onelogin]. This is not an exhaustive list. To determine if ThoughtSpot supports your preferred IdP, talk to your ThoughtSpot contact.

After you complete the SAML configuration in ThoughtSpot that this article describes, refer to your Identity Provider’s SAML documentation for specific information on setting up SAML with that IdP.

[#prerequisites]
== Configuration prerequisites

Before configuring SAML, collect the following information:

[cols=2*]
|===
|&#10063;
|<<ts-service-address,ThoughtSpot service address>>

|&#10063;
|<<ts-service-address,Service port>>

|&#10063;
|<<ts-service-name,Unique service name>>

|&#10063;
|<<skew-time,Skew time in seconds>>

|&#10063;
|<<metadata-xml-file,IDP Metadata XML file>>

|&#10063;
|<<auto-add,Automatically add SAML users to ThoughtSpot>>

|&#10063;
|<<ts-auth,Also use ThoughtSpot internal authentication>>
|===

[#ts-service-address]
=== ThoughtSpot service address
DNS name of the load balancer _front-end_ for multi-node ThoughtSpot clusters, or of the ThoughtSpot _server_ for a single-node ThoughtSpot cluster. If you do not have the DNS name, you can use the front-end IP address. Using the DNS name instead of the IP address is a best practice.

[#ts-service-port]
=== Service port
Service port for ThoughtSpot instance, typically TCP/443.

[#ts-service-name]
=== Unique service name
The unique key ThoughtSpot uses to identify IDP service. Set by the ThoughtSpot Support Team.

The key has the following format:
`urn:thoughtspot:callosum:saml`.

[#skew-time]
=== Skew time in seconds
Allowed skew time for authentication, or the duration after authentication response is rejected and sent back from the IDP.

Usually set to `3600` seconds.

[#metadata-xml-file]
=== IDP Metadata XML File
This file is provided by the IDP. The absolute path to the `idp-meta.xml` file is needed for one-time configuration.

NOTE: If your IdP does not allow you to import the IdP metadata XML file, you must map values manually. For the ThoughtSpot system to pick up certain attributes, you must map them to specific fields. Map the username you would like to use to `NameId`, and map the email id of the user to `mail`.

[#auto-add]
=== Automatically add SAML users to ThoughtSpot: (yes/no)
If you choose 'yes', then new users will be automatically created in ThoughtSpot upon first successful SSO login.

If you choose 'no', then SAML users will not be added in ThoughtSpot upon first successful SSO login. Instead, you must xref:add-user.adoc[add users manually] or through xref:LDAP-config-AD.adoc[Active Directory].

[#ts-auth]
=== Also use ThoughtSpot internal authentication: (y/n)
If 'y', then ThoughtSpot local/internal users (including local administrative users) will still be authenticated outside the scope of SSO.

[#saml-configure-tscli]
== Configure SAML using tscli

NOTE: This configuration persists across software updates, so you do not have to reapply it if you update to a newer release of ThoughtSpot.

To set up SAML for user authentication, follow these steps:

. Log in to the Linux shell using SSH.
. Execute the `saml configure` command to launch the interactive SAML configuration:
+
----
 tscli saml configure
----

. Complete the configurator prompts with the information you gathered in xref:prerequisites[Configuration prerequisites].
. When the configuration is complete, download ThoughtSpot's metadata file, `spring_saml_metadata.xml`. This file contains the public key you need if you want to encrypt your SAML assertions. To download this file, navigate to `https://<hostname-or-IP>/callosum/v1/saml/metadata/`. The file automatically downloads.

=== Configure the IdP
To enable the IdP to recognize your host application and ThoughtSpot as a valid service provider, you must configure the IdP with required attributes and metadata. This includes the spring_saml_metadata.xml file that you downloaded in step 4 of <<saml-configure-tscli,Configure SAML using tscli>>.

ThoughtSpot supports SAML authentication with several identity and access management providers, such as https://developer.okta.com/docs/guides/build-sso-integration/saml2/before-you-begin/[Okta^], https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/configure-saml2-settings-azure-ad[Azure Active Directory^], https://docs.pingidentity.com/bundle/solution-guides/page/ozz1597769517562.html[PingFederate^], https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/configure-saml2-settings[Microsoft AD FS^], https://developers.onelogin.com/saml[Onelogin^], and so on. If you want to use one of these providers as your IdP, make sure you read the SAML configuration steps described in the Identity provider’s documentation site.

To determine if ThoughtSpot supports your preferred IdP, xref:contact.adoc[contact ThoughtSpot Support].

Complete your configuration of the IdP using the IdP’s SAML documentation. Upload or copy the contents of the `spring_saml_metadata.xml` to your IdP server. This file contains the public key you need if you want to encrypt your SAML assertions. If you did not download the `spring_saml_metadata.xml` file, navigate to `https://<your_ThoughtSpot_hostname-or-IP>/callosum/v1/saml/metadata/`. The file automatically downloads.

NOTE: When configuring SAML 2.0, make sure you map the SAML user attributes to appropriate fields. For example, you must map SAML user’s username to the NameId attribute in OneLogin. Similarly, in Okta, you must map the username to userPrincipalName. You must also ensure that the email address of the user is mapped to the mail attribute. If your IdP does not allow you to import the IdP metadata XML file, you must map these values manually.

After you configure the IdP, open a Web browser and go to the ThoughtSpot login page. It should now show the Single Sign On option.

=== Additional resources

As you develop your expertise in authentication and security, we recommend the following ThoughtSpot U course:
- https://training.thoughtspot.com/authentication-security/621450[Single Sign On (SSO)]

See other training resources at https://training.thoughtspot.com[ThoughtSpot U].
