= Glossary
:last_updated: 11/19/2019

ThoughtSpot has its own company-specific terminology, which is useful to know.

++++
<div class="glossary">
<br>
<p><strong>Answer</strong> : An Answer is the result of search that the user saves in the form of a visualization, such as a table or a chart. </p>
<br>
<p><strong>authentication</strong> : The process of verifying user credentials, and letting them long into ThoughtSpot. </p>
<br>
<p><strong>data set, dataset</strong> : A collection of related sets of information that is composed of separate elements, but can be manipulated as a unit by a computer. In the case of tabular data, a data set is comprised of one or more database tables, where every column of a table represents a specific variable, and each row corresponds to a record of the data set. </p>
<br>
<p><strong>filter</strong> : This is a column value that a user can add to search. </p>
<br>
<p><strong>formula</strong> : This is an expression that applies a calculation, usually a mathematical calculation, to data. </p>
<br>
<p><strong>group aggregation</strong> : This enables you to aggregate a value by a specific attribute. Also known as *pinned aggregation* or a *level-based measure*. </p>
<br>
<p><strong>impression</strong> : An impression registers when a user enters text into a search bar, or loads a *pinboard*. </p>
<br>
<p><strong>Pinboard</strong> : This is a collection of related *Answers*, or search results, that appear as tables or visualizations. </p>
<br>
<p><strong>pinned measure</strong> : This enables you to aggregate a value by a specific attribute. Also known as *group aggregation*, or a *level-based measure*. </p>
<br>
<p><strong>reportbook</strong> : This is an internal name for a *visualization*. </p>
<br>
<p><strong>search</strong> : This is a query in ThoughtSpot. We call this search because ThoughtSpot queries enable the user to find business information as efficiently as using an Internet search engine. </p>
<br>
<p><strong>token</strong> : The text that users enter in the search bar. This includes keywords, column names, and formula names. </p>
<br>
<p><strong>user</strong> : Individuals that can log in to ThoughtSpot. See *authentication*. </p>
<br>
<p><strong>visualization</strong> : This is a visual representation of data. In ThoughtSpot, it is the representation of an *answer*. In some cases, we use the terms *visualization* and *answer* interchangeably. </p>
<br>
<p><strong>viz</strong> : This is a common abbreviation for *visualization*. </p>
</div>
++++
