= About installation and upgrades
:last_updated: 3/4/2020


As administrator, you are responsible for setting up and configuring ThoughtSpot. This guide explains how. It will also assist you in troubleshooting some common problems, finding additional resources, and contacting ThoughtSpot.

In ThoughtSpot, both physical appliances and virtual machines ship with a base OS image.
ThoughtSpot Support then helps you to install, and subsequently update the software.
Note the exception of RHEL installations, where the customer provides the OS image themselves, and uses a slightly different installation protocol.

The ThoughtSpot Support team contacts all clients to schedule updates as we release new versions of ThoughtSpot.
To schedule upgrades to patch releases that support your use cases, work with our Customer Success team.

As administrator, you are responsible for setting up and configuring ThoughtSpot.
This guide helps you with these tasks, and also assists in troubleshooting some common problems and finding additional resources.

[#display-current-config]
== Display your current configuration

To perform the setup and configuration, you must first learn how to link:{{ site.baseurl }}/admin/setup/logins.html[gain administrative access].

. Log in to the ThoughtSpot cluster as the `admin` user.
. Use the `tscli feature` subcommand to display your current configuration.
+
----
 $ tscli feature get-all-config
 +---------------------------------+----------+---------------+
 |              NAME               |  STATUS  | CONFIGURATION |
 +---------------------------------+----------+---------------+
 | Firewall                        | Disabled |               |
 | Saml                            | Disabled |               |
 | Ldap                            | Disabled |               |
 | CustomBranding                  | Disabled |               |
 | CustomBrandingFontCustomization | Disabled |               |
 | DataConnect                     | Disabled |               |
 | RLS                             | Enabled  |               |
 | Callhome                        | Enabled  |               |
 | SSHTunnel                       | Enabled  |               |
 | Fileserver                      | Disabled |               |
 +---------------------------------+----------+---------------+
----

[#related]
== Related information

The following tasks are also available:

* link:{{ site.baseurl }}/admin/setup/set-your-thoughtspot-locale.html[Set your locale]
* link:{{ site.baseurl }}/admin/setup/test-network.html[Test connectivity between nodes]
* link:{{ site.baseurl }}/admin/setup/set-custom-calendar.html[Set up a fiscal calendar year]
* link:{{ site.baseurl }}/admin/setup/about-LDAP.html[Integrate LDAP]
* link:{{ site.baseurl }}/admin/setup/set-up-monitoring.html[Set up monitoring]
* link:{{ site.baseurl }}/admin/setup/work-with-ts-support.html[Configure support services]
* link:{{ site.baseurl }}/appliance/ports.html[Network ports]
* link:{{ site.baseurl }}/admin/setup/about-load-balancer-configuration.html[Configure load balancing and proxies]
* link:{{ site.baseurl }}/admin/setup/customize-style.html[Customize look and feel]
