= Introduction to monitoring
:last_updated: 10/22/2020


Learn how to monitor your system.

System monitoring tools in ThoughtSpot include several Pinboards in the *Admin Console* and system logs.
Additionally, ThoughtSpot provides several worksheets and out-of-the-box system monitoring pinboards.
From these worksheets, you can create your own custom visualizations and pinboards.
This page introduces these features and directs you towards more detailed information.

== Admin Console

The ThoughtSpot application includes an *Admin Console* center, where you can easily monitor usage, alerts, events and general cluster health.
Navigate to the Admin Console by selecting *Admin* from the top navigation bar.

Only users with administrative privileges can view the *Admin Console*.
However, administrative users can present the information in the *Admin Console* to others

Administrators can also create their own, custom boards that reflect system data in ways that are meaningful to specific departments or groups.
For more information, see the following documentation:

* link:{{ site.baseurl }}/admin/system-monitor/overview.html[Health Overview board]
* link:{{ site.baseurl }}/admin/system-monitor/data.html[Data board]
* link:{{ site.baseurl }}/admin/system-monitor/cluster-manager.html[Cluster Manager board]
* link:{{ site.baseurl }}/admin/system-monitor/cluster-manager.html[Alerts and Events board]
* link:{{ site.baseurl }}/admin/system-monitor/worksheets.html[System worksheets]
* link:{{ site.baseurl }}/admin/system-monitor/monitor-pinboards.html[System pinboards]
* link:{{ site.baseurl }}/admin/system-monitor/falcon-monitor.html[Falcon monitoring Pinboards]
* link:{{ site.baseurl }}/admin/system-monitor/performance-tracking.html[Performance Tracking Pinboard]

Much of the data presented by these boards is also available through link:{{ site.baseurl }}/reference/tscli-command-ref.html[`tscli` commands].

== Log files

Many of the administration commands output logging information to log files.
The logs get written into the fixed directory `/export/logs`, with a sub-directory for each subsystem.
The individual log directories are the following:

* `/export/logs/orion`
* `/export/logs/oreo`
* `/export/logs/hadoop`
* `/export/logs/zookeeper`

You can also view [additional topics that also touch on link:{{site.baseurl}}/tags/tag_logs.html[log files] throughout the documentation.

== System monitoring notifications

You can configure ThoughtSpot to send emails to addresses you specify with monitoring reports and a cluster heartbeat.
Follow these steps to link:{{ site.baseurl }}/admin/setup/set-up-monitoring.html#[Set up monitoring].
