= 6.2 Release Notes
:last_updated: 09/28/2020

ThoughtSpot version 6.2.1 is now available.
These release notes include information about new and enhanced features.

For a complete list of issues that we fixed in this release, see link:{{ site.baseurl }}/release/fixed.adoc[Fixed issues].

* <<6-2-1-new,6.2.1 New Features>>
* <<6-2-new,6.2 New Features>>
* <<beta-program,Beta Programs>>
* <<upgrade-paths,Supported Upgrade Paths>>

[#6-2-1-new]
== 6.2.1 New Features and Functionality

For a complete list of issues that we fixed in this release, see link:{{ site.baseurl }}/release/fixed.adoc#6-2-1[6.2.1 Fixed issues].

=== For the IT Ops Engineer
+++<dlentry id="granular-pinboard-access">+++Granular access to Pinboards::::
Starting with this release, you can control user's permissions to create or update Pinboards, essentially limiting them to 'read only' access.
These users can view and explore Pinboards.
However, they cannot edit, copy, download, or share Pinboards and Answers.
+ This must be enabled on the cluster.
+ See xref:pinboard-granular-permission.adoc[Granular access to Pinboards], and link:{{ site.baseurl }}/end-user/introduction/about-privileges-end-user.adoc#read-only[Cannot create or update Pinboards] privilege.+++</dlentry>++++++<dlentry id="style-customization">+++Style customization::::
You can now customize the ThoughtSpot application from the Admin Console.
With style customization, you can change the fonts, chart color palettes, footer text, application logo, and background colors in your embedded ThoughtSpot instance.
+  + Refer to xref:style-customization.adoc[Style customization].+++</dlentry>+++

[#6-2-new]
== 6.2 New Features and Functionality

For a complete list of issues that we fixed in this release, see xref:fixed.adoc#6-2[6.2 Fixed issues].

=== For the Analyst
+++<dlentry id="geomaps">+++Geomaps::::  ThoughtSpot now supports xref:geomap-reference.adoc[GeoMap] visualizations for these new locales:

* *India*: State, District, Postcode
* *Portugal*: District, Municipality, Postcode
* *Italy*: Improved regional name support *Geomaps overview* ++++<script src="https://fast.wistia.com/embed/medias/u7prltvp9w.jsonp" async="">++++++</script>++++++<script src="https://fast.wistia.com/assets/external/E-v1.js" async="">++++++</script>+++

[.wistia_embed.wistia_async_u7prltvp9w.popover=true.popoverAnimateThumbnail=true.popoverBorderColor=4E55FD.popoverBorderWidth=2]#&nbsp;#+++</dlentry>++++++<dlentry id="table-config">+++Table configuration::::  This release introduces a more intuitive way to configure your tables, including these new features:

* *xref:about-tables.adoc#rearrange-column-order[Drag and drop chips]* allow you to easily rearrange the order of the columns in your table
* *xref:about-tables.adoc#clip-wrap-text[Clip or wrap text]* for the entire table from the *Edit table: Settings* menu, or by column from the column's *more options menu*
* *xref:about-tables.adoc#number-formatting[Number formatting]* for any table column based on a measure, allowing you to change the category (number, percentage, or currency), units (auto, none, thousand, million, billion, or trillion), or method of writing negative values (-1234, 1234-, or (1234))
* *xref:about-tables.adoc#table-footer[Enable or disable the table footer]* from the *Edit table: Settings* menu
* *xref:about-tables.adoc#column-summaries[Enable or disable column summaries]* from the *Edit table: Settings* menu *Table configuration overview* ++++<script src="https://fast.wistia.com/embed/medias/9ggsx9glpz.jsonp" async="">++++++</script>++++++<script src="https://fast.wistia.com/assets/external/E-v1.js" async="">++++++</script>+++

[.wistia_embed.wistia_async_9ggsx9glpz.popover=true.popoverAnimateThumbnail=true.popoverBorderColor=4E55FD.popoverBorderWidth=2]#&nbsp;#

For more information, see xref:about-tables.adoc[Results that are tables].+++</dlentry>++++++<dlentry id="high-cardinality">+++High cardinality::::
In this release, ThoughtSpot supports charts and tables with a very large number of data values, and shows how much of the data your chart or table displays.
+

* Your search in table form can now have more than 1000 rows.
* Your charts now come with a horizontal scroll bar, to support up to 35,000 data points.
* You can have up to 250 distinct legend items on a chart. *High cardinality overview* ++++<script src="https://fast.wistia.com/embed/medias/q9jggoxmjy.jsonp" async="">++++++</script>++++++<script src="https://fast.wistia.com/assets/external/E-v1.js" async="">++++++</script>+++

[.wistia_embed.wistia_async_q9jggoxmjy.popover=true.popoverAnimateThumbnail=true.popoverBorderColor=4E55FD.popoverBorderWidth=2]#&nbsp;#

See xref:high-cardinality.adoc[Charts and tables with a very large number of data values].+++</dlentry>++++++<dlentry id="keywords">+++New search keywords and changed behavior::::
* *The nested '`top`' keyword* + The new keyword phrase, <a href="{{"/reference/keywords.adoc#top-n-by" | prepend: site.baseurl}}">top _n_ _measure1_ by _attribute_ | _measure2_</a>, enables you to search the top n results by an attribute or a secondary measure.
* *The '`not in`' keyword* + Another keyword phrase, <a href="{{"/reference/keywords.adoc#not-in" | prepend: site.baseurl}}">not in</a>, enables you to find the relative complement of two sets: results that satisfy the outer query that are not in the inner query.
Contrast this with <a href="{{"/reference/keywords.adoc#in" | prepend: site.baseurl}}">in</a> that returns results that are an intersection of the outer and inner query, or 'query within a query'.
* +++<strong>+++Change in behavior for the '`in`' keyword+++</strong>+++ + The <a href="{{"/reference/keywords.adoc#in" | prepend: site.baseurl}}">in</a> keyword returns results that are an intersection of the outer and inner query, or 'query within a query'.
Starting in 6.2, searches with the `in` keyword do not include \{null} values.
To include these \{null} values, create a formula for the relevant attribute in your search, to convert \{null} values to 'unknown,' or some similar word. *Search keywords overview* ++++<script src="https://fast.wistia.com/embed/medias/0m74x2bszt.jsonp" async="">++++++</script>++++++<script src="https://fast.wistia.com/assets/external/E-v1.js" async="">++++++</script>+++

[.wistia_embed.wistia_async_0m74x2bszt.popover=true.popoverAnimateThumbnail=true.popoverBorderColor=4E55FD.popoverBorderWidth=2]#&nbsp;#+++</dlentry>++++++<dlentry id="monitor">+++Monitor [.label.label-beta]#Beta#::::
* *Subscribe others*: To drive adoption of Pinboards, analysts can now subscribe business users to receive daily email notification for the relevant metrics.
See <a href="{{"/spotiq/monitor-headlines.adoc#subscribe-others" | prepend: site.baseurl}}">Subscribe others</a>.
* *UI enhancements*: We made several improvements to the Monitor and Follow features, optimizing the workflow.+++</dlentry>++++++<dlentry id="insights">+++Insights::::
Insights no longer appear on Home page and Pinboard by default, unless that feature is turned on for the cluster.
See <a href="{{"/end-user/introduction/about-navigating-thoughtspot.adoc#insights" | prepend: site.baseurl}}">Finding your way around, Insights</a>.+++</dlentry>++++++<dlentry id="scriptability">+++Scriptability::::
This release introduces expanded support for link:{{ site.baseurl }}/admin/scriptability/scriptability.adoc[exporting and importing ThoughtSpot objects].
You can now export and import the following scriptable objects:

* link:{{ site.baseurl }}/admin/worksheets/worksheet-export.adoc[Worksheets with filters]
* link:{{ site.baseurl }}/admin/scriptability/scriptability-answer.adoc[Answers] [.label.label-beta]#Beta#
* link:{{ site.baseurl }}/admin/scriptability/scriptability-pinboard.adoc[Pinboards] [.label.label-beta]#Beta#+++</dlentry>++++++<dlentry id="aggregate-formulas">+++Aggregate formulas as Worksheet filters::::
You can now use an aggregate formula as a Worksheet filter.
See link:{{ site.baseurl }}/complex-search/aggregation-formulas.adoc#aggregate-filter[Use aggregate formulas as Worksheet filters].+++</dlentry>++++++<dlentry id="formula-parser">+++Formula Parser Improvements::::
ThoughtSpot 6.2 includes improvements to the latency of the formula parser.
Complex formulas that took over 45 seconds to parse are now parsed in 150 milliseconds -- a 300x improvement.
Latency no longer increases exponentially with the depth of the formula nesting, no matter how complex the formula is.+++</dlentry>+++

=== For the Business User
+++<dlentry id="growth-sharing">+++Growth: Sharing::::  Updates to link:{{ site.baseurl }}/end-user/data-view/sharing-for-end-users.adoc[sharing] in 6.2 make the feature more intuitive, and remove moments of friction that can occur when sharing, or trying to access objects for which you have limited permissions.

* *link:{{ site.baseurl }}/end-user/pinboards/share-pinboards.adoc#share-viz[Share a specific visualization within a Pinboard]* so that the email link opens up to that visualization in Explore mode
* *link:{{ site.baseurl }}/end-user/pinboards/share-pinboards.adoc#share-direct-link[Copy a direct link to the Pinboard, Answer, or visualization within a Pinboard]* that you are sharing, so you can separately send that link to users after you share the object with them
* *link:{{ site.baseurl }}/end-user/pinboards/request-access[Request access within a Pinboard or Answer]* if you need edit or underlying data access to the Pinboard or Answer
* *link:{{ site.baseurl }}/end-user/pinboards/share-pinboards.adoc#share-underlying-data[Share underlying data access]* within the sharing modal if the user does not have data access+++</dlentry>++++++<dlentry id="answer-explorer">+++Answer Explorer v2::::
Updates to Answer Explorer in 6.2 introduce a cleaner user interface and allow users to add their own filters, comparisons, measures, and attributes to a visualization while in Explore mode.
See link:{{ site.baseurl }}/end-user/pinboards/answer-explorer.adoc[Answer Explorer] for more information.  *Answer Explorer overview* ++++<script src="https://fast.wistia.com/embed/medias/e69konui8y.jsonp" async="">++++++</script>++++++<script src="https://fast.wistia.com/assets/external/E-v1.js" async="">++++++</script>+++

[.wistia_embed.wistia_async_e69konui8y.popover=true.popoverAnimateThumbnail=true.popoverBorderColor=4E55FD.popoverBorderWidth=2]#&nbsp;#+++</dlentry>++++++<dlentry id="mobile-android">+++Mobile for Android::::
In time for this release, you can download ThoughtSpot app for Android OS from the PlayStore.
See link:{{ site.baseurl }}/admin/mobile/notes-mobile.adoc[ThoughtSpot Mobile release notes] and link:{{ site.baseurl }}/admin/mobile/use-mobile.adoc[ThoughtSpot Mobile overview].+++</dlentry>+++

=== For the Data Engineer
+++<dlentry id="dataflow">+++DataFlow::::
DataFlow is a new graphical, code-free, analyst-friendly approach for easily loading data into ThoughtSpot's in-memory engine.
+ In this release, DataFlow supports a large number of databases (<a href="{{"/data-integrate/dataflow/dataflow-amazon-aurora.adoc" | prepend: site.baseurl}}">Amazon Aurora</a>, <a href="{{"/data-integrate/dataflow/dataflow-amazon-redshift.adoc" | prepend: site.baseurl}}">Amazon Redshift</a>), <a href="{{"/data-integrate/dataflow/dataflow-azure-synapse.adoc" | prepend: site.baseurl}}">Azure Synapse</a>, <a href="{{"/data-integrate/dataflow/dataflow-cassandra.adoc" | prepend: site.baseurl}}">Cassandra</a>, <a href="{{"/data-integrate/dataflow/dataflow-google-bigquery.adoc" | prepend: site.baseurl}}">Google BigQuery</a>, <a href="{{"/data-integrate/dataflow/dataflow-hive.adoc" | prepend: site.baseurl}}">Hive</a>, <a href="{{"/data-integrate/dataflow/dataflow-ibm-db2.adoc" | prepend: site.baseurl}}">IBM Db2</a>, <a href="{{"/data-integrate/dataflow/dataflow-mariadb.adoc" | prepend: site.baseurl}}">MariaDB</a>, <a href="{{"/data-integrate/dataflow/dataflow-mongodb.adoc" | prepend: site.baseurl}}">MongoDB</a>, <a href="{{"/data-integrate/dataflow/dataflow-mysql.adoc" | prepend: site.baseurl}}">MySQL</a>, <a href="{{"/data-integrate/dataflow/dataflow-netezza.adoc" | prepend: site.baseurl}}">Netezza</a>, <a href="{{"/data-integrate/dataflow/dataflow-oracle.adoc" | prepend: site.baseurl}}">Oracle</a>, <a href="{{"/data-integrate/dataflow/dataflow-postgresql.adoc" | prepend: site.baseurl}}">PostgreSQL</a>, <a href="{{"/data-integrate/dataflow/dataflow-presto.adoc" | prepend: site.baseurl}}">Presto</a>, <a href="{{"/data-integrate/dataflow/dataflow-sap-adaptive-server-enterprise.adoc" | prepend: site.baseurl}}">SAP Adaptive Server Enterprise</a>, <a href="{{"/data-integrate/dataflow/dataflow-sap-hana.adoc" | prepend: site.baseurl}}">SAP HANA</a>, <a href="{{"/data-integrate/dataflow/dataflow-sap-sql-anywhere.adoc" | prepend: site.baseurl}}">SAP SQL Anywhere</a>, <a href="{{"/data-integrate/dataflow/dataflow-sql-server.adoc" | prepend: site.baseurl}}">SQL Server</a>, <a href="{{"/data-integrate/dataflow/dataflow-snowflake.adoc" | prepend: site.baseurl}}">Snowflake</a>, <a href="{{"/data-integrate/dataflow/dataflow-splice-machine.adoc" | prepend: site.baseurl}}">Splice Machine</a>, and <a href="{{"/data-integrate/dataflow/dataflow-teradata.adoc" | prepend: site.baseurl}}">Teradata</a>), file systems (<a href="{{"/data-integrate/dataflow/dataflow-amazon-s3.adoc" | prepend: site.baseurl}}">Amazon S3</a>, <a href="{{"/data-integrate/dataflow/dataflow-azure-blob-storage.adoc" | prepend: site.baseurl}}">Azure Blob Storage</a>, <a href="{{"/data-integrate/dataflow/dataflow-files.adoc" | prepend: site.baseurl}}">Flat Files</a>, <a href="{{"/data-integrate/dataflow/dataflow-google-cloud-storage.adoc" | prepend: site.baseurl}}">Google Cloud Storage</a>, <a href="{{"/data-integrate/dataflow/dataflow-hdfs.adoc" | prepend: site.baseurl}}">HDFS</a>), and one application, <a href="{{"/data-integrate/dataflow/dataflow-salesforce.adoc" | prepend: site.baseurl}}">Salesforce</a>. *DataFlow overview* ++++<script src="https://fast.wistia.com/embed/medias/0850igo7wv.jsonp" async="">++++++</script>++++++<script src="https://fast.wistia.com/assets/external/E-v1.js" async="">++++++</script>+++

[.wistia_embed.wistia_async_0850igo7wv.popover=true.popoverAnimateThumbnail=true.popoverBorderColor=4E55FD.popoverBorderWidth=2]#&nbsp;#+++</dlentry>++++++<dlentry id="embrace">+++Embrace::::  In this release, Embrace supports two new data warehouses and includes new features.

New data warehouses:

* *Teradata* + Teradata Vantage version 16.20 or later is required.
For more information, see <a href="{{"/data-integrate/embrace/embrace-teradata.adoc" | prepend: site.baseurl}}">Teradata overview</a>. +

* *SAP HANA* [.label.label-beta]#Beta# + SAP HANA version 2.0 or later is required.
For more information, see <a href="{{"/data-integrate/embrace/embrace-hana.adoc" | prepend: site.baseurl}}">SAP HANA overview</a>.

New features:

* Ability to remove columns from a connection.
* Actual SQL is displayed in the query visualizer.
This allows analysts to check the actual external database query so they can easily validate the output.
* A summary of connected tables/columns is displayed in the add/edit connection workflow.
* Improved performance when creating or editing a connection.+++</dlentry>++++++<dlentry id="tsload">+++tsload connector::::
This release introduces a new option for loading data in bulk, called tsload connector.
It is a collection of APIs that allow you to directly, and more quickly load your data into the ThoughtSpot Falcon database.
For more information, see <a href="{{"/admin/loading/load-with-tsload.adoc" | prepend: site.baseurl}}">Use the tsload connector to load data</a>.+++</dlentry>+++

=== For the IT Ops Engineer
+++<dlentry id="amazon-linux-2">+++Amazon Linux 2 Deployment::::
This release of ThoughtSpot introduces deployment support for https://aws.amazon.com/amazon-linux-2/[Amazon Linux 2].
This decouples the OS and application files we shipped together in previous releases, and gives you the flexibility to run ThoughtSpot on an Amazon Linux 2 image that your organization manages internally.
ThoughtSpot certifies Amazon Linux 2 on the AWS platform.
To deploy ThoughtSpot on Amazon Linux 2, you must have the Ansible tarball;
you can obtain the tarball through your ThoughtSpot contact.
For more information, see the <a href="{{"/appliance/amazon-linux-2/al2-overview.adoc" | prepend: site.baseurl}}">Amazon Linux 2 Deployment Overview</a>.+++</dlentry>++++++<dlentry id="admin-portal">+++Admin Console::::
This release of ThoughtSpot introduces the xref:admin-portal.adoc[Admin Console], providing you with an intuitive, user-friendly interface to accomplish most of the necessary tasks for administering ThoughtSpot.
You can accomplish the following tasks from the Admin Console:

* xref:users.adoc[Manage ThoughtSpot users]
* xref:groups.adoc[Manage ThoughtSpot groups]
* xref:authentication-local.adoc[Manage local authentication]
* xref:authentication-saml.adoc[Configure SAML authentication]
* xref:authentication-active-directory.adoc[Configure LDAP authentication through Active Directory]
* xref:ssl-configure.adoc[Configure SSL]
* xref:reverse-ssh-tunnel.adoc[Configure a reverse SSH tunnel for Support]
* xref:smtp-configure.adoc[Set the relay host for SMTP (email)]
* xref:customize-help.adoc[Customize ThoughtSpot help]
* xref:customize-actions-menu.adoc[Customize Answer actions menu]
* xref:system-overview-pinboard.adoc[View System Overview Pinboard]
* xref:system-cluster-pinboard.adoc[View System Cluster Pinboard]
* xref:system-alerts-pinboard.adoc[View System Alerts Pinboard]
* xref:available-update.adoc[Monitor available cluster updates] *Admin Console overview* ++++<script src="https://fast.wistia.com/embed/medias/ic9rg4gru8.jsonp" async="">++++++</script>++++++<script src="https://fast.wistia.com/assets/external/E-v1.js" async="">++++++</script>+++

[.wistia_embed.wistia_async_ic9rg4gru8.popover=true.popoverAnimateThumbnail=true.popoverBorderColor=4E55FD.popoverBorderWidth=2]#&nbsp;#+++</dlentry>++++++<dlentry id="in-memory-data-compression">+++In-memory data compression::::
ThoughtSpot release 6.2 includes improvements to in-memory data compression.
These improvements lower your RAM requirements and reduce the number of VMs you need for in-memory data, when deploying on a cloud platform.
In release 6.2, ThoughtSpot added two new compression algorithms to the Dictionary compression that ThoughtSpot already supports.
ThoughtSpot now supports *LZ4*, for `INT`, `BIGINT`, `DOUBLE`, and `FLOAT` data types, and *RLE*, for strings.
See link:{{ site.baseurl }}/admin/architecture/data-compression.adoc[In-memory data compression] for more information.+++</dlentry>++++++<dlentry id="falcon-monitor">+++Falcon monitoring Pinboards::::
In ThoughtSpot release 6.2, there are 4 new Pinboards, based on Falcon metrics, that are available to system administrators.
Use the Falcon monitoring system Pinboards for an overview of Falcon, ThoughtSpot's in-memory database, and its health, based on query, data load, and varz metrics.
You can use these Pinboards for proactive monitoring, or, with help from link:{{ site.baseurl }}/appliance/contact.adoc[ThoughtSpot Support], for debugging.
See link:{{ site.baseurl }}/admin/system-monitor/falcon-monitor.adoc[Falcon monitoring Pinboards] for more information.+++</dlentry>++++++<dlentry id="use-agreement">+++In-app acceptance of ThoughtSpot's use agreement::::
You can now sign ThoughtSpot's end-user use agreement from the application itself.
Even if you previously signed a paper copy of the use agreement, an admin *_must_* sign the agreement in the application, within 30 days of your upgrade to release 6.2.
See link:{{ site.baseurl }}/admin/setup/use-agreement.adoc[ThoughtSpot use agreement] for more information.+++</dlentry>+++

[#beta-program]
== Beta Programs

If you are interested in seeing some of our newest features, we want to add you to our testing group.
ThoughtSpot is looking for people with all levels of experience: end-users, analysts, administrators, configurators, and so on.
We like to have a diversity of experience and perspective, and want to hear from you.
Because we strive for excellence, we will partner with you to adjust the final details of our offerings based on your feedback.

=== Monitor

Please contact us if you are interested in participating in the link:mailto:BetaProgram@thoughtspot.com?subject=Monitor%20Beta%20Program%20Request[Monitor Beta Program], for monitoring selected metrics over time.

=== Scriptability

Please contact us if you are interested in participating in the link:mailto:BetaProgram@thoughtspot.com?subject=Scriptability%20Beta%20Program%20Request[Scriptability Beta Program], for migrating and updating Answers and Pinboards in a flat-file format.

[#upgrade-paths]
== Supported Upgrade Paths

If you are running one of the following versions, you can upgrade to the 6.2.1 release directly:

* 6.0.x to 6.2.1
* 6.1.x to 6.2.1
* 6.2 to 6.2.1

This includes any hotfixes or customer patches on these branches.

If you are running a different version, you must do a multiple pass upgrade.
First, upgrade to version 6.0.x, 6.1.x, or 6.2, and then to the 6.2.1 release.

NOTE: To successfully upgrade your ThoughtSpot cluster, all user profiles must include a valid email address.
Without valid email addresses, the upgrade is blocked.
