= RHEL installation prerequisites
:last_updated: 10/19/2020


Prepare the system and ThoughtSpot clusters for installation.

[cols=2*]
|===
| &#10063;
| <<set-up-hosts,1.
Set up hosts for the ThoughtSpot cluster>>

| &#10063;
| <<partition-hosts,2.
Partition the hosts>>

| &#10063;
| <<install-rhel,3.
Install RHEL version 7.8 or 7.9 on all hosts>>

| &#10063;
| <<linux-kernel-version,4.
Ensure that your Linux kernel is on version 3.10.0-1127.19.1>>

| &#10063;
| <<enable-hosts,5.
Enable the hosts to download RHEL packages>>

| &#10063;
| <<enable-ansible,6.
Enable an Ansible Control Server>>

| &#10063;
| <<disable-selinux,7.
Disable SELinux>>
|===

[#set-up-hosts]
== Set up hosts for the ThoughtSpot cluster

Set up hosts for the ThoughtSpot cluster on your chosen platform.
Please refer to the relevant deployment sections in our documentation for the exact specification for the hosts: CPU, memory, and disks.

* ThoughtSpot-certified hardware appliance manufactured by link:{{ site.baseurl }}/appliance/hardware/installing-dell.html[DELL]
* ThoughtSpot-certified hardware appliance manufactured by link:{{ site.baseurl }}/appliance/hardware/installing-the-smc.html[SMC]
* link:{{ site.baseurl }}/appliance/aws/configuration-options.html[Amazon Web Services (AWS) EC2]
* link:{{ site.baseurl }}/appliance/gcp/configuration-options.html[Google Cloud Platform (GCP)]
* link:{{ site.baseurl }}/appliance/vmware/vmware-intro.html[VMware]
* link:{{ site.baseurl }}/appliance/azure/configuration-options.html[Microsoft Azure]

[#partition-hosts]
== Partition the hosts

Ensure that all ThoughtSpot hosts meet the following partition and sizing requirements.
All drives must be SSDs.

. At least 20 GB available on the root drive, for yum packages and system logs.
. At least 200 GB for ThoughtSpot installation, either on a secondary drive or as a separate partition on the root drive.
For ThoughtSpot-certified hardware platforms, link:{{ site.baseurl }}/appliance/hardware/installing-dell.html[Dell] and link:{{ site.baseurl }}/appliance/hardware/installing-the-smc.html[Super Micro Computer], you must use a secondary drive, since the root drive has a limit of 200 GB.
+
{% include note.html content="This drive must be separate from the data drive(s)." %}

[#install-rhel]
== Install RHEL on hosts

ThoughtSpot is certified with RHEL versions 7.8 and 7.9;
we *do not* support other versions of RHEL, including 7.7, 8, and 8.1.
Install RHEL version 7.8 or 7.9, and ensure that your <<linux-kernel-version,linux kernel version>> is 3.10.0-1127.19.1.

[#linux-kernel-version]
=== Linux kernel version

Your Linux kernel *_must_* be on version 3.10.0-1127.19.1.
RHEL 7.8 used to come with a Linux kernel of version 3.10.x, which has a bug that causes nodes to reboot unexpectedly.
The default Linux kernel version for RHEL 7.8 is now 3.10.0-1127.19.1.
However, you may have an older RHEL 7.8, with a Linux kernel of version 3.10.x.
You must upgrade to 3.10.0-1127.19.1.
If you have trouble upgrading your Linux kernel to version 3.10.0-1127.19.1, link:{{ site.baseurl }}/appliance/contact.html[contact ThoughtSpot Support].
This is a requirement for *_all_* platforms: appliance, cloud, and VMware.

If you are using RHEL version 7.9, the default Linux kernel never had this bug.

{% include warning.html content="If your Linux kernel version is not 3.10.0-1127.19.1, you may run into unexpected node reboots and possible loss of data." %}

[#enable-hosts]
== Enable the hosts to download RHEL packages

*Repositories*

* *Yum repositories*: you must enable the following Yum repositories in your cluster: `epel`, `nux-desktop`, `pgdg95`, `rhel`, `rhel-optional`, `rhel-extras`.

* *Python repository*: for Python, ensure the machine is able to reach the `PyPI` repository located at https://pypi.python.org/.

* *R repository*: for R, ensure the machine is able to reach the `CRAN` repository located at https://cran.rstudio.com/.

Make sure that you can download RHEL packages to all hosts, either from the <<official-repositories,official package repositories>>, or from a <<mirror-repositories,mirror repository>> owned and managed by your organization.

If you cannot access the RHEL repositories, there is no mirror repository in your organization, or you are unable to access Yum, Python, or R repositories, please link:{{ site.baseurl }}/appliance/contact.html[contact ThoughtSpot Support].

*Official package repositories*

If the hosts of your ThoughtSpot cluster can access external repositories, either directly or through a proxy, your cluster is online.
You can then proceed to download <<yum-repositories,Yum>>, <<python-repositories,Python>>, and <<r-repositories,R>> package repositories.

*Internal mirror repository*

If the hosts of your ThoughtSpot cluster have access to an internal repository that mirrors the public repositories, copy the <<yum-repositories,Yum>>, <<python-repositories,Python>>, and <<r-repositories,R>> package repositories to your hosts.

[#enable-ansible]
== Enable an Ansible Control Server

Configure an Ansible Control Server, on a separate host, to run the Ansible playbook that ThoughtSpot supplies.
You must install both `rsync` and Ansible on the Ansible Control Server host.

[#disable-selinux]
== Disable SELinux or run it in permissive mode

ThoughtSpot does not support policies that enforce SELinux.
We recommend that you disable SELinux, or run it in permissive mode.
