= ThoughtSpot Modeling Language
:last_updated: 12/16/2020

:redirect_from: /admin/scriptability/tsl.html", "/admin/ts-cloud/tml.html", "/admin/worksheets/yaml-worksheet.html", "/admin/scriptability/tsl-pinboard.html", "/admin/scriptability/tsl-answer.html", "/admin/scriptability/tsl-view.html", "/6.3.0/admin/ts-cloud/tsl.html", "/6.3.0/admin/scriptability/tsl-pinboard.html", "/6.3.0/admin/scriptability/tsl-answer.html", "/6.3.0/admin/scriptability/tsl-view.html", "/6.3.0/admin/worksheets/yaml-worksheet.html", "/6.3.0.CU1/admin/ts-cloud/tsl.html", "/6.3.0.CU1/admin/scriptability/tsl-pinboard.html", "/6.3.0.CU1/admin/scriptability/tsl-answer.html", "/6.3.0.CU1/admin/scriptability/tsl-view.html", "/6.3.0.CU1/admin/worksheets/yaml-worksheet.html

Use ThoughtSpot Modeling Language to modify a Worksheet, View, table, Pinboard, SpotIQ result, or Answer in a flat-file format. Then you can migrate the object to a different cluster, or restore it to the same cluster.

To work with Scriptable <<syntax-worksheets,Worksheets>>, <<syntax-views,Views>>, <<syntax-tables,tables>>, <<syntax-answers,Answers>>, <<syntax-pinboards,SpotIQ results>>, and <<syntax-pinboards,Pinboards>> in ThoughtSpot, you can download these objects to a flat file in `TML` format, modify it, and subsequently upload this file either to the same cluster, or to a different cluster.
To learn how to export, change, and update Worksheets, Views, Tables, Answers, SpotIQ results, and Pinboards, see link:{{ site.baseurl }}/admin/scriptability/scriptability.html[Scriptability].

[#syntax-worksheets]
== Syntax of the Worksheet TML file

The `TML` file for Scriptable Worksheets has a specific syntax.

See the <<parameters,Parameters>> section for details about the keywords used in this example.

You may not see each of these parameters in your own TML files, depending on whether each variable is explicitly defined.
For example, if you do not have any filters on your Worksheet, the `filters` parameter does not appear.
You can add that variable to the TML file to specify filters for your Worksheet.

....

worksheet:
  name: <worksheet_name>
  description:
    This is a multi-line description of the worksheet
    Description line 2
  tables:
  - name: <table_name_1>
    id : <optional_table_id_1>
    fqn : <optional_GUID_of_table_name_1>
  - name: <table_name_2>
  - name: <table_name_n>
  joins:
  - name: <join_name_1>
    source: <source_table_name>
    destination: <destination_table_name>
    type: [RIGHT_OUTER | LEFT_OUTER | INNER | OUTER]
    on: <on_string>
    is_one_to_one: [ false | true ]
  - ...
  table_paths:
  - id: <table_path_name_1>
    table: <table_name_1>
    join_path:
    - join:
      - <join_name_1>
  - id: <table_path_name_2>
    table: <table_name_2>
    join_path:
    - {}
  - id: <table_path_name_3>
    table: <table_name_3>
    join_path:
    - join:
      - <join_name_1>
    - join:
      - <join_name_2>
      - <join_name_3>
    - join:
      - <join_name_4>
      - <join_name_5>
      - <join_name_6>
  formulas:
  - name: <formula_name_1>
    expr: <formula_definition_1>
    [id]: <optional_unique_identifier>
  - name: <formula_name_2>
    expr: <formula_definition_2>
  - name: <formula_name_3>
    expr: <formula_definition_3>
  filters:
  - column: <filtered_column_name_1>
    oper: <filter_operator>
    values: <filtered_values>
    - value 1
    - value 2
    - value n
  - column: <filtered_column_name_2>
  worksheet_columns:
  - name: <column_name_1>
    description: <optional_column_description>
    column_id: <column_id_1>
    properties:
      column_type: [ MEASURE | ATTRIBUTE ]
      aggregation: [ SUM | COUNT | AVERAGE | MAX | MIN |
                     COUNT_DISTINCT | NONE | STD_DEVIATION | VARIANCE]
      index_type: [ DONT_INDEX | DEFAULT | PREFIX_ONLY |
                    PREFIX_AND_SUBSTRING | PREFIX_AND_WORD_SUBSTRING ]
 	    index_priority: <index_priority>
      synonyms :
             <synonym_1>
             <synonym_2>
      is_attribution_dimension : [true | false]
      is_additive : [ true | false ]
      calendar : [ default | calendar_name ]
      format_pattern : <format_pattern_string>
      currency_type :
        is_browser : true
          OR
        column : <column_name>
          OR
        iso_code : <valid_ISO_code>
      is_hidden: [ true | false ]
      geo_config :
        latitude : true
          OR
        longitude : true
          OR
        country : true
          OR
        region_name:
        - country : <name_supported_country>
        - region_name : <region_name_in_UI>
      spotiq_preference: <spotiq_preference_string>
      search_iq_preferred: [ true | false ]
    name: <column_name_2>
    description: <column_description>
    column_id: <column_id_2>
    ...
  properties:
    is_bypass_rls: [ true | false ]
    join_progressive: [ true | false ]
guid: <worksheet_guid>
....

[#syntax-views]
== Syntax of the View TML file

The `TML` file for Scriptable Views has a specific syntax.

See the <<parameters,Parameters>> section for details about the keywords used in this example.

You may not see each of these parameters in your own TML files, depending on whether each variable is explicitly defined.
For example, if you do not have a description for your View, the `description` parameter does not appear.
You can add that variable to the TML file to specify a description for your View.

....

view:
  name: <view_name>
  description:
    This is a multi-line description of the View.
    Description line 2
  tables:
    identity:
    - id: <table_id_1>
      name: <table_name_1>
      fqn: <optional_table_guid_1>
    identity:
    - id: <table_id_n>
      name: <table_name_n>
      fqn: <optional_table_guid_n>
  joins:
  - name: <join_name_1>
    source: <source_table_name>
    destination: <destination_table_name>
    type: [RIGHT_OUTER | LEFT_OUTER | INNER | OUTER]
    on: <on_string>
    is_one_to_one: [ false | true ]
  table_paths:
  - id: <table_path_name_1>
    table: <table_name_1>
    join_path:
    - {}
  formulas:
  - id: <formula_id_1>
    name: <formula_name_1>
    expr: <formula_definition_1>
    properties: <formula_properties_1>
      column_type: [ MEASURE | ATTRIBUTE ]
      data_type: [ BOOL | VARCHAR | DOUBLE | FLOAT | INT | BIGINT | DATE | DATETIME | TIMESTAMP | TIME ]
      aggregation: [ SUM | COUNT | AVERAGE | MAX | MIN |
                         COUNT_DISTINCT | NONE | STD_DEVIATION | VARIANCE]
  - id: <formula_id_n>
    name: <formula_name_n>
    expr: <formula_definition_n>
    properties: <formula_properties_n>
  filters:
  - column: <filtered_column_name_1>
    oper: <filter_operator>
    values: <filtered_values>
    - value 1
    - value 2
  - column: <filtered_column_name_n>
  view_columns:
  - name: <column_name_1>
    description: <optional_column_description>
    column_id: <column_id_1>
    phrase: <phrase_string_1>
    properties:
      column_type: [ MEASURE | ATTRIBUTE ]
      aggregation: [ SUM | COUNT | AVERAGE | MAX | MIN |
                     COUNT_DISTINCT | NONE | STD_DEVIATION | VARIANCE]
      index_type: [ DONT_INDEX | DEFAULT | PREFIX_ONLY |
                    PREFIX_AND_SUBSTRING | PREFIX_AND_WORD_SUBSTRING ]
 	    index_priority: <index_priority>
      synonyms :
             <synonym_1>
             <synonym_2>
      is_attribution_dimension : [true | false]
      is_additive : [ true | false ]
      calendar : [ default | calendar_name ]
      format_pattern : <format_pattern_string>
      currency_type :
        is_browser : true
          OR
        column : <column_name>
          OR
        iso_code : <valid_ISO_code>
      is_hidden: [ true | false ]
      geo_config :
        latitude : true
          OR
        longitude : true
          OR
        country : true
          OR
        region_name:
        - country : <name_supported_country>
        - region_name : <region_name_in_UI>
      spotiq_preference: <spotiq_preference_string>
      search_iq_preferred: [ true | false ]
    name: <column_name_2>
    description: <column_description>
    column_id: <column_id_2>
    ...
  query: <query_string>
guid: <view_guid>
....

[#syntax-tables]
== Syntax of the table TML file

The `TML` file for scriptable tables has a specific syntax.

See the <<parameters,Parameters>> section for details about the keywords used in this example.

You may not see each of these parameters in your own TML files, depending on whether each variable is explicitly defined.
For example, if you did not define an `index_priority` for your table, the `index_priority` parameter does not appear.
You can add that variable to the TML file to specify an index priority for the table.

....

table:
  name: <table_name>
  db: <database_name>
  schema: <schema_name>
  db_table: <database_table_name>
  connection:
    name: <connection_name>
    type: <connection_type>
  columns:
  - name: <column_name_1>
    db_column_name: <database_column_name>
    is_primary_key: [true | false]
    is_foreign_key: [true | false]
    data_type: [ BOOL | VARCHAR | DOUBLE | FLOAT | INT32 | INT64 | DATE | TIME ]
    properties:
      column_type: [ MEASURE | ATTRIBUTE ]
      aggregation: [ SUM | COUNT | AVERAGE | MAX | MIN |
                     COUNT_DISTINCT | NONE | STD_DEVIATION | VARIANCE]
      index_type: [ DONT_INDEX | DEFAULT | PREFIX_ONLY |
                    PREFIX_AND_SUBSTRING | PREFIX_AND_WORD_SUBSTRING ]
      index_priority: <index_priority>
      synonyms :
             <synonym_1>
             <synonym_2>
      is_attribution_dimension : [true | false]
      is_additive : [ true | false ]
      calendar : [ default | calendar_name ]
      format_pattern : <format_pattern_string>
      currency_type :
        is_browser : true
          OR
        column : <column_name>
          OR
        iso_code : <valid_ISO_code>
      is_hidden: [ true | false ]
      geo_config :
        latitude : true
          OR
        longitude : true
          OR
        country : true
          OR
        region_name:
        - country : <name_supported_country>
        - region_name : <region_name_in_UI>
      spotiq_preference: <spotiq_preference_string>
      search_iq_preferred: [ true | false ]
  - name: <column_name_2>
  - name: <column_name_n>
guid: <table_guid>
....

[#syntax-answers]
== Syntax of the Answer TML file

The `TML` file for Scriptable Answers has a specific syntax.

See the <<parameters,Parameters>> section for details about the keywords used in this example.

You may not see each of these parameters in your own TML files, depending on whether each variable is explicitly defined.
For example, if you did not define any conditional formatting, the `conditional_formatting` variable does not appear.
You can add that variable in the TML file to specify conditional formatting.

....

answer:
  name: <answer_name>
  description:
    This is a multi-line description of the answer
    Description line 2
  tables:
  - id: <table_id>
    name: <table_name_1>
    fqn : <optional_GUID_of_table_name_1>
  joins:
  - name: <join_name_1>
    source: <source_table_name>
    destination: <destination_table_name>
    type: [RIGHT_OUTER | LEFT_OUTER | INNER | OUTER]
    on: <on_string>
    is_one_to_one: [ false | true ]
  - ...
  table_paths:
  - id: <table_path_name_1>
    table: <table_name_1>
    join_path:
    - {}
  formulas:
  - id: <formula_id_1>
    name: <formula_name_1>
    expr: <formula_definition_1>
    properties: <formula_properties_1>
      column_type: [ MEASURE | ATTRIBUTE ]
      data_type: [ BOOL | VARCHAR | DOUBLE | FLOAT | INT | BIGINT | DATE | DATETIME | TIMESTAMP | TIME ]
      aggregation: [ SUM | COUNT | AVERAGE | MAX | MIN |
                     COUNT_DISTINCT | NONE | STD_DEVIATION | VARIANCE]
  - id: <formula_id_2>
    name: <formula_name_2>
    expr: <formula_definition_2>
    properties: <formula_properties_2>
  - id: <formula_id_3>
    name: <formula_name_3>
    expr: <formula_definition_3>
    properties: <formula_properties_3>
  search_query: <search_query_string>
  answer_columns:
  - id: <column_id_1>
    name: <column_name_1>
    custom_name: <custom_name_1>
  - name: <column_name_2>
  table:
    table_columns:
    - column_id: <column_id_1>
      conditional_formatting:
      - range:
        min: <conditional_formatting_minimum>
        max: <conditional_formatting_maximum>
      - rule: <conditional_formatting_rule_1>
          range:
            min: <conditional_formatting_minimum>
            max: <conditional_formatting_maximum>
          color: <color_string>
          plotAsBand: [ true | false ]
      - rule: <conditional_formatting_rule_2>
      show_headline: [ true | false ]
      headline_aggregation: <headline_aggregation_string>
    - column_id: <column_id_2>
    ordered_column_ids:
    - column_id: <column_id_1>
    - column_id: <column_id_2>
    client_state: <client_state_string>
  chart:
    type: <chart_type>
    chart_columns: <chart_column_1>
    - column_id: <column_id_1>
      conditional_formatting:
      - rule: <conditional_formatting_rule_1>
          range:
            min: <conditional_formatting_minimum>
            max: <conditional_formatting_maximum>
          color: <color_string>
          plotAsBand: [ true | false ]
      - rule: <conditional_formatting_rule_2>
    - column_id: <column_id_2>
    axis_configs: <axis_config_1>
    - x:
      - column_id: <column_id_x_axis>
    - y:
      - column_id: <column_id_y_axis>
      color:
      - column_id: <column_id_color>
    axis_configs: <axis_config_2>
    locked: [ true | false ]
    client_state: <client_state_string>
  display_mode: <display_mode_string>
guid: <answer_guid>
....

[#syntax-pinboards]
== Syntax of the Pinboard and SpotIQ result TML file

The `TML` file for Scriptable Pinboards has a specific syntax.
Note that SpotIQ results are in the form of Pinboards.
Use the Pinboard TML syntax to edit a SpotIQ TML file.

See the <<parameters,Parameters>> section for details about the keywords used in this example.

You may not see each of these parameters in your own TML files, depending on whether each variable is explicitly defined.
For example, if you do not have any filters on your Pinboard, the `filters` parameter does not appear.
You can add that variable to the TML file to specify filters for your Pinboard.

....

pinboard:
  name: <pinboard_name>
  description:
    This is a multi-line description of the pinboard
    Description line 2
  visualizations:
  - answer:
    This section includes all the Answer specification for a visualization, from name to display_mode, in the Answer syntax section above.
    id: <viz_id_1>
  - answer:
    This section includes all the Answer specification for a second visualization. In this case, the visualization is a headline.
    id: <viz_id_2>
    display_headline_column: <headline_column>
  filters:
  - column: <filtered_column_name_1>
    oper: <filter_operator>
    values: <filtered_values>
    - value 1
    - value 2
  - column: <filtered_column_name_2>
  layout:
    tiles:
    - visualization_id: <visualization_id_1>
      size: <viz_id_1_size>
    - visualization_id: <visualization_id_2>
guid: <pinboard_guid>
....

[#parameters]
== Parameters of TML files
+++<dlentry id="aggregation">+++aggregation::::
The default aggregation of the Worksheet, View, or Table column, or the aggregation of the output for a formula.
+ Aggregation options depend on the data type.
+ Possible values: `SUM`, `COUNT`, `AVERAGE`, `MAX`, `MIN`, `COUNT_DISTINCT`, `NONE`, `STD_DEVIATION`, and `VARIANCE` + Default: `SUM` ++++</dlentry>++++++<dlentry id="answer">+++answer::::  Top-level container for all object definitions within an Answer.+++</dlentry>++++++<dlentry id="answer_columns">+++answer_columns::::  A list of columns generated by the search query.+++</dlentry>++++++<dlentry id="axis_configs">+++axis_configs::::
Specifies the columns for each axis on a chart.
If you are displaying a column chart with a line chart overlaying it, for example, you would need to specify more than one `axis_config`.+++</dlentry>++++++<dlentry id="calendar">+++calendar::::
Specifies the calendar used by a date column + Can be the Gregorian calendar (`default`), a fiscal calendar, or any custom calendar.
+ See link:../setup/set-custom-calendar.html[Set up a custom calendar]+++</dlentry>++++++<dlentry id="chart">+++chart::::  Contains configuration for the Answer, if it displays in chart format.+++</dlentry>++++++<dlentry id="chart_columns">+++chart_columns::::  A list of columns in the chart.+++</dlentry>++++++<dlentry id="client_state">+++client_state::::  A JSON string with more advanced chart and table configuration.+++</dlentry>++++++<dlentry id="color">+++color::::  Color to use for conditional formatting or for the columns of an Answer in chart form, in the form of a HEX value.+++</dlentry>++++++<dlentry id="column">+++column::::  The id of the column being filtered on.+++</dlentry>++++++<dlentry id="columns">+++columns::::  The columns in the table.+++</dlentry>++++++<dlentry id="column_id">+++column_id::::
The `id` of the Worksheet or View column.
+ For Answers, `column_id` refers to how the column appears in the query.
For example, if you sorted by `Quarter` in your search, from the `Commit Date` column, the `column_id` of the column is `Quarter(Commit Date)`.+++</dlentry>++++++<dlentry id="column_type">+++column_type::::
The type of data the column represents.
For a formula, the `column_type` refers to the output of the formula.
+ Possible values: `MEASURE` or `ATTRIBUTE` + For Worksheets, the default is: `MEASURE` + For formulas, the default depends on the <<data_type,data_type>>.
If the data type is `INT` or `BIGINT`, the formula output's `column_type` defaults to `Measure`.
If the data type is `BOOL`, `VARCHAR`, `DOUBLE`, `FLOAT`, `DATE`, `DATETIME`, or `TIME`, the formula output's `column_type` defaults to `Attribute`.+++</dlentry>+++
+
////
<dlentry id="column_width">
    <dt>column_width</dt>
    <dd>The width of the table column.</dd>
  </dlentry> not in v1
////+++<dlentry id="conditional_formatting">+++conditional_formatting::::  Conditional formatting for the chart or table of an Answer.+++</dlentry>++++++<dlentry id="connection">+++connection::::  A way to identify the external data warehouse connection that the table resides in.+++</dlentry>++++++<dlentry id="currency_type">+++currency_type::::  The source of currency type + One of: +

* `is_browser : true` infer the currency data from the locale of your browser
* `column : <column_name>` extracts the currency information from a specified column
* `iso_code : <valid_ISO_code>` applies currency based on the ISO code;
see https://www.iso.org/iso-4217-currency-codes.html[ISO 4217 Currency Codes]

See link:../data-modeling/set-format-pattern-numbers.html#set-currency-type[Set currency type]+++</dlentry>++++++<dlentry id="custom_name">+++custom_name::::  Optional display name for a column.+++</dlentry>++++++<dlentry id="data_type">+++data_type::::
The data type of the formula output or column.
If the data type is `INT` or `BIGINT`, the formula output's `column_type` defaults to `Measure`.
If the data type is `BOOL`, `VARCHAR`, `DOUBLE`, `FLOAT`, `DATE`, `DATETIME`, or `TIME`, the formula output's `column_type` defaults to `Attribute`.
The possible data types are `Boolean`, `Text`, `Date`, `Datetime`, `Time`, `Numeric`, and `Decimal`.+++</dlentry>++++++<dlentry id="db">+++db::::
The database that a table resides in.
Note that this is not the same as the data warehouse (Falcon, Amazon Redshift, or Snowflake, for example).+++</dlentry>++++++<dlentry id="db_column_name">+++db_column_name::::
The name of the column in the database.
Note that this database is not the same as the data warehouse (Falcon, Amazon Redshift, or Snowflake, for example).+++</dlentry>++++++<dlentry id="db_table">+++db_table::::
The name of the table in the database.
Note that this database is not the same as the data warehouse (Falcon, Amazon Redshift, or Snowflake, for example).+++</dlentry>++++++<dlentry id="description">+++description::::  The text that describes an object: a `worksheet`, a `worksheet_column`, `answer`, `pinboard`, `view`, `view_column` and so on.+++</dlentry>++++++<dlentry id="destination">+++destination::::  Name of destination table or view of the join+++</dlentry>++++++<dlentry id="display_mode">+++display_mode::::
Determines whether the Answer displays as a chart or a table.
Specify either `CHART_MODE` or `TABLE_MODE`.+++</dlentry>++++++<dlentry id="display_headline_column">+++display_headline_column::::  If the visualization is a headline, this parameter specifies the column the headline comes from.+++</dlentry>++++++<dlentry id="expr">+++expr::::  The definition of the formula+++</dlentry>++++++<dlentry id="filters">+++filters::::  Contains specifications for Pinboard, View, and Worksheet filters.+++</dlentry>++++++<dlentry id="format_pattern">+++format_pattern::::  The format pattern string that controls the display of a number, date, or currency column + See link:../data-modeling/set-format-pattern-numbers.html[Set number, date, and currency formats]+++</dlentry>++++++<dlentry id="formulas">+++formulas::::
The list of formulas in the Worksheet, View, or Answer.
+ Each formula is identified by `name`, the `expr` (expression), and an optional `id` attribute.+++</dlentry>++++++<dlentry id="fqn">+++fqn::::
The table's GUID.
You can find this string of letters and numbers at the end of the URL for that table.
For example, in https://<company>.thoughtspot.com/#/data/tables/34226aaa-4bcf-4d6b-9045-24cb1e9437cb, the GUID is 34226aaa-4bcf-4d6b-9045-24cb1e9437cb.+++</dlentry>++++++<dlentry id="geo_config">+++geo_config::::  Specifies the geographic information of a column + One of: +

* `latitude : true` for columns that specify the latitude
* `longitude : true` for columns that specify the longitude
* `country : true` for columns that specify the country
* `region_name` for specifying a region in a country + Uses two paired parameters: + - `country: <country_name>` + - `region_name: <region_name_in_UI>`, which can be State, Postal Code, District, and so on.

See link:../data-modeling/model-geo-data.html[Add a geographical data setting]+++</dlentry>++++++<dlentry id="guid">+++guid::::
The GUID for the Answer, Pinboard, SpotIQ result, Table, Worksheet, or View.
You can find this string of letters and numbers at the end of the URL for an object.+++</dlentry>++++++<dlentry id="headline_aggregation">+++headline_aggregation::::
Specifies the type of headline aggregation.
Can be `COUNT`, `COUNT_DISTINCT`, `SUM`, `MIN`, `MAX`, `AVERAGE`, or `TABLE_AGGR`.+++</dlentry>++++++<dlentry id="id">+++id::::
Specifies the id of an object, such as `table_paths`, `formula`.
+ For Answers, `id` refers to how the column appears in the query.
For example, if you sorted by `Quarter` in your search, from the `Commit Date` column, the `id` of the column is `Quarter(Commit Date)`.
Refer to link:{{ site.baseurl }}/app-integrate/reference/search-data-api.html#components[Components of a Search Query] to understand syntax.
+ For formulas within Answers, `id` refers to the display name of the formula.
If you do not give your formula a name, it appears as 'Untitled Formula'.+++</dlentry>++++++<dlentry id="identity">+++identity::::  Specifies the identity of a table, based on its `name`, `id`, and `fqn`.+++</dlentry>++++++<dlentry id="index_priority">+++index_priority::::
A value (1-10) that determines where to rank a column's name and values in the search suggestions + ThoughtSpot prioritizes columns with higher values.
+ See link:../data-modeling/change-index.html#change-a-columns-suggestion-priority[Change a column's suggestion priority].+++</dlentry>++++++<dlentry id="index_type">+++index_type::::  The indexing option of the Worksheet, View, or table column + Possible values: `DONT_INDEX`, `DEFAULT` (see link:../data-modeling/change-index.html#understand-the-default-indexing-behavior[Understand the default indexing behavior]), `PREFIX_ONLY`, `PREFIX_AND_SUBSTRING`, and `PREFIX_AND_WORD_SUBSTRING` + Default: `DEFAULT` + See link:../data-modeling/change-index.html#index-type[Index Type Values]+++</dlentry>++++++<dlentry id="is_additive">+++is_additive::::  Controls extended aggregate options for attribute columns + For attribute columns that have a numeric data type (`FLOAT`, `DOUBLE`, or `INTEGER`) or a date data type (`DATE`, `DATETIME`, `TIMESTAMP`, or `TIME`) + Possible values: `true` or `false` + Default: `true` + See link:../data-modeling/change-aggreg-additive.html#making-an-attribute-column-additive[Making an ATTRIBUTE column ADDITIVE]+++</dlentry>++++++<dlentry id="is_attribution_dimension">+++is_attribution_dimension::::
Controls if the column is an attribution dimension + Used in managing chasm traps.
+ Possible values: `true` by default, `false` to designate a column as not producing meaningful attributions across a chasm trap + Default: `true` + See link:../data-modeling/attributable-dimension.html[Change the attribution dimension]+++</dlentry>++++++<dlentry id="is_bypass_rls">+++is_bypass_rls::::  Specifies if the worksheet supports bypass of Row-level security (RLS) + Possible values: `true` or `false` + Default: `false` + See link:../data-security/row-level-security.html#privileges-that-allow-users-to-set-or-be-exempt-from-rls[Privileges that allow users to set, or be exempt from, RLS]+++</dlentry>++++++<dlentry id="is_hidden">+++is_hidden::::  The visibility of the column + Possible values: `true` to hide the column, `false` not to hide the column + Default: `false` + See link:../data-modeling/change-visibility-synonym.html#hide-a-column[Hide a column]+++</dlentry>++++++<dlentry id="is_one_to_one">+++is_one_to_one::::  Specifies the cardinality of the join + Possible values: `true`, `false` + Default: `false`+++</dlentry>++++++<dlentry id="is_primary_key">+++is_primary_key::::
Determines if the table column is the primary key.
Can be `true` or `false`.+++</dlentry>++++++<dlentry id="is_foreign_key">+++is_foreign_key::::
Determines if the table column is the foreign key.
Can be `true` or `false`.+++</dlentry>++++++<dlentry id="join">+++join::::  Specific join, used in defining higher-level objects, such as table paths + Defined as `name` within `joins` definition+++</dlentry>++++++<dlentry id="join_path">+++join_path::::
Specification of a composite join as a list of distinct `join` attributes + These `join` attributes list relevant joins, previously defined in the `joins`, by name.
+ Default: `{}`+++</dlentry>++++++<dlentry id="join_progressive">+++join_progressive::::  Specifies when to apply joins on a worksheet + Possible values: `true` when joins are applied only for tables whose columns are included in the search, and `false` for all possible joins + Default: `true` + See link:../worksheets/progressive-joins.html[How the worksheet join rule works]+++</dlentry>++++++<dlentry id="joins">+++joins::::
List of joins between tables and views, used by the Worksheet or View.
+ Each join is identified by `name`, and the additional attributes of `source`, `destination`, `type`, and `is_one_to_one.`+++</dlentry>++++++<dlentry id="layout">+++layout::::  Specifies the Pinboard layout, in the order that a `visualization_id` is listed.+++</dlentry>++++++<dlentry id="locked">+++locked::::
The 'automatically select my chart' option in the UI.
If set to `true`, the chart type does not change, even when you add items to the query.+++</dlentry>++++++<dlentry id="max">+++max::::  Maximum value for conditional formatting.+++</dlentry>++++++<dlentry id="min">+++min::::  Minimum value for conditional formatting.+++</dlentry>++++++<dlentry id="name">+++name::::
The name of an object.
Applies to `worksheet`, `table`,`join`, `formula`, `answer`, `pinboard`, `view`, `table`, `connection` and so on.
+ For Answers, `name` refers to how the column appears in the query.
For example, if you sorted by `Quarter` in your search, from the `Commit Date` column, the `name` of the column is `Quarter(Commit Date)`.
Refer to link:{{ site.baseurl }}/app-integrate/reference/search-data-api.html#components[Components of a Search Query] to understand syntax.+++</dlentry>++++++<dlentry id="on">+++on::::  The keys that your tables are joined on.+++</dlentry>++++++<dlentry id="oper">+++oper::::
The operator of the Pinboard, View or Worksheet filter.
Accepted operators are `"in"`, `"not in"`, `"between"`, `=<`, `!=`, `+<=+`, `>=`, `>`, or `<`.+++</dlentry>++++++<dlentry id="ordered_column_ids">+++ordered_column_ids::::  A list of columns, in the order they appear in the table.+++</dlentry>++++++<dlentry id="phrase">+++phrase::::  Phrase associated with a View column.+++</dlentry>++++++<dlentry id="pinboard">+++pinboard::::  Top-level container for all object definitions within the Pinboard or SpotIQ result.+++</dlentry>++++++<dlentry id="properties">+++properties::::
The list of properties of a Worksheet, Table, or View column, a Worksheet or View itself, or the properties of the output for a formula within an Answer, Worksheet, or View.
+ For Worksheets, Views, and Tables, each column can have the following properties, depending on its definition: `column_type`, `aggregation`, `index_type`, `is_hidden`, `index_priority`, `synonyms`, `is_attribution_dimension`, `is_additive`, `calendar`, `format_pattern`, `currency_type`, `geo_config`, `spotiq_preference`, and `search_iq_preferred`.
+ Worksheets and Views themselves can have the following properties that affect query generation: `is_bypass_rls`, and `join_progressive`.
+ For Answers, each formula's output can have the following properties, depending on its definition: `column_type` and `aggregation`.+++</dlentry>++++++<dlentry id="plotAsBand">+++plotAsBand::::
Specifies whether to plot the chart conditional formatting like a band on the Visualization.
This is the 'fill chart' option in the UI.+++</dlentry>++++++<dlentry id="query">+++query::::  The query that the View is based on.+++</dlentry>++++++<dlentry id="range">+++range::::  Range for the conditional formatting to apply to, with a specified `min` and `max`.+++</dlentry>++++++<dlentry id="rule">+++rule::::  A conditional formatting rule.+++</dlentry>++++++<dlentry id="schema">+++schema::::  The schema that the table is a part of.+++</dlentry>++++++<dlentry id="search_query">+++search_query::::
A string that represents the fully disambiguated search query.
Refer to link:{{ site.baseurl }}/app-integrate/reference/search-data-api.html#components[Components of a Search Query] to understand syntax.+++</dlentry>+++
+
////
<dlentry id="show_data_labels">
    <dt>show_data_labels</dt>
    <dd>Whether or not to show the data labels. <code>true</code> shows the labels.</dd>
  </dlentry> not in v1
////+++<dlentry id="show_headline">+++show_headline::::
Determines whether to show the headline for this column.
`true` shows the headline.+++</dlentry>+++
+
////
<dlentry id="show_grid_summary">
    <dt>show_grid_summary</dt>
    <dd>Whether or not to show the grid summary. <code>true</code> shows the summary.</dd>
  </dlentry> not in v1
////
+
////
<dlentry id="show_table_footer">
    <dt>show_table_footer</dt>
    <dd>Whether or not to show the table footer. <code>true</code> shows the summary.</dd>
  </dlentry> not in v1
////+++<dlentry id="size">+++size::::
The size of a visualization in a Pinboard.
The options are `EXTRA_SMALL`, `SMALL`, `MEDIUM`, `LARGE`, `LARGE_SMALL`, `MEDIUM_SMALL`, and `EXTRA_LARGE`.+++</dlentry>++++++<dlentry id="source">+++source::::  Name of source table or view of the join+++</dlentry>++++++<dlentry id="spotiq_preference">+++spotiq_preference::::
Specifies whether to include a column in SpotIQ analysis.
Specify `EXCLUDE`, or this property defaults to include the column in SpotIQ Analysis.
+ Refer to link:{{ site.baseurl }}/admin/data-modeling/spotiq-data-model-preferences.html[Set columns to exlude from SpotIQ analyses].+++</dlentry>++++++<dlentry id="synonyms">+++synonyms::::  Alternate names for the column, used in search + See link:../data-modeling/change-visibility-synonym.html#create-synonyms-for-a-column[Create synonyms for a column]+++</dlentry>++++++<dlentry id="table">+++table::::
Top-level container for all object definitions within the Table.
+ Specific table, used in defining higher-level objects, such as table paths.
+ Defined as `name` within `tables` definition.
+ For Answers, this parameter contains configuration for the Answer, if it displays in table format.+++</dlentry>++++++<dlentry id="table_columns">+++table_columns::::  The columns in an Answer that is being displayed in table format.+++</dlentry>++++++<dlentry id="table_paths">+++table_paths::::  The list of table paths + Each table path is identified by the `id`, and additional attributes of `table` and `join_path`.+++</dlentry>++++++<dlentry id="tables">+++tables::::
List of tables used by the Worksheet or Answer.
+ Each table is identified by `name`.+++</dlentry>++++++<dlentry id="type">+++type::::
For Worksheets and Views, this is the join type.
+ Possible values: `LEFT_OUTER` for left outer join, `RIGHT_OUTER` for right outer join, `INNER` for inner join, `OUTER` for full outer join + Default: `INNER` + For Tables, this is the Embrace connection type.
+ Possible values: `Snowflake` or `Amazon Redshift`.
+ For Answers, this is the chart type + Possible values: `COLUMN`, `BAR`, `LINE`, `PIE`, `SCATTER`, `BUBBLE`, `STACKED_COLUMN`, `AREA`, `PARETO`, `COLUMN`, `GEO_AREA`, `GEO_BUBBLE`, `GEO_HEATMAP`, `GEO_EARTH_BAR`, `GEO_EARTH_AREA`, `GEO_EARTH_GRAPH`, `GEO_EARTH_BUBBLE`, `GEO_EARTH_HEATMAP`, `WATERFALL`, `TREEMAP`, `HEATMAP`, `STACKED_AREA`, `LINE_COLUMN`, `FUNNEL`, `LINE_STACKED_COLUMN`, `PIVOT_TABLE`, `SANKEY`, `GRID_TABLE`, `SPIDER_WEB`, `WHISKER_SCATTER`, `STACKED_BAR`, or `CANDLESTICK`.+++</dlentry>++++++<dlentry id="values">+++values::::  The values being filtered (excluded or included) in a Pinboard, View, or Worksheet.+++</dlentry>++++++<dlentry id="view">+++view::::  Top-level container for all object definitions within the View.+++</dlentry>++++++<dlentry id="view_columns">+++view_columns::::
The list of columns in the View.
+ Each column is identified by `name`, `description`, `column_id`, `phrase` and `properties`.+++</dlentry>++++++<dlentry id="visualizations">+++visualizations::::  The visualizations in a Pinboard: tables, charts, and headlines.+++</dlentry>++++++<dlentry id="visualization_id">+++visualization_id::::
The id of a visualization.
Used to specify the Pinboard's <<layout,layout>>.+++</dlentry>++++++<dlentry id="worksheet">+++worksheet::::  Top-level container for all object definitions within the worksheet+++</dlentry>++++++<dlentry id="worksheet_columns">+++worksheet_columns::::  The list of columns in the worksheet + Each worksheet is identified by `name`, `description`, `column_id`, and `properties`.+++</dlentry>+++
+
////
<dlentry id="wrap_column_text">
    <dt>wrap_column_text</dt>
    <dd>Determines whether to wrap or clip the column text in an Answer being displayed as  a table. <code>true</code> wraps the text, <code>false</code> clips it.</dd>
  </dlentry> not in v1
////
+
////
<dlentry id="wrap_table_header">
    <dt>wrap_table_header</dt>
    <dd>Determines whether to wrap or clip the table header. <code>true</code> wraps the table header.</dd>
  </dlentry> not in v1
////
////

== Limitations of working with TML files

There are certain limitations to the changes you can apply by editing a Worksheet, Answer, table, View, SpotIQ result, or Pinboard through TML.

* Formulas and columns can either have a new name, or a new expression.
You cannot change both, unless migrating or updating the worksheet two times.
* It is not possible to reverse the join direction in the TML script.
* You cannot create new tables using Scriptability.
You can only update existing tables.
* You can only change logical tables using Scriptability.
You cannot change the physical version of the table that exists in a database.
When you change the `column_name`, for example, the name changes in the application, but not in the physical table in the database.
* You cannot import manually compressed .zip files.
You can only import .zip files that you exported from ThoughtSpot: either an object and its associated data sources, or multiple objects of the same type that you exported from the object list page.
* You cannot create Scriptable representations of R- or Python-powered visualizations.
