= Data protection and business continuity
:last_updated: 2/22/2022
:linkattrs:
:experimental:
:page-layout: default-cloud
:description: Learn how ThoughtSpot protects your data and ensures business continuity. This article describes ThoughtSpot's disaster recovery strategy.

This article describes ThoughtSpot's data protection and business continuity strategy for ThoughtSpot Cloud.

There are several methods ThoughtSpot employs to protect your cluster data and ensure business continuity in the event of a hardware or software failure or a catastrophic event.

== Recovery Point Objective and Recovery Time Objective
A Recovery Point Objective (RPO) is the frequency of which you take a backup of a system. ThoughtSpot's RPO is 24 hours. Every 24 hours, ThoughtSpot automatically takes a backup and stores it in Amazon S3, in the same region as the cluster, but in a different Availability Zone.

A Recovery Time Objective (RTO) is the targeted duration of time between an event of failure and the return to operation. ThoughtSpot's RTO is 2 hours.

== Snapshots and backups
ThoughtSpot has a concept of both <<snapshots,snapshots>> and <<backups,backups>> for data protection and backing up your ThoughtSpot cluster.

[#snapshots]
=== Snapshots
A snapshot is a point-in-time image of your running cluster. Snapshots are taken on a running cluster, and later restored to the same cluster. ThoughtSpot takes snapshots of your cluster once an hour and stores them on EBS disks attached to your VM instance. If an error occurs while making any changes to your cluster’s environment, loading a large amount of new data, or changing the structure of a table, you can restore the cluster to a point in time at most an hour before the error.

[#backups]
=== Backups
A backup is a procedure that stores a snapshot outside a ThoughtSpot cluster. ThoughtSpot takes backups of your cluster once a day, at midnight local cluster time, and stores them in Amazon S3. ThoughtSpot can use a backup to restore a cluster to a prior state.

Backups contain the following information:

* Metadata:
** Users, groups, answers, Liveboards, visualizations, worksheets, data modeling settings, row level security filters, tables, columns
** Configuration of connections to external cloud data warehouses
* Scheduled jobs (for example, scheduled Liveboards)
* Cluster details: ID, name, version
* *[For clusters with S3 storage]:* AWS configuration (label, region, S3 bucket name)
* Cluster manager configuration (e.g., backup policy), and service configuration (e.g., service enabled or disabled, memory limits for service)
* End-user license agreement (EULA) policy and file
* ThoughtSpot Software artifacts: version, checksum of binaries
* Hadoop layout
* Firewall configuration
* `mailname` and `mailfromname`
* SAML configuration
* Consumption pricing user activity

Backups DO NOT include the following information:

* Search index tokens
* Usage information
* Traces

== Automation of data protection
ThoughtSpot's data protection procedure is fully automated. ThoughtSpot automatically takes <<snapshots,snapshots>> of your cluster once an hour and stores them on EBS disks attached to your VM instance. ThoughtSpot automatically takes <<backups,backups>> of your cluster once a day and stores them in Amazon S3.

If a cluster is not available, {support-url} receives an alert. Then, ThoughtSpot Support investigates the cluster, and restores it from a snapshot or backup, if necessary.
