= Confirm data source
:last_updated: 11/05/2021
:linkattrs:
:experimental:
:page-aliases: /admin/ts-cloud/business-user-datasource-confirm.adoc
:description: Choose a data source to use to gain insights through Search.

include::partial$liveboards-announcement.adoc[]

Choose a data source to use to gain insights through Search.

Your organization selected the most relevant data for your exploration.
In ThoughtSpot's link:{{ site.baseurl }}/admin/ts-cloud/business-user-onboarding.html[business user onboarding], you can select the recommended data source.

This data set determines what you can search, which Liveboards you can create or interact with, and what answers and insights you'll find.
For example, a user in the Finance department might see a *payroll* data set, while a user in Sales might see a *pipeline* data set.

Refer to link:{{ site.baseurl }}/end-user/search/start-a-new-search.html[Start a new search] to learn more about choosing a data source and searching your data in ThoughtSpot, or watch this video about how to complete your first search:+++<script src="https://fast.wistia.com/embed/medias/uf5h6du15r.jsonp" async="">++++++</script>++++++<script src="https://fast.wistia.com/assets/external/E-v1.js" async="">++++++</script>+++

[.wistia_embed.wistia_async_uf5h6du15r.popover=true.popoverAnimateThumbnail=true.popoverBorderColor=4E55FD.popoverBorderWidth=2]#&nbsp;#

== Next steps

Next, link:{{ site.baseurl }}/admin/ts-cloud/business-user-pinboard-select.html[select a Liveboard].
