////
:doctype: book

////include::7.1@software:ROOT:connections-snowflake-add.adoc[]
////
= Upload a CSV file in your {connection} connection
:last_updated: 8/11/2020
:linkattrs:
:page-layout: default-cloud
:experimental:
:connection: Snowflake

== Prerequisites

- Before you can upload a CSV file in your {connection} connection, CSV upload must be configured for your Snowflake connection. This must be done by an administrator for your ThoughtSpot cluster.
+
For details, see xref:connections-snowflake-csv-upload-config.adoc[Configure CSV upload for your {connection} connection].


- Users that upload CSV files must have the
*Can Manage Data* privilege and have the appropriate write permissions in the {connection} database

== Uploading a CSV file in your {connection} connection

To upload a CSV file to your {connection} connection:

. Click *Data* in the top navigation bar.
. Click the *Utilities* tab in the left navigation bar
. In the Upload CSV tile, click *Upload CSV*.
. In the Upload Data window, click *Browse Files* and select your CSV file or drag your CSV file into the window.
. For *Column Names* and *Fields Separation*, make any changes necessary.
+
.When multiple Snowflake connections have CSV upload enabled
****
If there are multiple Snowflake connections in your cluster configured to allow CSV upload, *Do you want this table to be colocated with other tables/worksheets?* appears at the bottom of the window.

* If you want to join your imported table with another table/worksheet:

. Select *Yes*
. Click the *select source here* menu, and select the table or worksheet you want to join your imported table to.

TIP: Hovering over a table or worksheet name in the list displays the connection, database, and schema it is stored in.

* If you don't want to join your imported table with another table/worksheet:

. Select *No*

NOTE: You can add table joins after you

----
****
If this is the case, go to the next step. Otherwise, go to step 7.

. If you want to join your imported table with another table/worksheet, select *Yes* for colocating your table and using the *select source here* menu, select the table or worksheet you want to join your imported table to.
+
NOTE: Hovering over a table or worksheet name in the list displays the connection, database, and schema it is stored in.
. Click *Next*.
. In the Review and upload data page, review the data to correct any errors and make any changes necessary before uploading.
. Click *Upload*.
+
The data is written into the selected database and schema. When the upload is complete, a success message appears which confirms the number of rows that were imported.

. At this point, you have the option to either join the data you uploaded with existing data or start searching the data.

* To join the data with existing data, click *Join with existing data*
** This takes you to the table you imported, where you can add joins.
** If you want to load more data into the imported table, click *Load Data*.
+
This takes you to the Upload Data window where you have the option to append data to the table or overwrite the data completely.
* To search the data you uploaded, click *Start search on your data*.
