= ThoughtSpot in {connection} Partner Connect
:last_updated: 11/05/2021
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases: /admin/data-integrate/embrace/embrace-snowflake-partner.adoc
:description: With Snowflake Partner Connect you get a free trial of ThoughtSpot that allows you to try out ThoughtSpot Connections to connect to Snowflake.
:connection: Databricks


include::partial$liveboards-announcement.adoc[]


{connection} Partner Connect allows you to quickly and easily try out ThoughtSpot connected to {connection}, using ThoughtSpot Connections.

ThoughtSpot in {connection} Partner Connect benefits:

* 30-day trial
* Easy to sign up
* Up and running in 5 minutes
* Trial data already loaded into {connection}
* No data modeling required
* Gain first-hand experience of the power of ThoughtSpot search-driven insights

== Prerequisites

* A {connection} account with administrator privileges
+
If you don't have an account, you can sign up for a https://databricks.com/try-databricks?itm_data=NavBar-TryDatabricks-Trial[Databricks free trial^].

== Sign up for the ThoughtSpot free trial in {connection} Partner Connect

To sign up for the free trial, do the following:

. Sign in to your {connection} account.
. Click *Partner Connect*.
. Click *ThoughtSpot*.
The _Connect to partner_ window appears.
. Select an *SQL endpoint*.
+
NOTE: If the selected SQL endpoint is not running, you must click *Start* and wait for it to start up, before you can move to the next step. Endpoints take about 5 minutes to start up.
. Select a *schema* and click *Add*.
. (Optional) select and add more schemas.
. Click *Next*.
+
NOTE: A ThoughtSpot account is created for you and an email titled _Activate Your ThoughtSpot Trial_ is sent to the email address associated with your {connection} account. It is *not necessary*, however, to open this email to activate your account.
+
The next page summarizes the resources that will be created.
. Click *Next*.
+
The next page confirms that the resources have been created.
. Click *Connect to ThoughtSpot*.
+
A message appears briefly, indicating that you are being taken to ThoughtSpot's sign-up page. During this time, Databricks is creating an account for you on a ThoughtSpots free trial cluster.
+
Next, you are redirected to a ThoughtSpot free trial cluster which has an address ending in *.thoughtspot.cloud*, and the Welcome to ThoughtSpot page appears.
. Create and confirm a password for your ThoughtSpot account, and click *Start Now*.
+
Once you sign in, the ThoughtSpot Home screen appears.

== Using your connection with {connection} in the ThoughtSpot free trial

. From the ThoughtSpot Home page, click the *Data* tab.
. On the Data workspace screen, click *Connections*.
+
The Connections page appears, displaying your Databricks connection.
. To go to your connection, click the connection name.
. To select tables and columns for your connection, click *Edit connection*.

== Related information

* xref:connections.adoc[Connections overview]
* xref:connections-databricks-add.adoc[Add a {connection} connection]
* xref:connections-databricks-edit.adoc[Edit a {connection} connection]
* xref:connections-databricks-remap.adoc[Remap a {connection} connection]
* xref:connections-databricks-delete-table.adoc[Delete a table from a {connection} connection]
* xref:connections-databricks-delete-table-dependencies.adoc[Delete a table with dependent objects]
* xref:connections-databricks-delete.adoc[Delete a {connection} connection]
* xref:connections-databricks-oauth.adoc[Configure OAuth for a {connection} connection]
* xref:connections-databricks-private-link.adoc[]
* xref:connections-databricks-reference.adoc[Connection reference for {connection}]