= Enabling an AWS PrivateLink between ThoughtSpot Cloud and your {connection} data warehouse
:experimental:
:last_updated: 6/9/2022
:linkattrs:
:page-layout: default-cloud
:description: Learn how to deploy an AWS PrivateLink between your Teradata data warehouse and the ThoughtSpot Cloud tenant.
:connection: Teradata

Learn how to deploy an AWS PrivateLink between your {connection} data warehouse and the ThoughtSpot Cloud tenant.

Your data's security is important.
To ensure a secure two-way data exchange between your cloud data warehouse and the ThoughtSpot Cloud tenant, you can use an AWS PrivateLink.
This option is currently available for your Databricks, Dremio, Oracle, Redshift, SAP HANA, Snowflake, Starburst, or Teradata data warehouse connections.

This article details how to enable a PrivateLink for *{connection}*;
to enable it for other data warehouses, refer to:

* xref:connections-databricks-private-link.adoc[Databricks PrivateLink]
* xref:connections-dremio-private-link.adoc[Dremio PrivateLink]
* xref:connections-adw-private-link.adoc[Oracle PrivateLink]
* xref:connections-redshift-private-link.adoc[Redshift PrivateLink]
* xref:connections-hana-private-link.adoc[SAP HANA PrivateLink]
* xref:connections-snowflake-private-link.adoc[Snowflake PrivateLink]
* xref:connections-starburst-private-link.adoc[Starburst PrivateLink]

NOTE: You can only enable one PrivateLink for each cluster.

To deploy an AWS PrivateLink, you must work with https://community.thoughtspot.com/customers/s/contactsupport[ThoughtSpot Support] and follow the procedure in this article.

[#prerequisites]
== Prerequisites

* The {connection} data warehouse is running inside your AWS account.
* The ThoughtSpot cluster must be in the same AWS region as your {connection} account.
* You must obtain the ThoughtSpot AWS Account Amazon Resource Name (ARN) from https://community.thoughtspot.com/customers/s/contactsupport[ThoughtSpot Support].
You may need a separate ARN for staging or dev environments. This is required for step 7 of <<configure-aws,Configure the Endpoint Service>>. For example: `arn:aws:iam::999999999999:root`

== Enable an AWS PrivateLink for {connection}

To deploy an AWS PrivateLink between your {connection} data warehouse and the ThoughtSpot Cloud tenant, follow these steps.

. <<configure-aws,Configure the VPC Endpoint Service in your AWS Console>>
. <<exchange-information,Exchange AWS and ThoughtSpot information with ThoughtSpot Support>>
. <<accept-request,Accept the PrivateLink Request>>
. <<embrace,Configure Connections>>

[#configure-aws]
=== Configure the Endpoint Service in your AWS Console

After completing the <<prerequisites,prerequisites>>, you must configure the Endpoint Service.

. Log into the AWS Console.
. Create a Network Load Balancer (NLB) routing TCP traffic to your {connection} database.
. Note the number of the port you used to route the TCP traffic. You must provide {support-url} with this information later.
. Navigate to menu:AWS VPC Console[Endpoint Services > Create Endpoint Service].
. Select the NLB you created in step 2.
. *_Optionally_*, you can select *Require Acceptance for Endpoint*.
. Select menu:Endpoint Service[Whitelist principles > Add principles to whitelist].
Add the ThoughtSpot AWS Account Amazon Resource Name (ARN) that you obtained from ThoughtSpot Support in the <<prerequisites,prerequisites>>.
You may need a separate ARN for staging or dev environments.
. Select *Endpoint Service*.
. Write down the values for:

* *Service name*: for example, _com.amazonaws.vpce.us-west-2.vpce-svc-0123456789abcdef_
* *Port number*: for example, _5439_
* *Availability zones and availability zone IDs*: for example, _us-west-2a (usw2-az1)_
+
You must provide the service name, port number, availability zones, and availability zone IDs to ThoughtSpot Support.

[#exchange-information]
=== Exchange AWS and ThoughtSpot information with ThoughtSpot Support

. Send the *Service name*, *Port number*, *Availability zones*, and *Availability zone IDs* you gathered in step 9 of <<configure-aws,Configure the Endpoint Service in your AWS Console>> to ThoughtSpot Support.
. After ThoughtSpot Support configures the AWS PrivateLink in ThoughtSpot, ask them to send you the PrivateLink Endpoint DNS name.

[#accept-request]
=== Accept the PrivateLink Request

. Navigate to menu:VPC[Endpoint Services].
. Select the Endpoint Service you created in <<configure-aws,Configure the Endpoint Service in your AWS Console>>.
. Select *Endpoint Connections*.
. Select the connection from the ThoughtSpot AWS Account.
Its status should be _Pending Acceptance_.
. Select menu:Actions[Accept endpoint connection request].

[#embrace]
=== Configure Connections

xref:connections-teradata.adoc[Configure Connections for {connection}], using the PrivateLink Endpoint DNS name from ThoughtSpot Support for the *Host* field. For example, `vpce-12345a9c7e43959d-xxo2u2xx.vpce-svc-037b1f73d3de3a5b4.us-west-2.vpce.amazonaws.com`.
