= Query-based usage
:last_updated: 11/05/2021
:linkattrs:
:experimental:
:page-aliases:
:page-layout: default-cloud
:description:


[.lead]
Query-based usage is measured by the number of queries generated, based on a user’s activity. In most cases, one credit is consumed for every query that is generated.

== What is a credit?

A credit is a unit of measure you use to pay for using ThoughtSpot to get insights from your data. Insights are created by executing queries to request information from a connected data warehouse.

=== Types of credits

- *Base credits*: credits included in the base subscription of each edition.
- *Flexible credits*: any additional credits that you would like to purchase to add to your subscription.

[#usage-minutes]
== Query-based pricing

To purchase query-based credits, a customer purchases a number of base-credit packages.  Each base-credit package is valid for one year and sets a subscription term of one year.  If multiple base-credit packages are purchased in an order form, the Subscription Term will be extended for that number of years.

For example, one base-credit package establishes a subscription term applicable to that order form of one year.  Alternatively, three base-credit packages establishes a subscription term applicable to that order form of three years.

== What is a query?

When a user requires information from an external data warehouse, system cache (data fetched previously or a result of recent calculation, and stored in the system), or descriptive/statistical metadata, the system triggers an event, called a query. Some functions, like a scheduled Liveboard, monitor, or SpotIQ, also trigger queries.

Various kinds of user actions or system functions generate one or more queries.

Examples of queries:

- A chart view from a search typically generates one query.
- Pivot tables and stacked charts generate multiple queries.
- An answer view that contains a table and two headlines triggers three (3) queries.
- A Liveboard view may generate multiple queries when loading multiple visualizations.

For information on user actions that generate queries, see xref:consumption-pricing-query-based-generate.adoc[user actions and queries].

== Subscription term definition

The subscription term is the number of years for which base credit packages were purchased.

Example: For a one-year subscription, you would buy one base-credit package. For a three-year subscription, you would buy three base-credit packages.

Flexible credits can be used at any time during the subscription term after the base credits for the year they were purchased for are consumed.

A purchase of the base credits package provides you with an annual subscription.
If you use all the credits, you can purchase flexible credits.

== Rollover of credits

=== Base credits

Unused base credits expire each year and do not roll over.

=== Flexible credits

Unused flexible credits roll over each year within the contract term.

Flexible credits are valid to use throughout the subscription term for which they were purchased. In addition, a portion of flexible credits can be rolled over to a renewal subscription term as described in the table below.

====     Rollover of flexible credits
[cols="20%,20%,20%,40%",frame=ends,grid=rows]
|===
|Original contract term |Rollover within contract term |Renewal contract term |Rollover at time of renewal

|1 year
|N/A
|1 year or multi-year
|Up to 30% of prior contract’s flexible credits as long as renewal amount >= original contract.

|Multi-year
|100%
|Multi-year
|Up to 15% of prior contract’s flexible credits as long as renewal amount >= original contract.
|===

NOTE: Rollover credits expire 12 months after the time of renewal.


