= Query-based subscription and rollover policies
:last_updated: 11/05/2021
:linkattrs:
:experimental:
:page-aliases:
:page-layout: default-cloud
:description:

The following information defines a subscription term and how query-based consumption credits can be rolled over.

== Subscription term

The subscription term is the number of years for which base credit packages were purchased.

Example: For a one-year subscription, you would buy one base-credit package. For a three-year subscription, you would buy three base-credit packages.

Flexible credits can be used at any time during the subscription term after the base credits for the year they were purchased for are consumed.

A purchase of the base credits package provides you with an annual subscription.
If you use all the credits, you can purchase flexible credits.

For example, one base-credit package establishes a subscription term applicable to that order form of one year.  Alternatively, three base-credit packages establish a subscription term applicable to that order form of three years.

== Rollover of credits

=== Base credits

Unused base credits expire each year and do not roll over.

=== Flexible credits

Unused flexible credits roll over each year within the contract term.

Flexible credits are valid to use throughout the subscription term for which they were purchased. In addition, a portion of flexible credits can be rolled over to a renewal subscription term as described in the table below.

==== Rollover of flexible credits
[cols="20%,20%,20%,40%",frame=ends,grid=rows]
|===
|Original contract term |Rollover within contract term |Renewal contract term |Rollover at time of renewal

|1 year
|N/A
|1 year or multi-year
|Up to 30% of prior contract’s flexible credits as long as renewal amount >= original contract.

|Multi-year
|100%
|Multi-year
|Up to 15% of prior contract’s flexible credits as long as renewal amount >= original contract.
|===

NOTE: Rollover credits expire 12 months after the time of renewal.


