= Early Access features
:last_updated: 12/16/2022
:author: Mark Plummer
:linkattrs:
:experimental:
:page-layout: default-cloud
:description: This page describes how administrators can enable or disable Early Access features.

== Early Access features

Early Access features have new or enhanced functionality that only an administrator can selectively enable. They are disabled by default.

== Enabling Early Access features

To enable an early access feature, do the following:

. Go to the *Admin* tab and select *Early access features*.
. Find the feature you want to enable, and click *Edit*.
.

== Disabling Early Access features

Deprecated features still exist in the product, for backward compatibility, but we plan to remove them in a later release. Deprecated features do not receive ongoing support from ThoughtSpot. For details, see xref:deprecation.adoc[Deprecation and de-support announcements].

== De-supported

De-supported features no longer exist in the product. When you upgrade to a newer release, any workflows that rely on a de-supported feature no longer work. For details, see xref:deprecation.adoc[Deprecation and de-support announcements].

