= Formula function reference
:last_updated: 11/19/2019
:linkattrs:
:experimental:
:page-aliases: /reference/formula-reference.adoc
:description: Learn the operators and functions you can use to create formulas in ThoughtSpot.

ThoughtSpot allows you to create derived columns in worksheets using formulas.
You create these columns by building formulas using the *Formula Assistant*.
An individual formula is constructed from _n_ combination of operators and functions.

This reference lists the various operators and functions you can use to create formulas.

[#operators]
== Operators

include::partial$operators.adoc[]

[#aggregate-functions]
== Aggregate functions (group aggregate)

Use the following functions to aggregate data.

{% include content/aggregate.md %}

[#conversion-functions]
== Conversion functions

Use these functions to convert data from one data type into another data type.

ThoughtSpot does not support _date_ data type conversion.

{% include content/conversion-func.md %}

[#date-functions]
== Date functions

{% include content/date-func.md %}

[#mixed-functions]
== Mixed functions

These functions can be used with text and numeric data types.

include::partial$mixed-func.adoc[]

[#number-functions]
== Number functions

include::partial$number-func.adoc[]

[#text-functions]
== Text functions

{% include content/text-func.md %}

[#passthrough-functions]
== Connections passthrough functions

NOTE: The following passthrough functions are only supported with Snowflake connections at this time.

include::partial$passthrough-func.adoc[]
