= 中文(简体) Keyword reference
:last_updated: 11/19/2019
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases: /reference/keywords-zh-CN.adoc
:description: Use keywords to help define a search.

NOTE: This content is still under review, and might have incremental changes until this message is removed.

You can use keywords when asking a question to help define your search.
This reference lists the various keywords.

|===
| _xref:keywords.adoc[< Back to English Keywords page]_
|===

== General

{% include content/keywords-translate/zh-CN/keywords-general-zh-CN.md %}

== Date

{% include content/keywords-translate/zh-CN/keywords-date-zh-CN.md %}

== Time

{% include content/keywords-translate/zh-CN/keywords-time-zh-CN.md %}

== Text

{% include content/keywords-translate/zh-CN/keywords-text-zh-CN.md %}

== Number

{% include content/keywords-translate/zh-CN/keywords-number-zh-CN.md %}

== Comparative

{% include content/keywords-translate/zh-CN/keywords-comparative-zh-CN.md %}

////
## Location

{% include content/keywords-translate/zh-CN/keywords-location-zh-CN.adoc %}
////

== Period

{% include content/keywords-translate/zh-CN/keywords-period-zh-CN.md %}
