= Suomi Keyword reference
:last_updated: 11/19/2019
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases: /reference/keywords-fi-FI.adoc
:description: Use keywords to help define a search.

NOTE: This content is still under review, and might have incremental changes until this message is removed.

You can use keywords when asking a question to help define your search.
This reference lists the various keywords.

|===
| _xref:keywords.adoc[< Back to English Keywords page]_
|===

== General

{% include content/keywords-translate/fi-FI/keywords-general-fi-FI.md %}

== Date

{% include content/keywords-translate/fi-FI/keywords-date-fi-FI.md %}

== Time

{% include content/keywords-translate/fi-FI/keywords-time-fi-FI.md %}

== Text

{% include content/keywords-translate/fi-FI/keywords-text-fi-FI.md %}

== Number

{% include content/keywords-translate/fi-FI/keywords-number-fi-FI.md %}

== Comparative

{% include content/keywords-translate/fi-FI/keywords-comparative-fi-FI.md %}

////
## Location

{% include content/keywords-translate/fi-FI/keywords-location-fi-FI.md %}
////

== Period

{% include content/keywords-translate/fi-FI/keywords-period-fi-FI.md %}

////
## Help

{% include content/keywords-translate/fi-FI/keywords-help-fi-FI.md %}
////
