= Dansk Keyword reference
:last_updated: 11/19/2019
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases: /reference/keywords-da-DK.adoc
:description: Use keywords to help define a search.

NOTE: This content is still under review, and might have incremental changes until this message is removed.

You can use keywords when asking a question to help define your search.
This reference lists the various keywords.

|===
| _xref:keywords.adoc[< Back to English Keywords page]_
|===

== General

{% include content/keywords-translate/da-DK/keywords-general-da-DK.md %}

== Date

{% include content/keywords-translate/da-DK/keywords-date-da-DK.md %}

== Time

{% include content/keywords-translate/da-DK/keywords-time-da-DK.md %}

== Text

{% include content/keywords-translate/da-DK/keywords-text-da-DK.md %}

== Number

{% include content/keywords-translate/da-DK/keywords-number-da-DK.md %}

== Comparative

{% include content/keywords-translate/da-DK/keywords-comparative-da-DK.md %}

////
## Location

{% include content/keywords-translate/da-DK/keywords-location-da-DK.md %}
////

== Period

{% include content/keywords-translate/da-DK/keywords-period-da-DK.md %}

////
## Help

{% include content/keywords-translate/da-DK/keywords-help-da-DK.md %}
////
