= Español (Latinoamérica) Keyword reference
:last_updated: 11/19/2019
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases: /reference/keywords-es-US.adoc
:description: Use keywords to help define a search.

NOTE: This content is still under review, and might have incremental changes until this message is removed.

You can use keywords when asking a question to help define your search.
This reference lists the various keywords.

|===
| _xref:keywords.adoc[< Back to English Keywords page]_
|===

== General

{% include content/keywords-translate/es-US/keywords-general-es-US.md %}

== Date

{% include content/keywords-translate/es-US/keywords-date-es-US.md %}

== Time

{% include content/keywords-translate/es-US/keywords-time-es-US.md %}

== Text

{% include content/keywords-translate/es-US/keywords-text-es-US.md %}

== Number

{% include content/keywords-translate/es-US/keywords-number-es-US.md %}

== Comparative

{% include content/keywords-translate/es-US/keywords-comparative-es-US.md %}

////
## Location

{% include content/keywords-translate/es-US/keywords-location-es-US.md %}
////

== Period

{% include content/keywords-translate/es-US/keywords-period-es-US.md %}
