= 日本語 Keyword reference
:last_updated: 04/09/2021
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases: /reference/keywords-ja-JP.adoc
:description: Use keywords to help define a search.

NOTE: This content is still under review, and might have incremental changes until this message is removed.

You can use keywords when asking a question to help define your search.
This reference lists the various keywords.

|===
| _xref:keywords.adoc[< Back to English Keywords page]_
|===

== General

{% include content/keywords-translate/JA/keywords-general-ja-JP.md %}

== Date

{% include content/keywords-translate/JA/keywords-date-ja-JP.md %}

== Time

{% include content/keywords-translate/JA/keywords-time-ja-JP.md %}

== Text

{% include content/keywords-translate/JA/keywords-text-ja-JP.md %}

== Number

{% include content/keywords-translate/JA/keywords-number-ja-JP.md %}

== Comparative

{% include content/keywords-translate/JA/keywords-comparative-ja-JP.md %}

////
## Location

{% include content/keywords-translate/JA/keywords-location-ja-JP.md %}
////

== Period

{% include content/keywords-translate/JA/keywords-period-ja-JP.md %}

////
## Help

{% include content/keywords-translate/JA/keywords-help-ja-JP.md %}
////
