= Français (France) Keyword reference
:last_updated: 11/19/2019
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases: /reference/keywords-fr-FR.adoc
:description: Use keywords to help define a search.

NOTE: This content is still under review, and might have incremental changes until this message is removed.

You can use keywords when asking a question to help define your search.
This reference lists the various keywords.

|===
| _xref:keywords.adoc[< Back to English Keywords page]_
|===

== General

{% include content/keywords-translate/fr-FR/keywords-general-fr-FR.md %}

== Date

{% include content/keywords-translate/fr-FR/keywords-date-fr-FR.md %}

== Time

{% include content/keywords-translate/fr-FR/keywords-time-fr-FR.md %}

== Text

{% include content/keywords-translate/fr-FR/keywords-text-fr-FR.md %}

== Number

{% include content/keywords-translate/fr-FR/keywords-number-fr-FR.md %}

== Comparative

{% include content/keywords-translate/fr-FR/keywords-comparative-fr-FR.md %}

////
## Location

{% include content/keywords-translate/fr-FR/keywords-location-fr-FR.md %}
////

== Period

{% include content/keywords-translate/fr-FR/keywords-period-fr-FR.md %}
