= Norsk Keyword reference
:last_updated: 11/19/2019
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases: /reference/keywords-nb-NO.adoc
:description: Use keywords to help define a search.

NOTE: This content is still under review, and might have incremental changes until this message is removed.

You can use keywords when asking a question to help define your search.
This reference lists the various keywords.

|===
| _xref:keywords.adoc[< Back to English Keywords page]_
|===

== General

{% include content/keywords-translate/nb-NO/keywords-general-nb-NO.md %}

== Date

{% include content/keywords-translate/nb-NO/keywords-date-nb-NO.md %}

== Time

{% include content/keywords-translate/nb-NO/keywords-time-nb-NO.md %}

== Text

{% include content/keywords-translate/nb-NO/keywords-text-nb-NO.md %}

== Number

{% include content/keywords-translate/nb-NO/keywords-number-nb-NO.md %}

== Comparative

{% include content/keywords-translate/nb-NO/keywords-comparative-nb-NO.md %}

////
## Location

{% include content/keywords-translate/nb-NO/keywords-location-nb-NO.md %}
////

== Period

{% include content/keywords-translate/nb-NO/keywords-period-nb-NO.md %}

////
## Help

{% include content/keywords-translate/nb-NO/keywords-help-nb-NO.md %}
////
