= Known issues
:keywords: known issues
:last_updated: 11/8/2022
:experimental:
:page-layout: default-cloud
:linkattrs:

These are the known issues in this release of ThoughtSpot Cloud.

[#releases-8-10-x]
== 8.10.0.cl known issues

[cols="17%,39%,38%"]
|===
|Issue ID |Description|Symptoms, conditions, and workaround

|SCAL-136420
|KPI charts revert to table view.
a|*Symptoms*:

KPI chart on a Liveboard displays instead as a table.

*Conditions*:

KPI chart on a Liveboard.

*Workaround*:

To add the KPI chart back onto the Liveboard, edit the chart, and then save it.

|SCAL-135811
|User Sync API takes too long and then times out after upgrade to 8.7.0.cl 111 release.
a|*Symptoms*:

The User Sync API runs forever and eventually times out.

*Conditions*:

After upgrade to the 8.7.0.cl release.

*Workaround*:

Roll back to 8.7.0.cl

|SCAL-134911
|Cannot save a custom SQL view.
a|*Symptoms*:

Error message when trying to save changes to a custom SQL view.

*Conditions*:

Added some valid lines of code to a custom SQL view and tried to save it.

*Workaround*:

None

|SCAL-134123
|When clicking Explore in a visualization that contains no data in an embedded Liveboard V1, the display gets stuck while trying to load.
a|*Symptoms*:

Card pops up but never stops loading.

*Conditions*:

User clicks *Explore* in the visualization of an embedded Liveboard V1.

*Workaround*:

None

|===
