= Release life cycle
:last_updated: 12/16/2022
:author: Mark Plummer
:linkattrs:
:experimental:
:page-layout: default-cloud
:description: The regular life cycle of ThoughtSpot Cloud releases.

ThoughtSpot features go through a regular life cycle:

== Beta

Features in Beta are managed and supported by the Product Team and have been internally validated for a set of use cases. Minimal documentation is provided to customers and is subject to change as the features reach general availability (GA).

Beta features are marked with a beta icon: [.badge.badge-update-note]#Beta#

IMPORTANT: Beta features are disabled by default. You must contact ThoughtSpot Support to enable them.

== Early Access

A feature in an Early Access (EA) stage is new or enhanced functionality made available for you to selectively opt-in to and use in both Production and non-Production environments.

Early Access features are marked with a Early Access icon: [.badge.badge-early-access]#Early Access#

IMPORTANT: Early features are disabled by default. You must contact your ThoughtSpot administrator to enable them.

== General Availability (GA)

A feature in General Availability (GA) is new or enhanced functionality that is enabled by default for all customers. Beginning in February 2017, features move from EA (enabled by request) to GA (enabled for all orgs) in a regular cadence: