= Release life cycle
:last_updated: 12/16/2022
:author: Mark Plummer
:linkattrs:
:experimental:
:page-layout: default-cloud
:description: The life cycle of ThoughtSpot Cloud releases.

ThoughtSpot features go through stages of a life cycle:

== Beta

Beta features are incomplete and subject to change before they reach General Availability (GA). They are supported by ThoughtSpot and minimal documentation is available, which is also subject to change before General Availability (GA).

Beta features are marked with a beta icon: [.badge.badge-update-note]#Beta#

IMPORTANT: Beta features are disabled by default. You must contact {support-url} to enable them.

== Early Access

Early Access (EA) features have new or enhanced functionality you can selectively enable and use.

Early Access features are marked with an Early Access icon: [.badge.badge-early-access]#Early Access#

IMPORTANT: Early Access features are disabled by default. You must contact your *ThoughtSpot administrator* to enable them.

== General Availability (GA)

General Availability (GA) features have new or enhanced functionality that is enabled by default for all customers.

== Deprecated

Deprecated features still exist in the product, for backward compatibility, but we plan to remove them in a later release. Deprecated features do not receive ongoing support from ThoughtSpot. For details, see xref:deprecation.adoc[Deprecation and de-support announcements].

== De-supported

De-supported features no longer exist in the product. When you upgrade to a newer release, any workflows that rely on a de-supported feature no longer work. For details, see xref:deprecation.adoc[Deprecation and de-support announcements].

