= Date filters for Answers
:last_updated: 5/17/2023
:linkattrs:
:experimental:
:page-layout: default-cloud
:author: Naomi
:description: ThoughtSpot now supports rolling time windows, as well as fixed and custom date ranges for Search.

Beginning in 9.3.0.cl, we have increased the possible range of dates you can use to filter your Answers. Previously, when adding a date using the filter from the side bar, users were limited to the following conditions: On (=) <date>, On or after (>=) <date>, Before (<) <date>, and Between <date> and <date>. Now, we support rolling time windows, as well as fixed and custom date ranges.

For a complete list of the date options ThoughtSpot supports for Answers, see the following options:

. Specific calendar dates or date ranges.

* Is on / Is not on
* Is before / Is after
* Is on or before / Is on or after
* Is between / Is not between
* In the month and year e.g. Jan 2020
* In the quarter and year e.g. Q1 2020
* In the year e.g. 2020

. Rolling time windows. Note that in this context, s/m/h/D/W/M/Q/Y means seconds/minutes/hours/days/weeks/months/quarters/years.

* This/Last/Next s/m/h/D/W/M/Q/Y e.g. “this week”, “this quarter”, “last quarter”, “next quarter”. In addition, this includes explicit shortcuts for Today, Tomorrow and Yesterday even though this/last/next day mean the same thing i.e. “this day” = “Today”
* In/not in W/M/Q/Y to date e.g. week to date
* Last/Next X s/m/h/D/W/M/Q/Y e.g. “Last 30 days”, “Next 2 Quarters”
* Before (<) / after (>) / on or before (<=) / on or after (>=) This/Last/Next s/m/h/D/W/M/Q/Y/today/tomorrow/yesterday e.g. <this month, before last month, after next month, etc.
* Before (<) / after (>) / on or before (<=) / on or after (>=)Last/Next X s/m/h/D/W/M/Q/Y e.g. before last 30 days

. All other time windows.

* Multiple conditions e.g. if a user enters “last 30 days next 1 week” or “date != 1 Jan date > 30 Dec”. This would include conditions like “Last/Next X m/h/D/W/M/Q/Y To Last/Next X s/m/h/D/W/M/Q/Y”.
* Is empty / Is not empty (i.e. = null / not null)
* Last X m/h/D/W/M/Q/Y for each Day/Week/Month/Quarter/Year e.g. last 2 days for each month
* Is one of / is not any of <multiple dates>
* X m/h/D/W/M/Q/Y ago e.g. 30 weeks ago
Choose a day of week (Saturdays, Sundays etc.), or a day of month (1st, 2nd, etc.) or a month of year (January, February, etc.) or quarter of year (Q1, Q2, etc.). Complete list:
** day of week
** day of month
** day of quarter
** day of year
** week of month
** week of quarter
** week of year
** month of quarter
** month of year
** quarter of year
* Specify minutes and hours e.g. events between 1 Jun 2021 4:00pm and 1 Jun 2021 5:00pm
