= ThoughtSpot Sage
:last_updated: 4/25/23
:linkattrs:
:experimental:
:page-layout: default-cloud
:description: ThoughtSpot Sage provide AI-powered search in ThoughtSpot.

ThoughtSpot Sage is our new natural language search which leverages the large language model (LLM) of Microsoft Azure OpenAI Service. Currently, Sage uses a combination of GPT-3.5T and GPT-4. Natural language search significantly reduces the skill and level of effort required for you to create insights in ThoughtSpot.

When searching in a Worksheet, ThoughtSpot Sage translates your natural language query to a relational search to provide you an accurate, AI-generated answer from your complex data.

Natural Language query and Token-based authentication

<Insert image here>

In the AI-generated answer, you can view the ThoughtSpot search phrases (also known as tokens) that matched your natural language query to verify the measures, attributes and filters used to create the answer. If you notice an error, you can quickly modify the query by adding or removing search phrases, and then send us the feedback so we can improve the results in a future ThoughtSpot release.

== How ThoughtSpot Sage works

The following diagram provides a high-level overview of how ThoughtSpot Sage takes a natural language question you ask and gives you an AI-generated answer.

image::sage-gpt-flow.svg[]

=== Steps of a ThoughtSpot Sage query

After you enter your natural language query, ThoughtSpot Sage does the following:

==== Pre-processing

Sage uses all available information about your data source to create a prompt for generating a SQL query using GPT.
ThoughtSpot Sage:

- Identifies the columns and values to be shared with GPT
- Identifies the examples to be shared with GPT
- Provides instructions for generating the SQL query
* Shares custom functions with GPT for converting the generated SQL to the syntax required for ThoughtSpot’s Search data functionality.

==== GPT

GPT uses the information collected during pre-processing to generate a SQL query to answer your question. ThoughtSpot Sage uses GPT to:

- Understand your intent by looking at a Few-Shot examples, column names and values.
- Generate a SQL query to answer your question using custom functions

==== Post-processing

In this stage, ThoughtSpot Sage converts the SQL query generated by GPT into a query which contains search tokens for ThoughtSpot’s Search data functionality.

== Enabling ThoughtSpot Sage

ThoughtSpot Sage features are available as Private Preview starting in the 9.2.0.cl release. They are disabled by default, and require approval from ThoughtSpot before they can be enabled. If you want to enable ThoughtSpot Sage, contact ThoughtSpot support.

Once it is enabled, your ThoughtSpot administrator can do the following:

- Limit access by enabling ThoughtSpot Sage for specific worksheets and specific users
- Disable indexing of personally identifiable information (PII) and sensitive data columns so the data isn’t used by the GPT features at all.
// - Disable sending any information to GPT if you are concerned about security risks

== ThoughtSpot Sage security

Features of ThoughtSpot Sage security:

- https://learn.microsoft.com/en-us/legal/cognitive-services/openai/data-privacy?context=%2Fazure%2Fcognitive-services%2Fopenai%2Fcontext%2Fcontext[Azure OpenAI Service^] complies with SOC2 for data security and privacy, and has passed the ThoughtSpot Vendor Security Risk Assessment (https://learn.microsoft.com/en-us/compliance/regulatory/offering-home?view=o365-worldwide[Azure cloud compliances)^].
- ThoughtSpot sends the natural language search query along with additional metadata such as worksheet column names, descriptions and sample values as part of the GPT prompt in order to provide accurate, in-context responses.
- GPT does not store the data or metadata that ThoughtSpot sends. We have turned off persistence of the prompt. Though Microsoft allows you to persist data for 30 days to do troubleshooting, we have explicitly disabled this.
- ThoughtSpot Sage does not use ChatGPT. We use a combination of GPT 3.5T and GPT-4, also created by Open AI, because it is better suited for natural language translation to SQL.
.

== ThoughtSpot Sage accuracy

Accuracy varies based on the complexity of the question and the data source you select, and will improve with future releases. For simple worksheets with clearly formatted names and less than 200 columns, we measured an average of over 80% accuracy.

For more complex worksheets with thousands of columns, joins and overlapping column names, accuracy is around 40%. As a result, you should always review the answer completely before relying on the result. Because of this, we’ve provided you with the ability to control which worksheets generate AI answers, and which users can have access to the feature.




