= {spotapp}
:last_updated: 6/13/2022
:experimental:
:linkattrs:
:page-layout: default-cloud
:description: Deploy the {spotapp}, an out-of-the-box solution template built specifically for {application}.
:spotapp: HubSpot Email Marketing SpotApp
:application: HubSpot

include::partial$spotapps-intro.adoc[]

Use the {spotapp} to identify the success of your email campaigns. Determine which emails are working, and use that information to make data-driven decisions about where to focus your marketing budget.

[#prerequisites]
== Prerequisites
Before you can deploy the {spotapp}, you must complete the following prerequisites:

include::partial$spotapp-prereqs-general.adoc[]

* Super Admin access to {application}
* Access to the following {application} tables in your cloud data warehouse. Refer to <<schema,{spotapp} schema>> for more details.
TABLES
* Run the required SQL commands in your cloud data warehouse. Refer to <<sql,Run SQL commands>>.

[#sql]
=== Run SQL commands
The following SQL commands help standardize data types and column names. Replace the database name and schema name with your specific information.

NOTE: The following SQL example is for the Snowflake cloud data warehouse. You may need to modify the code for the SQL requirements of your specific cloud data warehouse.

SQL commands:
[%collapsible]
====
include::partial$hubspot-sql-script.adoc[]
====

include::partial$spotapp-deploy-individual.adoc[]

[#schema]
== {spotapp} schema

The following table describes the schema for the {spotapp}.

|===
| Table/View |Column | Column type | Join column | Required | Frequency

TABLE INFO