= Activate your ThoughtSpot account
:last_updated: 6/24/2022
:linkattrs:
:experimental:
:page-layout: default-cloud
:description: Learn how to activate your ThoughtSpot account.

Before you can begin using ThoughtSpot, you must activate your ThoughtSpot account. When your ThoughtSpot administrator creates your user account, ThoughtSpot sends you an activation email.


Your password must meet the following requirements:

* The password must be 8 characters or more in length.
* The password must include at least 1 uppercase letter, 1 lowercase letter, 1 number, and 1 special character.
* The password must pass a complexity test based on an external library. This test ensures password complexity and uniqueness by checking for known patterns or words that are too simple. If the password is not complex enough, ThoughtSpot rejects it, even if it fulfills the other requirements. Refer to the https://github.com/dropbox/zxcvbn[Dropbox password library^] for more information.
* The password cannot use certain blocked words. By default, the blocked words are: your username, any part of your display name, and any blocked words your company configures. To add additional words to the blocklist, contact {support-url}.
