== Prerequisites 

Before attempting the following practice examples, follow these steps to upload the sample dataset:

[%collapsible]
1. Click link:{attachmentsdir}/Meetings_tiny.csv[here] to download the sample data set.

2. Sign in to your ThoughtSpot account, and click the *Data* tab.

3. Click the *more* menu icon in the top-right of the screen. From the menu, select *Upload data*.

4. Upload the data file, either by dragging and dropping it into the field provided, or by clicking *Browse your files* and selecting *Meetings_tiny.csv*.

.. Select *Yes* to answer *Are the column names already defined in the file header?*

.. Select *Comma (,)* to answer *Are the fields separated by?*.

5. Select *Next* at the bottom right of the screen to proceed.

6. Select *Next* to proceed without changing the column names. For the sake of the formulas used in the examples, column names should not be changed.

7. Review the column types in Step 3 and select *Upload* to finish.

8. Click the *search* icon on the final screen of the upload process to begin a search based on the sample data set.
