ifndef::pendo-links[]
January 2023 [label label-dep]#9.0.0.sw#
endif::[]
ifdef::pendo-links[]
[month-year-whats-new]#January 2023#
[label label-dep-whats-new]#9.0.0.sw#
endif::[]

ifndef::pendo-links[]
NOTE: Features marked as [.badge.badge-update-whats-new-beta-note]#Beta# are off by default. To enable them, contact {support-url}.
endif::[]

ifdef::pendo-links[]
NOTE: Features marked as [.badge.badge-update-whats-new-beta-note]#Beta# are off by default. To enable them, contact {support-url}.
endif::[]

[#primary-9-0-0-sw]



'''
[#secondary-9-0-0-sw]
[discrete]
=== _Other features and enhancements_

[#9-0-0-cl-joins-rls]
[discrete]
=== Delete joins and RLS rules through TML

When you edit and import TML files, ThoughtSpot now supports deletion of joins and RLS rules.  For more information, see
ifndef::pendo-links[]
xref:tml.adoc[ThoughtSpot Modeling Language].
endif::[]
ifdef::pendo-links[]
see xref:tml.adoc[ThoughtSpot Modeling Language],window=_blank].
endif::[]

[discrete]
=== ThoughtSpot Everywhere

Customers licensed to embed ThoughtSpot can use ThoughtSpot Everywhere features and the Visual Embed SDK.

To enable ThoughtSpot Everywhere on your cluster, contact {support-url}.

For new features and enhancements introduced in this release for ThoughtSpot Everywhere, see https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].
