= Pre-configure User Home and Favorite Pinboards Tool
:last_updated: ["3/10/2021"]
:linkattrs:

The Home and Favorite Pinboards Tool is a Python script that allows you to use the ThoughtSpot Web APIs to do the following:

- Set a Pinboard as the Home Pinboard for all users of the Mobile App.
- Add Pinboard(s) to favorites for all users of ThoughtSpot.
- Remove Pinboard(s) from favorites for all users of ThoughtSpot.

== Prerequisites

- Python version XXX #WHICH VERSION?#
- Mac OS X (TBD), Linux, or Windows (TBD) #WHICH VERSION?#

NOTE: Web APIs are not public.

== Installing the script

To install the script:

. Download the source zip file and decompress it. #WHERE DO THEY DOWNLOAD IT?#
. Open a terminal/cmd window, and run:
+
[source]
----
python setup.py install
----

=== Command syntax

----
configure_pinboards [-h] [--ts_url TS_URL] [--username USERNAME] [--password PASSWORD]
                       [--disable_ssl] [--action ACTION] [--category PINBOARD_CATEGORY]
                       [--user_group USER_GROUP_NAME] [--grant_permission] [--remove_permission]
                       [--pinboards PINBOARDS]
----


==== Mandatory arguments

[cols="30,70%",options="header"]
|====================
| Argument | Description
a| `--ts_url TS_URL` | `TS_URL` is the URL to your ThoughtSpot instance, e.g. *\https://myserver*
a| `--username USERNAME` | `USERNAME` is the username of the user.
a| `--password PASSWORD` | `PASSWORD` is the password of the user.
a| `--action ACTION` | Supported values for `ACTION` are `*set*`, `*add*`, and `*remove*`. Use `*set*` to
                        set the home pinboard. Use `*add*` or `*remove*` to add or remove pinboards in user favorites.
a| `--category CATEGORY` | Supported values are `*home*`, or `*favorites*`. Choose 'home' to execute
                        action on home pinboard. Choose 'favorites' to execute action on user
                        favorites
a|`--user_group USER_GROUP`  | `USER_GROUP` is the name of the user group to which to execute the specified action.
a|`--pinboards PINBOARDS`  | `PINBOARDS` is a list of comma separated pinboard ID(s). For setting the Home Pinboard you must specify only one
                        pinboard ID.
|====================

==== Optional arguments

[cols="30,70%",options="header"]
|====================
| Argument | Description
a| `-h, --help` | Shows the help message and exit.
a| `--disable_ssl` | Ignores SSL errors.
a| `--grant_permission` | Grants permissions to users of the specified user group
                      who do not have permissions to the specified pinboard(s). (Otherwise, skips the
                      specified action for such user.)
a| `--remove_permission` | Removes permissions of users of the specified user group. NOTE: Applicable only for remove favorites user action.
|====================

== Using the script

=== Setting the User Home Pinboard for Mobile users

Sets a given pinboard as the Home Pinboard in the mobile app for all users of a given user group in a ThoughtSpot cluster.

==== Command syntax:
[source]
----
python3 -m pinboard.configure_pinboards --ts_url <URL of ThoughtSpot instance> --username  <ThoughtSpot username> --password <ThoughtSpot password> --action set --category home --user_group <user group name> --grant_permission --pinboards <pinboard ID>
----
==== Example:
[source]
----
python3 -m pinboard.configure_pinboards --ts_url http://172.18.2.39:8088 --username tsadmin --password admin --action set --category home --user_group rls-group-1 --grant_permission --pinboards 2ff57a24-cf90-485f-8b4b-45fc17474c6f
----

=== Adding Pinboards to User Favorites

Adds given pinboards to User Favorites for all users of given user group in a ThoughtSpot cluster.

==== Command syntax:
[source]
----
python3 -m pinboard.configure_pinboards --ts_url <URL of ThoughtSpot instance> --username <ThoughtSpot username> --password <ThoughtSpot password> --action add --category favourites --user_group <user group name> --grant_permission --pinboards <pinboard IDs>
----
==== Example:
[source]
----
python3 -m pinboard.configure_pinboards --ts_url http://172.18.2.39:8088 --username tsadmin --password admin --action add --category favourites --user_group rls-group-1 --grant_permission --pinboards e0836cad-4fdf-42d4-bd97-567a6b2a6058,2ff57a24-cf90-485f-8b4b-45fc17474c6f
----

=== Removing Pinboards from User Favorites

Removes given pinboards from User Favorites for all users of given user group in a ThoughtSpot cluster.

==== Command syntax: #FAVORITE OR FAVOURITE?# #Note: I normally change British spellings in our docs to the American version, but if your script uses the spelling of "Favourite", I'd be worried about breaking it if I change category value name to "Favorite". In talking to Vikas, he thought it might be possible for you to change it use/support "Favorite". Let me know if this is possible.#
[source]
----
python3 -m pinboard.configure_pinboards --ts_url <URL of ThoughtSpot instance> --username <ThoughtSpot username> --password <ThoughtSpot password> --action remove --category favourites --user_group <user group name> --pinboards <pinboard IDs>
----
==== Example
[source]
----
python3 -m pinboard.configure_pinboards --ts_url http://172.18.2.39:8088 --username tsadmin --password admin --action remove --category favourites --user_group rls-group-1 --pinboards e0836cad-4fdf-42d4-bd97-567a6b2a6058,2ff57a24-cf90-485f-8b4b-45fc17474c6f
----
