= Packages installed with ThoughtSpot for Amazon Linux 2
:last_updated: 01/04/2020
:linkattrs:
:experimental:

View the packages necessary to deploy ThoughtSpot with Amazon Linux 2.

To successfully deploy ThoughtSpot in your organization, you must have the following packages on each node of your ThoughtSpot cluster: yum, python 3, and R. If you are deploying ThoughtSpot on version 7.2.0 or earlier, you must also have python 2 packages.
When the Ansible playbook runs, it automatically installs them.

ThoughtSpot works with the latest version of each package; see the minimum supported version.

[#yum]
[#pip2]
[#pip3]
[#r]
[tabset]
====
Yum RPM packages;;
+
--
Download: link:{attachmentsdir}/yum-rpm-packages.csv[Yum RPM package list].

include::partial$packages/yum-rpm-packages.adoc[]
--
Python 2 packages for 7.2.0 and earlier;;
+
--
Download: link:{attachmentsdir}/pip2-rpm-packages.csv[Python2 RPM package list].
include::partial$packages/pip2-rpm-packages.adoc[]
--
Python 3 packages for 7.2.0 and earlier;;
+
--
Download: link:{attachmentsdir}/pip3-rpm-packages.csv[Python3 RPM package list for 7.2.0 and earlier].
include::partial$packages/pip3-rpm-packages.adoc[]
--
Python 3 packages for 7.2.1 and later;;
+
--
Download: link:{attachmentsdir}/pip3-rpm-packages-721.csv[Python3 RPM package list for 7.2.1 and later].
include::partial$packages/pip3-rpm-packages-721.adoc[]
--
R packages;;
+
--
Download: link:{attachmentsdir}/r-rpm-packages.csv[R RPM package list].
include::partial$packages/r-rpm-packages.adoc[]
--
====
