= Connection reference for Oracle
:last_updated: 08/09/2021
:experimental:
:linkattrs:
:page-partial:
:page-aliases: /data-integrate/embrace/embrace-adw-reference.adoc

Learn about the fields used to connect to Oracle databases. You need specific information to establish a seamless and secure connection. All fields are required, except where noted.

[#connection-name]
Connection name::  Enter a new Oracle connection name.
[#connection-description]
Connection description::
Provide a short description of the connection.
_(Optional)_
[#user]
User::  Enter the Oracle account username.
[#password]
Password::  Enter the Oracle account password.
[#net-service-name]
Net Service Name:: Specify the net service name of the Oracle account.
[#wallet-file]
Wallet file:: Upload the wallet file containing your Oracle client credentials. If you do not have a wallet file, contact your Autonomous Database administrator.
[#schema]
Schema:: Specify the schema associated with the database.
_Optionall field_.
