= Dremio connection reference
:last_updated: 08/20/2021
:linkattrs:
:page-partial:

You need very specific information to establish a seamless and secure connection with your Dremio database.

Here is a list of fields for Dremio connections.

You require all these fields, except the ones we marked _(Optional)_.

[#connection-name]
Connection name::
Enter the name for the new connection.
[#connection-description]
Connection description::
_(Optional)_ Provide a short description of the connection.
[#host]
Host::
Enter the Dremio server host name.
[#http-path]
Port::
Dremio server port.
[#user]
User::
Enter the user associated with the Dremio database.
[#password]
Password::
Enter the password of the user associated with the Dremio database.
[#project-id]
Project id::
_(Optional for Service Account only)_ Enter the project ID of the Dremio database.
[#Schema]
Schema::
_(Optional)_ Enter the schema of the Dremio database.
[#oauth-client-id]
(OAuth only) OAuth Client ID::
Enter the OAuth client ID associated with the user of the Dremio database.
[#oauth-client-secret]
(OAuth only) OAuth Client Secret::
Enter the OAuth client secret associated with the user of the Dremio database.
[#auth-url]
(OAuth only) Auth Url::
Enter the Auth Url associated with the user of the Dremio database.
[#access-token-url]
(OAuth only) Access token Url::
Enter the Access token Url associated with the user of the Dremio database.