= Redshift connection reference
:last_updated: 01/10/2022
:experimental:
:linkattrs:
:page-partial:
:page-aliases: /data-integrate/embrace/embrace-redshift-reference.adoc

Learn about the fields used to create a Redshift connection.

Here is a list of the fields of a Redshift connection.
You need specific information to establish a seamless and secure connection.
All fields are required, except where noted.
[#connection-name]
Connection name::  Enter a new Redshift connection name.
[#connection-description]
Connection description::
Provide a short description of the connection.
_(Optional)_
[#host]
Host::  Enter the host name associated with the Redshift database.
[#port]
Port::  Enter the port number associated with the Redshift database.
[#user]
User::  Enter the Redshift account username.
[#password]
Password::  Enter the Redshift account password.
[#database]
Database::  Specify the database associated with the account.
[#db-user]
(IAM only) Db User:: Specify the db user associated with the account.
[#access-key]
(IAM only) Access Key:: Specify the access key associated with the account.
[#secret-key]
(IAM only) Secret Key:: Specify the secret key associated with the account.
[#iam-oauth-client-id]
(OAuth only) OAuth Client ID:: Specify the OAuth client ID associated with the account.
[#oauth-client-secret]
(OAuth only) OAuth Client Secret:: Specify the OAuth client secret associated with the account.
[#oauth-auth-url]
(OAuth only) Auth Url:: Specify the Auth Url associated with the account.
[#oauth-access-token-url]
(OAuth only) Access Token Url:: Specify the Access token URL associated with the account.
[#oauth-role-arn]
(OAuth only) Role ARN:: Specify the role ARN associated with the account.
[#oauth-db-groups]
(OAuth only) DbGroups:: Specify the DbGroups associated with the account.
