= ThoughtSpot artifacts for deploying on your own OS
:last_updated: 4/19/2023
:linkattrs:
:author: Teresa Killmond
:page-aliases: /appliance/amazon-linux-2/al2-ts-artifacts.adoc
:experimental:
:description: Get the two primary tarball artifacts for configuring ThoughtSpot using Amazon Linux 2, OEL, or RHEL.

include::partial$ts-artifacts-customer-os.adoc[]

== Next steps

Next, proceed to install:

* xref:customer-os-install-online.adoc[install ThoughtSpot on online clusters], where the hosts can connect to the public repositories to download the required packages
* xref:customer-os-install-offline.adoc[install ThoughtSpot on offline clusters], where the hosts cannot connect to the public repositories to download the required packages

'''
> **Related information**
>
> * xref:customer-os.adoc[]
> * xref:customer-os-prerequisites.adoc[]
> * xref:customer-os-install-online.adoc[Installing ThoughtSpot on online clusters]
> * xref:customer-os-install-offline.adoc[Installing ThoughtSpot on offline clusters]
> * xref:customer-os-upgrade.adoc[Upgrading ThoughtSpot on your own OS to a new release]
> * xref:customer-os-add-node.adoc[Adding new nodes to clusters running on your own OS]
> * xref:customer-os-packages.adoc[Packages installed with ThoughtSpot running on your own OS]