= CentOS end-of-life announcement
:last_updated: 10/14/2022
:linkattrs:
:experimental:
:description: End-of-life information about CentOS-based ThoughtSpot software and hardware deployments.

This page provides the end-of-sale (EOS), and end-of-service-life (EOSL).

ThoughtSpot ships an xref:security-thoughtspot-lifecycle.adoc[embedded CentOS 7 Linux] with software and hardware deployments. Because https://endoflife.date/centos[RedHat plans to EOL CentOS^], ThoughtSpot will EOL our CentOS-based deployments.

If you are using a CentOS-based software or hardware deployment, you must migrate using one of our supported options to continue to receive support from ThoughtSpot.

== Key dates

[cols="30%,70%"]
|===
|Date |Event

|January 1, 2023
|EOS for new CentOS-based embedded Linux deployments

|January 1, 2023
|EOR for existing CentOS-based software and hardware deployments

|December 31, 2023
|EOSL for CentOS-based software and hardware deployments
|===

== Migration options

ThoughtSpot supports the following migration paths:

* ThoughtSpot Cloud SAAS
* One of the following bring-your-own-Linux (BYOL) variants:
** xref:rhel.adoc[ RedHat Enterprise Linux (RHEL) / Oracle Enterprise Linux (OEL)]
** xref:al2.adoc[Amazon Linux 2 (AL2)]

+
IMPORTANT: These BYOL variants are not supplied/embedded by ThoughtSpot. You must manage the deployment of the OS yourself.

> **Migration help**
>
> * ThoughtSpot can provide professional services to help you migrate.
> * For more information, contact your ThoughtSpot sales or customer service representative, or open a case with {support-url}.
