= Omitting outer aggregation from your formula
:last-updated: 10/12/2021
:linkattrs:
:experimental: 

////
== Intro
Click link:{attachmentsdir}/Meetings_tiny.csv[here] to download this data set.
////

All of the examples in this document have so far included both an “inner aggregation” and an “outer aggregation”.  This article discusses the effect of omitting the outer aggregation

[#example-5]
== Removing outer aggregation

In the formula below, sum is the inner aggregation and average is the outer aggregation:


*Formula*: +
[source]
----
Average hours per activity class =average(group_aggregate(sum(hours), query_groups() + {activity class}, {}))
----

This formula specifies that we should aggregate hours by summing to the level of detail specified by the dimensions in the search bar + _activity class_. Then we should re-aggregate to the search bar level of detail by averaging.

Let’s assume that the search bar specifies the account level of detail.

Using our meetings dataset as an example, this would mean that for each account we do the following:
Calculate two values: 1) sum of hours for all meetings and 2) sum of hours for all calls.
Average those two values to calculate the final value for the account.

The resulting table will contain one row per account, containing the averaged value.

Search for: `account`   `average hours per activity class`    `sort by account`

[#example-5-1-1]
.Example 5.1.1
[options=”header”]
|===
| Account | Hours per activity class averaged

| Amazon | 11

| Oracle | 18

| Redshift | 3

| Snowflake | 3.5
|===

// This is described in detail in Section 2.

In any formula, you have the option of omitting the outer aggregation (“average” in this case), but this is not recommended and may lead to confusing results. When you omit the outer aggregation, the result shows the table or chart at the level of detail of the inner aggregation. In this example, the inner aggregation is at the _activity class_ level of detail.

If we omit the outer aggregation, the table would be displayed as follows:

Search for: `account`   `average hours per activity class`    `sort by account`

[#example-5-1-2]
.Example 5.1.2
[options=”header”]
|===
| Account | Hours per activity class averaged

| Amazon | 11

| Oracle | 18

| Redshift | 5

| Redshift | 1

| Snowflake | 2

| Snowflake | 5
|===


In the table above, because the outer aggregation has been omitted from the hours per activity class averaged formula, we display the table at the _activity class_ level of detail, but we do not show a column for _activity class_.

If you add an _activity class_ column, this table makes more sense:

Search for: `account`   `average hours per activity class `     `sort by account`

[#example-5-1-3]
.Example 5.1.3
[options=”header”]
|===
| Account | Activity class | Hours per activity class averaged

| Amazon | meeting | 11

| Oracle | meeting | 18

| Redshift | meeting | 5

| Redshift | call | 1

| Snowflake | meeting | 2

| Snowflake | call | 5
|===

In a nutshell, omitting the outer aggregation means the formula will not be aggregated to the level of detail specified in the search bar. This is confusing to the user and not recommended.

If you have a preference for placing your outer aggregation in the search bar, this is an option. You can omit the outer aggregation from the formula and place it in the search bar instead. For example, if you omit the outer aggregation in the formula above, the formula would look like this:

*Formula*: +
[source]
----
hours per activity class = group_aggregate(sum(hours), query_groups() + {activity class}, {})
----

In this case, you could achieve outer aggregation to the search bar level by putting the following in your search:

Search for: `account`   `average hours per activity class`    `sort by account`

[#example-5-1-4]
.Example 5.1.4
[options=”header”]
|===
| Account | Average hours per activity class

| Amazon | 11

| Oracle | 18

| Redshift | 3

| Snowflake | 3.5
|===


This results in the same table generated by including the outer aggregation in the formula, but the column heading will be prefixed by “Average”.

This is a valid approach, but requires that the user of the formula remember to add the aggregation to the front of the formula when used in the search bar. When omitted, the results are confusing, so recommended usage is to always include the outer aggregation in the formula.
