= Filters in group_aggregate()
:last-updated: 10/12/2021
:experimental:
:linkattrs: 

////
== Intro
Click link:{attachmentsdir}/Meetings_tiny.csv[here] to download this data set.
////

Now let’s see what happens when you use filters in your search. The last argument of group_aggregate() allows you to specify whether the filter from the search should be applied in the formula.

[#example-4]
== Adding filters through the Search bar

In this example, we’ll apply a filter in the search bar that filters for activity class = “call”.

First, let’s look at what our table looks like with no filter. This is created by the following search.

Search for: `account`  `activity class`   `hours`   `sort by account`

[options=”header”]
|===
| Account | Activity Class | Total Hours

| Amazon | meeting | 11

| Oracle | meeting | 18

| Redshift | meeting | 5

| Redshift | call | 1

| Snowflake | meeting | 2

| Snowflake | call | 5
|===

Now let’s add a filter for `activity class = “call”`.

Search for: `account`    `activity class`   `hours`   `activity class = call`    `sort by account`

[options=”header”]
|===
| Account | Activity Class | Total Hours

| Redshift | call | 1

| Snowflake | call | 5
|===


Finally, let’s add a formula that aggregates hours to the account level of detail:

*Formula*: +
[source]
----
hours per account =average(group_aggregate(sum(hours), {account}, {}))
----

And let’s add that formula to our search bar,

Search for: `account` `activity class`  `hours`  `hours per account`   `activity class = call`  `sort by account`

[#example-4-1-1]
.Table 4.1.1
[options=”header”]
|===
| Account | Activity Class | Total Hours | Hours per account

| Redshift | call | 1 | 6.00

| Snowflake | call | 5 | 7.00
|===


This gives us a result which filters our rows to only rows that include “call”, but note that `Hours per account` does not match `Total Hours`. This is because `Hours per account` is aggregated without the filter, because the last argument of group_aggregate is {}.

If you want your formula to take into account the filters specified in the search, you can use the query_filters() argument like this:

*Formula*: +
[source]
----
hours per account =average(group_aggregate(sum(hours), {account}, query_filters()))
----

Now your resulting table will look like this:

[#example-4-1-2]
.Table 4.1.2
[options=”header”]
|===
| Account | Activity Class | Total Hours | Hours per account

| Redshift | call | 1 | 1.00

| Snowflake | call | 5 | 5.00
|===

== Adding filters to your formula

You can also include filters in your group_aggregate formula which are not in the search bar. For example, if you want your formula to explicitly filter for activity class = “call”, regardless of what is in the search bar, you could create it like this:

*Formula*: +
[source]
----
hours per account =average(group_aggregate(sum(hours), {account}, activity class = “call”))
----

If you now perform the following search:

Search for: `account`   `activity class`  `hours`   `hours per account`   `sort by account`   `sort by activity class`

You’ll get a table where Hours per account results in values that are filtered by “call”, even though the table itself contains rows for both calls and meetings.

[#example-4-2]
.Example 4.2
[options=”header”]
|===
| Account | Activity Class  | Total Hours | Hours per account

| Amazon | meeting | 11 | \{null}

| Oracle | meeting | 18 | \{null}

| Redshift | call | 1 | 1

| Redshift | meeting | 5 | 1

| Snowflake | call | 5 | 5

| Snowflake | meeting | 2 | 5
|===

== Using multiple filters

You can put multiple filters in the filters argument of the group_aggregate function. For example, if you want to filter on both activity class and activity date, you could create a group_aggregate function that looks like this:

*Formula*: +
[source]
----
hours per account =average(group_aggregate(sum(hours), {account}, activity class = “call”, activity date >= 04/01/2020 and activity date <= 04/14/2020))
----

In the above example, the activity class and activity date filters will be added in an `and` condition together.

Search for: `account`   `activity class`  `hours`  `hours per account`    `sort by account`  `sort by activity class`

[#example-4-3]
.Example 4.3
[options=”header”]
|===
| Account | Activity Class | Total Hours | Hours per account

| Amazon | meeting | 11 | \{null}

| Oracle | meeting | 18 | \{null}

| Redshift | call | 1 | 1

| Redshift | meeting | 5 | 1

| Snowflake | call | 5 | 4

| Snowflake | meeting | 2 | 4
|===


You can also use AND, OR, and parens, as shown below to flexibly combine filters:

*Formula*: +
[source]
----
hours per account =average(group_aggregate(sum(hours), {account}, activity class = “call” or (activity date >= 04/01/2020 and activity date <= 04/14/2020)))
----
