= Authentication flow with embed
:last_updated: 02/01/2021
:linkattrs:
:experimental:

You can enable Single Sign On (SSO) with your embedded version of ThoughtSpot.

If your ThoughtSpot system is configured for Security Assertion Markup Language (SAML) you can enable Single Sign On (SSO) for your embed application.

== iFrame embedding with SSO

ThoughtSpot clusters running 7.0.1 or lower Software release versions may add additional headers and restrict iFrame embedding with SSO. To resolve this issue, apply `saml_iframe_options.patch`.

. Log in to ThoughtSpot.
. Go to `/usr/local/scaligent/release/production/orion/tomcat/callosum/saml`.
. Edit `applicationContext-security.xml`.
. Apply `saml_iframe_options.patch`.
+
[source,text]
----
diff --git a/production/orion/tomcat/callosum/saml/applicationContext-security.xml b/production/orion/tomcat/callosum/saml/applicationContext-security.xml
index 096558ca13a..3dae46e5d83 100644
--- a/production/orion/tomcat/callosum/saml/applicationContext-security.xml
+++ b/production/orion/tomcat/callosum/saml/applicationContext-security.xml
@@ -22,6 +22,9 @@
     <security:csrf disabled="true"/>
     <security:custom-filter before="FIRST" ref="metadataGeneratorFilter"/>
     <security:custom-filter after="BASIC_AUTH_FILTER" ref="samlFilter"/>
+    <security:headers>
+      <security:frame-options disabled="true"/>
+    </security:headers>
   </security:http>
----

== Authenticate when the window is initialized

Place the JS API library in the `<head>` section of the HTML on your Web page.
Ensure that the JS API script tag is the first script loaded in the page.

Your web page needs to authenticate by calling `window.thoughtspot.initialize` and waiting for the `onInitializationCallback` to be called before embedding any ThoughtSpot visualizations or making any ThoughtSpot REST API calls.

The JS API call `window.thoughtspot.initialize` can cause the entire Web page to be re-directed to your Identity Provider (IDP).
This order implies that you may not execute any of your application logic before `window.thoughtspot.initialize` has called your callback.

Any redirection could interfere with your application logic.
So, don't embed any static ThoughtSpot visualizations in your HTML.
In other words, you should generate the ThoughtSpot visualizations dynamically after `window.thoughtspot.initialize` has called your callback.

The `onAuthExpiration` is only available if you have at least one ThoughtSpot visualization iframe in your web page.

== Example of code flow

. To authenticate with SSO, download the ThoughtSpot JavaScript library; see xref:downloads.adoc[Downloads for ThoughtSpot].

. Include the library file in your web page's `<head>` section:
+
[source,html]
----
<head>
  <script type=”text/javascript” src=”<protocol><your.thoughtspot.domain>/js/api/api.min.js”>
   ...
</head>
----

. From your application code, authenticate to ThoughtSpot by calling to the `window.thoughtspot.initialize` method.
+
For example:
+
[source,text]
----
 <script type=”text/javascript”>
     thoughtspotHost = <hostname_or_ip_w/o_http>
     function setUpThoughtSpotAPI() {
         window.thoughtspot.initialize(
             function(isUserAuthenticatedToThoughtSpot) {
                    if (isUserAuthenticatedToThoughtSpot) {
                        // load an embedded ThoughtSpot visualization or
                        // make a ThoughtSpot data API call
                    } else {
                        // the current user into your system is not authenticated
                        // into your ThoughtSpot instance, case in any other way suitable
                        // to your application logic. Do NOT call setUpThoughtSpotAPI again
                        // here as that could create an infinite cycle.
                    }
             },
             function() {
                 // the user got logged out from ThoughtSpot, possibly because
                 // their session with ThoughtSpot expired, you can call setUpThoughtSpotAPI()
                 // again to re-authenticate the user or handle this case in any other way
                 // suitable to your application logic.
             },
             thoughtspotHost
         );
     }
 </script>
----

. Work with ThoughtSpot support to enable CORS between your client application domain and the ThoughtSpot domain.
+
When this value is changed, the `nginx` service is restarted automatically to reflect the change.

Now, you're ready to either xref:embed-viz.adoc[embed a visualization] or xref:data-api-get.adoc[use the REST API to get data] from ThoughtSpot and display it within your Web page or application.