= Known issues
:keywords: known issues
:last_updated: 10/6/2022
:experimental:
:page-layout:
:linkattrs:

These are the known issues in this release of ThoughtSpot Software.

[#releases-8-7-x]
== 8.8.0.sw known issues

[cols="17%,39%,38%"]
|===
|Issue ID |Description|Symptoms, conditions, and workaround

|SCAL-129737
|Headline summary is truncated despite the number of decimals.
a|*Symptoms*:

Headline with decimal digits is rounded off, causing a loss of accuracy.

*Conditions*:

Headline value is double type

*Workaround*:

None

|SCAL-129691
|“UniqueCount is not supported for the current query” error on pinned-headline tiles in a Liveboard.
a|*Symptoms*:

- If you try to edit the pinned visualization, the Edit page will show the entire answer that the pinned headline came from. If the headline summary in the answer page is showing --, this is a good indication that the current aggregation selected is not compatible with the column that it is summarizing.
- This should only happen with formula columns.
- Pinning the headline to a liveboard is not a locked action from the UI; instead, the visualization tile will display the execution error message specified above when we attempt to retrieve the actual summary.

*Conditions*:

- The headline is over a formula column that contains any of `unique_count`, `unique_count_if`, `group_unique_count`, `approx_unique_count`.
- The formula’s unique count portion uses columns that come from tables that are Embrace (non-Falcon, external data warehouse, etc.) tables.
- The selected headline aggregation for the formula (the headline visualization is at the bottom of the main answer visualization) is Table Aggregate.

*Workaround*:

Set the selected headline aggregation to something other than Table Aggregate. Usually, TOTAL is a sufficient replacement for Table Aggregate and better matches customer use cases.

|===
