= 7.1 Release Notes
:experimental:
:last_updated: 8/19/2021
:linkattrs:
:redirect_from: "/release/notes.html", "/7.0/release/notes.html", "/7.0.0.CU1/release/notes.html", "/7.0.1/release/notes.html", "/release/notes.html", "/7.0.0.mar.sw/release/notes.html"


ThoughtSpot version 7.1 is now available. These release notes include information about new and enhanced features.

To see our feature deprecation plans, please see xref:deprecation.adoc[].

For a complete list of issues that we fixed in this release, see xref:fixed.adoc#releases-7-0-x[Fixed issues].

* <<new-7-1,7.1 New Features and Functionality>>
* <<new-7-1,7.1 New Features and Functionality>>
* <<upgrade-paths,Supported Upgrade Paths>>

[#new-7-1]
== 7.1 New Features and Functionality

For a complete list of issues that we fixed in this release, see xref:fixed.adoc#releases-7-1-x[Fixed issues].

Here are the most significant new features and improvements in the 7.1 Software Release:

* <<analyst-7-1,For the Analyst>>
* <<business-user-7-1,For the Business User>>
* <<data-engineer-7-1,For the Data Engineer>>
* <<it-ops-engineer-7-1,For the IT Ops Engineer>>

[#analyst-7-1]
=== For the Analyst

[#business-user-7-1]
=== For the Business User

[#data-engineer-7-1]
=== For the Data Engineer

[#it-ops-engineer-7-1]
=== For the IT Ops Engineer

[#rhel]
RHEL ease of installation::
You can now configure a specific admin username for the user who sets up the nodes when deploying on RHEL. Previously, you had to use the default `admin` username, the `1081` uid, and the `1081` gid.
+
Refer to xref:rhel-install-online.adoc[] and xref:rhel-install-offline.adoc[].

[#ui-improvement]
UI improvement for Admin Console::
This release improves the UI and user experience of the xref:admin-portal-nas-mount-configure.adoc[NAS mount], xref:admin-portal-reverse-ssh-tunnel.adoc[Reverse SSH tunnel], xref:admin-portal-smtp-configure.adoc[SMTP], xref:admin-portal-snapshot-manage.adoc[Snapshot], and xref:admin-portal-ssl-configure.adoc[SSL] sections of the Admin Console.

[#upgrade-paths]
== Supported Upgrade Paths

If you are running one of the following versions, you can upgrade to the 7.0 release directly:

* 6.2.x to 7.0.1
* 6.3.x to 7.0.1

This includes any hotfixes or customer patches on these branches.

If you are running a different version, you must do a multiple pass upgrade.
First, upgrade to version 6.2.x, or 6.3.x, and then to the 7.0.1 release.

NOTE: To successfully upgrade your ThoughtSpot cluster, all user profiles must include a valid email address. Without valid email addresses, the upgrade is blocked.
