= 8.4.0 Release Notes
:experimental:
:last_updated: 5/11/2022
:linkattrs:
:page-aliases: /release/notes.adoc

ThoughtSpot version 8.4.0.sw is now available.

These release notes include information about new and enhanced features.

To see our feature deprecation plans, please see xref:deprecation.adoc[].

For a complete list of issues that we fixed in this release, see xref:fixed.adoc#releases-8-4-x[Fixed issues].

* <<new-8-4-0,8.4.0.sw New Features and Functionality>>
* <<upgrade-paths,Supported Upgrade Paths>>

[#new-8-4-0]
== 8.4.0.sw New Features and Functionality

* <<analyst-8-4-0-sw,For the Analyst>>
* <<business-user-8-4-0-sw,For the Business User>>
* <<data-engineer-8-4-0-sw,For the Data Engineer>>
* <<it-ops-engineer-8-4-0-sw,For the IT Ops Engineer>>
* <<developer-8-4-0-sw,For the Developer>>

[#analyst-8-4-0-sw]
=== For the Analyst

[#business-user-8-4-0-sw]
=== For the Business User

[#data-engineer-8-4-0-sw]
=== For the Data Engineer

[#it-ops-engineer-8-4-0-sw]
=== For the IT Ops Engineer

[#developer-8-4-0-sw]
=== For the Developer

[#upgrade-paths]
== Supported Upgrade Paths

If you are running one of the following versions, you can upgrade to the 8.4.0.sw release directly:

* 7.1.x to 7.2.1
* 7.2.x to 8.4.0.sw

This includes any hotfixes or customer patches on these branches.

If you are running a different version, you must do a multiple pass upgrade.

First, upgrade to version 7.1.x or 7.2.x, and then to the 8.4.0.sw release.

NOTE: To successfully upgrade your ThoughtSpot cluster, all user profiles must include a valid email address. Without valid email addresses, the upgrade is blocked.
