= 7.2 Release Notes
:experimental:
:last_updated: 1/14/2021
:linkattrs:
:page-aliases: /release/notes.adoc

ThoughtSpot version 7.2 is now available.

These release notes include information about new and enhanced features.

To see our feature deprecation plans, please see xref:deprecation.adoc[].

For a complete list of issues that we fixed in this release, see xref:fixed.adoc#releases-7-2-x[Fixed issues].

* <<new-7-2,7.2 New Features and Functionality>>
* <<upgrade-paths,Supported Upgrade Paths>>

[#new-7-2]
== 7.2 New Features and Functionality

* <<analyst-7-2,For the Analyst>>
* <<business-user-7-2,For the Business User>>
* <<data-engineer-7-2,For the Data Engineer>>
* <<it-ops-engineer-7-2,For the IT Ops Engineer>>
* <<developer-7-2,For the Developer>>

[#analyst-7-2]
=== For the Analyst

[#business-user-7-2]
=== For the Business User

[#data-engineer-7-2]
=== For the Data Engineer

[#it-ops-engineer-7-2]
=== For the IT Ops Engineer

[#developer-7-2]
=== For the Developer

[#upgrade-paths]
== Supported Upgrade Paths

If you are running one of the following versions, you can upgrade to the 7.2 release directly:

* 6.3.x to 7.2
* 7.0.x to 7.2
* 7.1.x to 7.2

This includes any hotfixes or customer patches on these branches.

If you are running a different version, you must do a multiple pass upgrade.

First, upgrade to version 6.3.x, 7.0.x, or 7.1 and then to the 7.2 release.

NOTE: To successfully upgrade your ThoughtSpot cluster, all user profiles must include a valid email address. Without valid email addresses, the upgrade is blocked.
