= 8.8.sw Release Notes
:experimental:
:last_updated: 5/19/2022
:linkattrs:
:page-aliases: /release/notes.adoc

ThoughtSpot version 8.8.0.sw is now available.

These release notes include information about new and enhanced features.

To see our feature deprecation plans, please see xref:deprecation.adoc[].

For a complete list of issues that we fixed in this release, see xref:fixed.adoc#releases-8-8-x[Fixed issues].

* <<new-8-8-0,8.8.0.sw New Features and Functionality>>
* <<upgrade-paths,Supported Upgrade Paths>>

[#new-8-8-0]
== 8.8.0.sw New Features and Functionality

include::partial$limited-availability-notice.adoc[]

* <<analyst-8-8-0-sw,For the Analyst>>
* <<business-user-8-8-0-sw,For the Business User>>
* <<data-engineer-8-8-0-sw,For the Data Engineer>>
* <<it-ops-engineer-8-8-0-sw,For the IT Ops Engineer>>
* <<developer-8-8-0-sw,For the Developer>>

[#analyst-8-8-0-sw]
=== For the Analyst

Customizable colors for heatmap and treemap charts::
You can now customize the colors used for heatmap and treemap charts. Prior to this release, the only available heatmap color was teal in various shades, and the only available treemap color was green in various shades. Now you can choose any color in your color palette. For more information, see xref:chart-heatmap.adoc[] and xref:chart-treemap.adoc[].

New answer experience::
The xref:answer-experience-new.adoc[new answer experience] is now GA and on by default. The new answer experience contains the following features:

include::partial$new-answer-experience-features.adoc[]

New answer experience deprecations::

include::partial$new-answer-experience-deprecations.adoc[]

TML import improvements::
You can now import xref:tml.adoc[TML] files that contain certain errors. During the import process, ThoughtSpot removes the part of the object that contains errors, and allows you to import the rest of the object. These errors include the following:
+
--
* Some Liveboard visualizations contain errors, but the overall Liveboard is valid: ThoughtSpot removes the visualizations that contain errors and imports the Liveboard.
* Some Liveboard filters contain errors, but the overall Liveboard is valid: ThoughtSpot removes the filters that contain errors and imports the Liveboard.
* Destination tables for some joins in a table do not exist, but the overall table is valid: ThoughtSpot removes the joins that do not have destination tables and imports the table.
--
+
Refer to xref:scriptability.adoc#migrate-object[Migrate an object].

[#business-user-8-8-0-sw]
=== For the Business User

Support for multiple contains, begins_with, and ends_with phrases in versus queries::

ThoughtSpot now supports multiple `contains`, `begins_with`, and `ends_with` phrases in `vs` queries. For example, you can now have a versus query such as `state name begins_with 'a' state name begins_with 'c' vs state name begins_with 'd'`.

For more information, refer to the xref:keywords.adoc#vs[Keyword reference].

Choose sources limitation::
You can no longer select more than 100 data sources to search on when searching data. This maximum of 100 sources improves performance and limits timeouts due to the selection of too many sources.

Geo charts enhancements::
This release includes several enhancements to all geo charts:
+
--
* Improved map quality: This includes faster map loading, better clarity, and more granular details down to the street level when you zoom in.
* A new *map type* option that allows you to customize the display of the geo chart map. The new map type options are Light, Dark, Outdoors, Streets, Satellite, and Satellite Streets. The default is Light.

--
See xref:chart-geo.adoc[].

Improvements to German keywords::
This release improves the translated German keywords. See xref:keywords-de-DE.adoc[].

[#data-engineer-8-8-0-sw]
=== For the Data Engineer

Delete joins that have dependents::
You can now delete a join from the ThoughtSpot UI even if the join has dependents. Deleting the join does not delete the dependents. This allows you to delete a join and create it again in the other direction, without invalidating or deleting any dependent objects.
+
Refer to xref:relationship-create.adoc#delete-join[Delete a join].

[#dbt-improvements]
Integration with dbt improvements::
This release includes the following improvements to the dbt integration:
+
--
* Integration with dbt for Databricks connections
* Import of multiple folders at a time
* Import of a single table within a folder
* Support for joins across multiple folders
--
+
For more information, see xref:dbt-integration.adoc[].

Edit tags from the Data workspace::
You can now edit tags for tables, worksheets, views, and SQL views from the Data workspace home page. Refer to xref:tags.adoc#data-workspace[Use tags to organize].

[#it-ops-engineer-8-8-0-sw]
=== For the IT Ops Engineer

[#developer-8-8-0-sw]
=== For the Developer

Customers licensed to embed ThoughtSpot can use ThoughtSpot Everywhere features and Visual Embed SDK.

To enable ThoughtSpot Everywhere on your cluster, contact ThoughtSpot Support.

For information about ThoughtSpot Everywhere, refer to  link:https://developers.thoughtspot.com/docs[ThoughtSpot Everywhere Documentation, window=_blank].

[#upgrade-paths]
== Supported Upgrade Paths

If you are running one of the following versions, you can upgrade to the 8.8.0.sw release directly:

* 7.2.x to 8.8.0.sw
* 8.4.x to 8.8.0.sw

This includes any hotfixes or customer patches on these branches.

If you are running a different version, you must do a multiple pass upgrade.

First, upgrade to version 7.2.x or 8.4.x, and then to the 8.8.0.sw release.

NOTE: To successfully upgrade your ThoughtSpot cluster, all user profiles must include a valid email address. Without valid email addresses, the upgrade is blocked.
