= 8.8.sw Release Notes
:experimental:
:last_updated: 5/19/2022
:linkattrs:
:page-aliases: /release/notes.adoc

ThoughtSpot version 8.8.0.sw is now available.

These release notes include information about new and enhanced features.

To see our feature deprecation plans, please see xref:deprecation.adoc[].

For a complete list of issues that we fixed in this release, see xref:fixed.adoc#releases-8-8-x[Fixed issues].

* <<new-8-8-0,8.8.0.sw New Features and Functionality>>
* <<upgrade-paths,Supported Upgrade Paths>>

[#new-8-8-0]
== 8.8.0.sw New Features and Functionality

include::partial$limited-availability-notice.adoc[]

* <<analyst-8-8-0-sw,For the Analyst>>
* <<business-user-8-8-0-sw,For the Business User>>
* <<data-engineer-8-8-0-sw,For the Data Engineer>>
* <<it-ops-engineer-8-8-0-sw,For the IT Ops Engineer>>
* <<developer-8-8-0-sw,For the Developer>>

[#analyst-8-8-0-sw]
=== For the Analyst

[#business-user-8-8-0-sw]
=== For the Business User

[#data-engineer-8-8-0-sw]
=== For the Data Engineer

Delete joins that have dependents::
You can now delete a join from the ThoughtSpot UI even if the join has dependents. Deleting the join does not delete the dependents. This allows you to delete a join and create it again in the other direction, without invalidating or deleting any dependent objects.
+
Refer to xref:relationship-create.adoc#delete-join[Delete a join].

[#it-ops-engineer-8-8-0-sw]
=== For the IT Ops Engineer

[#developer-8-8-0-sw]
=== For the Developer

Customers licensed to embed ThoughtSpot can use ThoughtSpot Everywhere features and Visual Embed SDK.

To enable ThoughtSpot Everywhere on your cluster, contact ThoughtSpot Support.

For information about ThoughtSpot Everywhere, refer to  link:https://developers.thoughtspot.com/docs[ThoughtSpot Everywhere Documentation, window=_blank].

[#upgrade-paths]
== Supported Upgrade Paths

If you are running one of the following versions, you can upgrade to the 8.8.0.sw release directly:

* 7.2.x to 8.8.0.sw
* 8.4.x to 8.8.0.sw

This includes any hotfixes or customer patches on these branches.

If you are running a different version, you must do a multiple pass upgrade.

First, upgrade to version 7.2.x or 8.4.x, and then to the 8.8.0.sw release.

NOTE: To successfully upgrade your ThoughtSpot cluster, all user profiles must include a valid email address. Without valid email addresses, the upgrade is blocked.
