= 9.0.0.sw Release Notes
:experimental:
:last_updated: 11/29/2022
:linkattrs:
:page-aliases: /release/notes.adoc
:description: These release notes include information about new and enhanced features.

++++
<style>
.badge-update-whats-new-beta {
  font-style: normal !important;
  top: -0.03rem !important;
}

</style>
++++

ThoughtSpot version 9.0.0.sw is now available.

These release notes include information about new and enhanced features.

To see our feature deprecation plans, please see xref:deprecation.adoc[].

For a complete list of issues that we fixed in this release, see xref:fixed.adoc#releases-8-8-x[Fixed issues].

* <<new-9-0-0,9.0.0.sw New Features and Functionality>>
* <<upgrade-paths,Supported Upgrade Paths>>

[#new-9-0-0]
== 9.0.0.sw New Features and Functionality

* <<analyst-9-0-0-sw,For the Analyst>>
* <<business-user-9-0-0-sw,For the Business User>>
* <<data-engineer-9-0-0-sw,For the Data Engineer>>
* <<it-ops-engineer-9-0-0-sw,For the IT Ops Engineer>>
* <<developer-9-0-0-sw,For the Developer>>

[#analyst-9-0-0-sw]
=== For the Analyst

Delete joins and RLS rules through TML::
When you edit and import TML files, ThoughtSpot now supports deletion of joins and RLS rules. Refer to xref:tml.adoc[].

[#business-user-9-0-0-sw]
=== For the Business User

Delete tables from ThoughtSpot:: Previously, when deleting tables from Connections, ThoughtSpot did not delete the table’s metadata completely. Starting in 9.0.0.sw, tables deleted through the ThoughtSpot UI disappear completely from your cluster.

[#data-engineer-9-0-0-sw]
=== For the Data Engineer

PostgreSQL connection::
This release added support to the PostgreSQL connection. For more information, see xref:connections-postgresql.adoc[PostgreSQL].

[#it-ops-engineer-9-0-0-sw]
=== For the IT Ops Engineer

[#developer-9-0-0-sw]
=== For the Developer

Customers licensed to embed ThoughtSpot can use ThoughtSpot Everywhere features and Visual Embed SDK.

To enable ThoughtSpot Everywhere on your cluster, contact ThoughtSpot Support.

For information about ThoughtSpot Everywhere, refer to  link:https://developers.thoughtspot.com/docs[ThoughtSpot Everywhere Documentation, window=_blank].

[#upgrade-paths]
== Supported Upgrade Paths

If you are running one of the following versions, you can upgrade to the 9.0.0.sw release directly:

* 8.4.x to 9.0.0.sw
* 8.8.x to 9.0.0.sw

This includes any hotfixes or customer patches on these branches.

If you are running a different version, you must do a multiple pass upgrade.

First, upgrade to version 8.4.x or 8.8.x, and then to the 9.0.0.sw release.

NOTE: To successfully upgrade your ThoughtSpot cluster, all user profiles must include a valid email address. Without valid email addresses, the upgrade is blocked.
