= 8.4.0.sw Release Notes
:experimental:
:last_updated: 5/11/2022
:linkattrs:
:page-aliases: /release/notes.adoc

++++
<style>
.doc .sidebarblock {
  background: #f1f1f1;
  border-radius: 0.75rem;
  border: 1px solid #4444;
  padding: 0.75rem 1.5rem;
  margin-top: 20px;
  margin-bottom: 20px;
  width: 96%;
}

.doc .sidebarblock p {
  margin-top: 1.25rem;
}

.doc .sidebarblock>.content>.title {
    font-weight: 500;
    font-size: .9rem;
    text-align: left;
    margin-top: 10px;
    margin-bottom: 10px;
}

.doc .image:not(.left):not(.right)>img {
    margin-top: -0.2em;
    margin-bottom: -5px;
}

#preamble+.sect1, .doc .sect1+.sect1 {
  margin-top: 1rem;
  margin-left: 10px;
}

.sect1 {
  margin-left: 10px;
}

.doc .sidebarblock .title img {
  margin-top: 0px;
  margin-bottom: -12px;
  margin-right: 5px;
}

span.image {
    vertical-align: text-bottom;
}

img {
    max-width: 95%;
    margin-top: 10px;
    margin-bottom: 10px;
}

.home .columns .box li img.inline {
    margin-top: 0;
}

.label-la {
    /* background-color: #fff; */
    border: 1px solid #00aeef;
    color: #00aeef;
    vertical-align: middle;
    padding-bottom: 5px;
    margin-left: 1px;
    position: relative;
    top: -1px;
    vertical-align: middle;
    padding-top: 4px;
}
</style>
++++

ThoughtSpot version 8.4.0.sw is now available as a limited availability release.

.image:info2.svg[Inline,30] Release 8.4.0.sw [.label.label-la]#LA#
****
8.4.0.sw is a Limited Availability (LA) release provided directly to select customers to test and provide feedback directly to ThoughtSpot to ensure the 8.4.1.sw maintenance release is customer-tested, stable, and reliable.

8.4.1.sw will be generally available for all customers and is scheduled for release in August 2022.
****

These release notes include information about new and enhanced features.

To see our feature deprecation plans, please see xref:deprecation.adoc[].

For a complete list of issues that we fixed in this release, see xref:fixed.adoc#releases-8-4-x[Fixed issues].

* <<new-8-4-0,8.4.0.sw New Features and Functionality>>
* <<upgrade-paths,Supported Upgrade Paths>>

[#new-8-4-0]
== 8.4.0.sw New Features and Functionality

* <<analyst-8-4-0-sw,For the Analyst>>
* <<business-user-8-4-0-sw,For the Business User>>
* <<data-engineer-8-4-0-sw,For the Data Engineer>>
* <<it-ops-engineer-8-4-0-sw,For the IT Ops Engineer>>
* <<developer-8-4-0-sw,For the Developer>>

[#analyst-8-4-0-sw]
=== For the Analyst

Date interval functions::
In this release, we introduced new functions for computing time intervals between two dates. In addition to the existing xref:formula-reference.adoc#diff_days[diff_days] and xref:formula-reference.adoc#diff_time[diff_time] functions, you can now use `diff_years`, `diff_quarters`, `diff_months` `diff_weeks`, `diff_hours`, and `diff_minutes` to calculate time intervals at these additional granularities.
+
If your organization uses a xref:connections-cust-cal.adoc[custom calendar], which can specify a new starting date of a year, starting dates of quarters, a starting day of the month, and a starting day of the week, use the optional custom calendar argument with these functions to calculate the difference between the two dates.
+
Refer to xref:formula-reference.adoc#date-functions[Formula reference date functions].

[#business-user-8-4-0-sw]
=== For the Business User

Starting in May 2022, ThoughtSpot refers to Liveboards instead of pinboards. With Liveboards, you can have an interactive experience and get granular insights through live queries on cloud data, tailored for you. You can use Liveboards to iterate, explore, and drill into more insights, and tell a continuously evolving data story. +
ThoughtSpot plans to support for several releases, and then retire, internal processes and external methods that use the older naming convention.

Key Performance Indicator (KPI) chart type::

You can now create visualizations of your data’s Key Performance Indicators (KPIs). When you search for a measure with a time-related keyword (for example, `Sales weekly`), you can create sparkline visualizations of your data’s Key Performance Indicators (KPIs). ThoughtSpot also supports conditional formatting to add visual cues for KPIs or threshold metrics to easily show where you are falling short or exceeding targets. For more information, see xref:chart-kpi.adoc[].

Auto-select search data source for new users::
When a new user first uses xref:search.adoc[Search], ThoughtSpot intelligently selects a data source for them to search on. ThoughtSpot chooses the most popular data source in the cluster that the user has access to. This allows users to begin to search data easily, without looking through all the existing data sources on their cluster.

[#data-engineer-8-4-0-sw]
=== For the Data Engineer

[#data-workspace-beta]
Data Workspace [.label.label-beta]#Beta#::
This release redesigns the Data section of the product. The new Data Workspace is still in the same place in the product. To access it, select Data from the top navigation bar. The redesign introduces several new features, such as SQL-based views and SpotApps, and makes the UI more intuitive.
+
This feature is in beta and off by default. To enable it, contact {support-url}.

[#sql-views-beta]
SQL-based views [.label.label-beta]#Beta#::
This release introduces beta support for SQL-based views. Users can create views based on custom SQL queries, and use those views as data sources. This type of view has the same functionality as a view based on searching your data.
+
This feature is in beta and off by default. It is part of the new <<data-workspace-beta,Data Workspace>>, which is also in beta and off by default. To enable SQL-based views and the new Data Workspace, contact {support-url}.

[#dbt-beta]
Integration with dbt [.label.label-beta]#Beta#::
ThoughtSpot now offers an integration with dbt. You can provide your existing dbt models and automatically create worksheets in ThoughtSpot that you can use to perform searches on your data.
+
This feature is in beta and off by default. It is part of the new <<data-workspace-beta,Data Workspace>>, which is also in beta and off by default. To enable dbt integration and the Data tab redesign, contact {support-url}.

[#it-ops-engineer-8-4-0-sw]
=== For the IT Ops Engineer

Python 3.9 upgrade::
*_ThoughtSpot-managed CentOS deployments only:_* If you upgraded to Python 3.9 while on ThoughtSpot version 7.2.1, you must xref:python-upgrade.adoc[upgrade your Python version to 3.9] again after you upgrade to ThoughtSpot version 8.4.0.sw.
+
NOTE: This does not apply to customer-managed Amazon Linux 2 or RHEL deployments. Amazon Linux 2 or RHEL deployments do not need to upgrade their Python version again.

[#developer-8-4-0-sw]
=== For the Developer

[#upgrade-paths]
== Supported Upgrade Paths

If you are running one of the following versions, you can upgrade to the 8.4.0.sw release directly:

* 7.1.x to 7.2.1
* 7.2.x to 8.4.0.sw

This includes any hotfixes or customer patches on these branches.

If you are running a different version, you must do a multiple pass upgrade.

First, upgrade to version 7.1.x or 7.2.x, and then to the 8.4.0.sw release.

NOTE: To successfully upgrade your ThoughtSpot cluster, all user profiles must include a valid email address. Without valid email addresses, the upgrade is blocked.
