= 7.2 Release Notes
:experimental:
:last_updated: 1/14/2021
:linkattrs:
:page-aliases: /release/notes.adoc

ThoughtSpot version 7.2 is now available.

These release notes include information about new and enhanced features.

To see our feature deprecation plans, please see xref:deprecation.adoc[].

For a complete list of issues that we fixed in this release, see xref:fixed.adoc#releases-7-2-x[Fixed issues].

* <<new-7-2,7.2 New Features and Functionality>>
* <<upgrade-paths,Supported Upgrade Paths>>

[#new-7-2]
== 7.2 New Features and Functionality

* <<analyst-7-2,For the Analyst>>
* <<business-user-7-2,For the Business User>>
* <<data-engineer-7-2,For the Data Engineer>>
* <<it-ops-engineer-7-2,For the IT Ops Engineer>>
* <<developer-7-2,For the Developer>>

[#analyst-7-2]
=== For the Analyst
[#scriptability]
Improved import workflow for Scriptability:: The new import workflow for xref:scriptability.adoc[Scriptability] identifies errors, suggests solutions, and allows you to resolve these errors as part of the import workflow.
It also has a cleaner, more intuitive UI, with separate sections for different object types.

[#business-user-7-2]
=== For the Business User

[#profile-ui]
UI improvement for user profile::
This release improves the UI and user experience of the xref:user-profile.adoc[user profile].

[#scatter-bubble-charts]
Minimum and maximum on x-axis for scatter and bubble charts::
You can now specify a minimum and maximum value for measures on the x-axis of xref:chart-scatter.adoc[scatter] and xref:chart-bubble.adoc[bubble] charts.
For more information on how to add a minimum and maximum value to a chart axis, refer to xref:chart-axes-options.adoc#edit[Change axis options].

[#geomaps]
Geo map support::
New Zealand;; We added support for regional councils, cities and districts, and postcodes, for New Zealand.
Denmark;; We added support for regions, municipalities, and postal codes, for Denmark.
+
See xref:geomap-reference.adoc[Geo Map Reference].

[#data-engineer-7-2]
=== For the Data Engineer

[#it-ops-engineer-7-2]
=== For the IT Ops Engineer

SAML assertion validity::
ThoughtSpot now supports 2 methods to increase the duration of validity for your xref:saml.adoc#saml-assertion[SAML assertion]: the `SessionNotOnOrAfter` attribute and the `maxAuthenticationAge` parameter. You can ask ThoughtSpot to disable either one of these checks. If you use both, and either check fails, ThoughtSpot does not authenticate the user. Some IDPs do not support use of `SessionNotOnOrAfter`. If your IDP does not support use of `SessionNotOnOrAfter`, remove that attribute from your IDP assertion and https://community.thoughtspot.com/customers/s/contactsupport[ask ThoughtSpot Support^] to enable `maxAuthenticationAge`.

[#credit-usage-pinboard]
Credit Usage Liveboard::  The Credit Usage Liveboard, a Liveboard for monitoring your credit consumption under the consumption-based pricing model, is now accessible from the Admin Console, under menu:Billing[Credit consumption].

[#developer-7-2]
=== For the Developer
ThoughtSpot Everywhere::
For information about the new features and enhancements introduced in this release, refer to the documentation embedded in your ThoughtSpot environment under the *Develop* tab.

[#upgrade-paths]
== Supported Upgrade Paths

If you are running one of the following versions, you can upgrade to the 7.2 release directly:

* 7.0.x to 7.2
* 7.1.x to 7.2

This includes any hotfixes or customer patches on these branches.

If you are running a different version, you must do a multiple pass upgrade.

First, upgrade to version 7.0.x or 7.1.x, and then to the 7.2 release.

NOTE: To successfully upgrade your ThoughtSpot cluster, all user profiles must include a valid email address. Without valid email addresses, the upgrade is blocked.
