= Upgrade your Python version
:last_updated: 4/26/2022
:linkattrs:
:experimental:

By default, your ThoughtSpot cluster comes with either Python 3.6 or Python 3.7. *In ThoughtSpot version 7.2.1 and later,* you can upgrade your Python version to Python 3.9, remain on the default version, or return to Python 3.6 or 3.7 if you are on Python 3.9.

[#supported-versions]
== Supported Python versions
ThoughtSpot supports use of the following versions of Python 3 for deployment. Python 3.6 is the default version for customer-managed RHEL, customer-managed OEL, and ThoughtSpot-managed CentOS. Python 3.7 is the default version for customer-managed Amazon Linux 2.

* Python 3.6: ThoughtSpot-managed CentOS for AWS, GBQ, VMware, Azure, SMC, and Dell; customer-managed xref:rhel.adoc[RedHat Enterprise Linux (RHEL)]; customer-managed xref:rhel.adoc[Oracle Enterprise Linux (OEL)]; customer-managed xref:al2.adoc[Amazon Linux 2]
* Python 3.7: customer-managed Amazon Linux 2
* Python 3.9: ThoughtSpot-managed CentOS for AWS, GBQ, and Azure; customer-managed xref:rhel.adoc[RedHat Enterprise Linux (RHEL)]; customer-managed xref:al2.adoc[Amazon Linux 2]

== Upgrade your Python version
After you create the cluster, upgrade your Python version.

To upgrade your Python version, follow these steps:

. `ssh` into a node as an admin user.
+
----
ssh admin@<node-IP>
----

. Run the following command to stop your cluster:
+
----
tscli cluster stop
----

. Ensure that the version of Python you want to use is <<supported-versions,ThoughtSpot-certified>> for your deployment type.
. Install the version of Python you want to use, either 3.6, 3.7, or 3.9.
. Navigate to the correct location to run the command:
+
----
cd /usr/local/scaligent/release/
----
. Run the following command on all nodes, at `/usr/local/scaligent/release/` for each node:
+
----
PATH=/usr/pgsql-11/bin:$PATH pip3 install -r production/prod_image/current/pip_packages/requirements_no_versions.txt --upgrade
----
. Run the following command to start your cluster again:
+
----
tscli cluster start
----

