= Manage cluster operations on Ansible for clusters that use RHEL
:last_updated: 12/8/2022
:author: Teresa Killmond
:linkattrs:
:experimental:
:description: Manage cluster operations if your organization requires that privilege escalation take place through an external tool that integrates with Ansible.

If your organization requires that privilege escalation take place through an external tool that integrates with Ansible, and your ThoughtSpot installation is on RHEL, you must manage cluster operations in a certain way. Specifically, you must use Ansible when completing the following tasks:

* xref:rhel-install-ansible.adoc[Creating a cluster]
* xref:rhel-restore-ansible.adoc[Restoring a cluster]
* xref:rhel-start-stop-ansible.adoc#start[Starting a cluster]
* xref:rhel-start-stop-ansible.adoc#stop[Stopping a cluster]
* xref:rhel-upgrade-ansible.adoc[Upgrading a cluster]
* xref:rhel-add-node-ansible.adoc[Adding a node to a cluster]
* xref:rhel-delete-ansible.adoc[Deleting a cluster]

'''
> **Related information**
>
> * xref:rhel-prerequisites.adoc[RHEL and OEL prerequisites]
> * xref:rhel-ts-artifacts.adoc[ThoughtSpot deployment artifacts for RHEL and OEL]
> * xref:rhel-install-online.adoc[Online RHEL and OEL install]
> * xref:rhel-install-offline.adoc[Offline RHEL and OEL install]
> * xref:rhel-upgrade.adoc[RHEL and OEL upgrade]
> * xref:rhel-add-node.adoc[Add new nodes to clusters on RHEL or OEL]
> * xref:rhel-packages.adoc[Packages installed with RHEL and OEL]
