= Packages installed with ThoughtSpot for RHEL and OEL
:last_updated: 8/6/2021
:linkattrs:
:experimental:

To successfully deploy ThoughtSpot in your organization, you must have the following packages on each node of your ThoughtSpot cluster: <<yum,yum>>, <<pip,python 3>>, and <<r,R>>.
When the Ansible playbook runs, it automatically installs them.

ThoughtSpot works with the latest version of each package;
see the minimum supported version.

[#yum]
[#pip]
[#r]
[tabset]
====
Yum RPM packages for RHEL 7.8 and 7.9 and OEL 7.9;;
+
--
Download: link:{attachmentsdir}/yum-rpm-packages-rhel.csv[Yum RPM package list for RHEL 7.8 and 7.9 and OEL 7.9].

include::partial$/packages/yum-rpm-packages-rhel.adoc[]
--
Yum RPM packages for RHEL 8.1 - 8.5;;
+
--
Download: link:{attachmentsdir}/yum-rpm-packages-rhel-8.csv[Yum RPM package list for RHEL 8.1 - 8.5].

include::partial$/packages/yum-rpm-packages-rhel-8.adoc[]
--
Python 3 packages for 7.2.0 and earlier;;
+
--
Download: link:{attachmentsdir}/pip-rpm-packages.csv[Python RPM package list for 7.2.0 and earlier].

include::partial$/packages/pip-rpm-packages.adoc[]
--
Python 3 packages for 7.2.1 and later;;
+
--
Download: link:{attachmentsdir}/pip-rpm-packages-721.csv[Python RPM package list for 7.2.1 and later].

include::partial$/packages/pip-rpm-packages-721.adoc[]
--
R packages;;
+
--
Download: link:{attachmentsdir}/r-rpm-packages-rhel.csv[R RPM package list].

include::partial$/packages/r-rpm-packages-rhel.adoc[]
--
====
