= Configure SAML
:last_updated: 06/16/2021
:linkattrs:
:experimental:
:page-aliases: /app-integrate/SAML/configure-SAML-with-tscli.adoc, /admin/ts-cloud/authentication-integration.adoc, /admin/setup/configure-SAML-with-tscli.adoc

You can configure Security Assertion Markup Language (SAML) using ThoughtSpot's command line interface, tscli, or through the Admin Console.

include::partial$saml-intro.adoc[]

== Enable SAML Authentication

You need admin privileges to enable SAML SSO authentication. You can set up SAML through the shell on ThoughtSpot <<saml-configure-tscli, using a `tscli`-based configurator>>, or through the xref:admin-portal.adoc[].

include::partial$saml-prerequisites.adoc[]

[#saml-configure-tscli]
== Configure SAML using tscli

NOTE: The configuration persists across updates to newer releases of ThoughtSpot.

To set up SAML on ThoughtSpot for user authentication, follow these steps:

. Log in to the Linux shell using SSH.
. Execute the command to launch the interactive SAML configuration:
+
[source]
----
 tscli saml configure
----

. Complete the configurator prompts with the information and files you collected in <<prerequisites, Configuration prerequisites>>.
. When the configuration is complete, download ThoughtSpot's metadata file, `spring_saml_metadata.xml`. This file contains the public key you need if you want to encrypt your SAML assertions. To download this file, navigate to `https://<hostname-or-IP>/callosum/v1/saml/metadata`. The file automatically downloads.

[#saml-configure-idp]
=== Configure the IdP

To enable the IdP to recognize your host application and ThoughtSpot as a valid service provider, you must configure the IdP with required attributes and metadata. This includes the `spring_saml_metadata.xml` file that you downloaded in step 4 of <<saml-configure-tscli, Configure SAML using tscli>>.

ThoughtSpot supports SAML authentication with several identity and access management providers, such as https://developer.okta.com/docs/guides/build-sso-integration/saml2/before-you-begin/[Okta^], https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/configure-saml2-settings-azure-ad[Azure Active Directory^], https://docs.pingidentity.com/bundle/solution-guides/page/ozz1597769517562.html[PingFederate^], https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/configure-saml2-settings[Microsoft AD FS^], https://developers.onelogin.com/saml[Onelogin^] and so on. If you want to use one of these providers as your IdP, make sure you read the SAML configuration steps described in the Identity provider’s documentation site.

To determine if ThoughtSpot supports your preferred IdP, xref:support-contact.adoc[contact ThoughtSpot support].

Complete your configuration of the IdP using the IdP's SAML documentation. Upload or copy the contents of the `spring_saml_metadata.xml` to your IdP server. If you did not download the `spring_saml_metadata.xml` file, navigate to `\https://<your_ThoughtSpot_hostname-or-IP>/callosum/v1/saml/metadata`. The file automatically downloads.

After you configure the IdP, open a Web browser and go to the ThoughtSpot login page. It should now show the Single Sign On option.

include::partial$authentication-saml.adoc[]

[#saml-configure-2.0]
=== Configure SAML 2.0

When configuring SAML 2.0, ensure that you map the SAML user attributes to appropriate fields.

For example,

Onelogin::
You must map the SAML user’s _username_ to the _NameId_ attribute.
Okta::
You must map the `username` to `userPrincipalName`.

You must also map the `email` address of the user to the `mail` attribute.
Optionally, map the display name you would like to use to `displayName`.

WARNING: Starting in ThoughtSpot version 6.3.1, the mail field is mandatory, and cannot be empty. If your organization cannot meet this requirement, contact https://community.thoughtspot.com/customers/s/contactsupport[ThoughtSpot Support^] for help.

If your IdP does not allow you to import the IdP metadata XML file, you must map these values manually.
