= Upgrade or patch a single-node ThoughtSpot CentOS cluster
:last_updated: 01/10/2020
:linkattrs:
:page-aliases: /admin/system-admin/upgrade-a-cluster.adoc
:experimental:

Learn how to upgrade a single-node, ThoughtSpot-managed CentOS cluster to a new release, or patch a cluster to update services and allow for bug fixes.

'''
> **ThoughtSpot Training**
>
> * For best results in upgrading or patching ThoughtSpot, take the following ThoughtSpot U course: https://training.thoughtspot.com/create-upgrade-patch-a-thoughtspot-cluster/431164[Upgrade & Patch a Cluster^].
> * See other training resources at https://training.thoughtspot.com/[ThoughtSpot U^].

'''

NOTE: This article teaches you how to upgrade a single-node, ThoughtSpot-managed CentOS cluster. To upgrade multi-node clusters, or clusters that use customer-managed xref:rhel.adoc[RHEL], xref:rhel.adoc[OEL], or xref:al2.adoc[Amazon Linux 2], contact {support-url}.

== About cluster upgrades and patches
ThoughtSpot is installed or updated from a release tarball that contains the ThoughtSpot application (binaries and configuration), third-party software, and Operating System image.
Third party software includes licensed software components necessary for operation of the ThoughtSpot application.
These include Java, Boost C{pp} libraries, Google protocol buffers, and so on.

ThoughtSpot patches the Operating System at the time of upgrades.
Installation and upgrade use the same process, replacing the older OS image on a node by the new image delivered in the release tarball.

ThoughtSpot Support will contact you to schedule an update when a minor or major upgrade becomes available.

// is this last sentence still true

== View available releases

NOTE: This feature is now deprecated. You may not use it starting with the 7.2.1 release. For details, see xref:deprecation.adoc[Deprecation Announcements].

You can also view available releases from the Admin Console.
To view new releases, navigate to the Admin Console by clicking on the *Admin* tab from the top navigation bar.
Select *Upgrade* from the side navigation bar that appears.

The *Upgrade* page shows your cluster's current version, and any new releases that are available.

== Upgrade a cluster
To upgrade your cluster, follow these steps:
[cols="5,~",grid=none,frame=none]
|===
| &#10063; | <<upgrade-step-1,Step 1: Download the release files>>
| &#10063; | <<upgrade-step-2,Step 2: Check disk space>>
| &#10063; | <<upgrade-step-3,Step 3: Create a cluster snapshot and back it up on disk>>
| &#10063; | <<upgrade-step-4,Step 4: Check the cluster's health and integrity of provided software>>
| &#10063; | <<upgrade-step-5,Step 5: Upgrade the cluster>>
| &#10063; | <<upgrade-step-6,Step 6: Finalize installation>>
| &#10063; | <<upgrade-step-7,Step 7: Apply patches>>
|===

NOTE: If any commands return errors, warnings, or failures while you upgrade, contact {support-url}.

[#upgrade-step-1]
=== Step 1: Download the release files
Download the release, including any patches for the version you are installing, to your computer. Move the release files to a directory with sufficient space in your ThoughtSpot node.

WARNING: Do not put the release files in the `/home/admin` or `/home/thoughtspot` directories. You should put the release files in one of the bigger hard disks/volumes on one node in the cluster. Typically, this is `/export/sdb1/` for hardware appliances, VMware and GCP, `/export/sdc1/` for Azure, and `/export/xvdb1/` for AWS.

To download the release files, use one of two methods:

* Download the release files from Egnyte, and use `winscp` or a similar secure copy method to copy the downloaded release bundle from your Downloads folder to any path in the `/export` folder of your ThoughtSpot node that has enough space, at least 20 GB.
+
<<download-scp, To download using secure copy, follow these steps>>.

* If your ThoughtSpot cluster has internet access and allows access to Egnyte, you can download the files directly to any path in the `/export` folder of your ThoughtSpot node that has enough space, using a `wget` command.
+
<<download-wget,To download using wget, follow these steps>>.

[#download-scp]
==== Download using secure copy
. Navigate to [RELEASE LINK].
. Download the release content folder for the version you would like to upgrade to. This includes the release, any patches, the `Md5checksum`, and the `capture_cluster_information.sh` script. This script inventories a ThoughtSpot cluster for use in audit or recovery, if necessary.
. In your terminal application, log in to your ThoughtSpot node using `ssh`.
. Copy the downloaded release bundle from your Downloads folder to any path in the `/export` folder of your ThoughtSpot node that has enough space, using winscp or a similar secure copy method.

[#download-wget]
==== Download using wget
. In your terminal application, log in to your ThoughtSpot node using `ssh`.
. Navigate to any path in the `/export` folder of your ThoughtSpot node that has enough space.
. If your ThoughtSpot cluster has internet access and allows access to Egnyte, you can download the files directly to the node. Use the following `wget` command:
+
[source,bash]
----
 $ wget <EGNYTE RELEASE LINK THAT I WILL PROVIDE WHEN I HAVE IT> -c -O <release-bundle-name>
----

[#upgrade-step-2]
=== Step 2: Check disk space
. Check disk space by running `df -h`. `/tmp` needs at least 50 GB free for upgrades, `/export` needs at least 30 GB free, and you need at least 10% availability on every other filesystem, except for `/update`.
+
[source,bash]
----
 $ df -h
----
+
The output of this command shows all disks in the ThoughtSpot node and their availability, in percentage and in number of GB.

[#upgrade-step-3]
=== Step 3: Create a cluster snapshot and back it up on disk
. Take a manual snapshot of the cluster. For information on how to take a manual snapshot, refer to xref:snapshots.adoc#manual-snapshot[Work with snapshots]. Note that snapshot creation may take some time.

. Take a manual backup of the cluster. For information on how to take a manual backup, refer to xref:backup-manual.adoc[Create a manual backup]. Note that taking a backup may take some time.

[#upgrade-step-4]
=== Step 4: Check the cluster's health and integrity of provided software
. Run `tscli cluster status`. This tells you what version you are currently on, and ensures that the cluster is running and ready.
+
[source,bash]
----
 $ tscli cluster status
----
+
Make sure that the output includes `Cluster: RUNNING`, `Database: READY`, and `Search Engine: READY`, `PENDING`, `INDEXING`, or `UPDATING`. Make sure the output does NOT include any errors.

. Run `tscli cluster check` to ensure there are no component failures.
+
[source,bash]
----
 $ tscli cluster check
----
+
Make sure that the output for each component is `SUCCESS`.

. Run `./capture_cluster_information.sh`. This captures current information about your cluster in case {support-url} needs it for any purpose after the upgrade.
+
[source,bash]
----
 $ ./capture_cluster_information.sh
----

. Check the integrity of the release by running the `md5sum -c <checksum file name>` command. Replace `checksum file name` with the name of the checksum file in your release bundle. It will likely be in the format `\*.MD*.`
+
[source,bash]
----
 $ md5sum -c <checksum file name>
----
+
The output should be a list of filenames, followed by  `OK`.

. If `tscli cluster status`, `tscli cluster check`, or the `md5sum` command return any errors, warnings, or failures, contact {support-url} before you proceed with the upgrade.

[#upgrade-step-5]
=== Step 5: Upgrade the cluster
. Launch a screen session. Use screen to ensure that your installation does not stop if you lose network connectivity.
+
[source,bash]
----
 $ screen -S upgrade
----
. Run `tscli cluster update <release-number>.tar.gz`. This may take about one hour.
+
Note the following parameters:

`release-number`:: is the release number of your ThoughtSpot installation, such as 8.4.1.sw, 7.2.1, and so on.

. During the upgrade process, the node reboots. The node reboot logs you out of the node. Wait about 15 minutes before you `ssh` back in. If the `ssh` output says something similar to `Connection refused`, the node is still rebooting.

. If you run into an error during upgrade, and the upgrade fails, refer to <<error-recovery,Error recovery>>.  If the `HDFS fsimage check` returns `FAILURE`, refer to the <<fsimage,HDFS fsimage check error recovery>>.

. To see which step the upgrade is in, run `tscli cluster status --tail`. When the upgrade is complete, the output of this command says that the upgrade is complete.
+
[source,bash]
----
$ tscli cluster status --tail
----
+
NOTE: During the upgrade process, some services may temporarily be unavailable. The status of an update task in the `tscli cluster status --tail` command might be `FAILURE`. In this case, the installer will run the command repeatedly until the update task status is `SUCCESS. If an update task continues to fail, xref:support-contact.adoc[contact ThoughtSpot Support].

. The upgrade takes about 1.5 hours to complete.

[#upgrade-step-6]
=== Step 6: Finalize installation
. To check that the cluster is ready, run `tscli cluster status`.
+
[source,bash]
----
 $ tscli cluster status
----
+
Ensure that the `DATABASE` and `SEARCH ENGINE` fields in the `tscli cluster status` command output show `READY`, and that the output reports no errors. It may take up to an hour for the `DATABASE` and `SEARCH ENGINE` fields to show `READY`, depending on how much data you have.

. Run `tscli cluster check` to ensure there are no component failures.
+
[source,bash]
----
 $ tscli cluster check
----
+
Make sure that the output for each component is `SUCCESS`.

. Sign in to the ThoughtSpot application on your browser. Make sure you sign in to ThoughtSpot in a new tab.

. Verify the release version in the UI matches the version you upgraded to:

.. Navigate to *Admin > Cluster*.
.. In the *Cluster details* panel, confirm that the *Release* version matches the version you upgraded to.

[#upgrade-step-7]
=== Step 7: Apply patches
Your release bundle may include patches for the ThoughtSpot application. These patches update services and provide bug fixes. If your release bundle includes any patches, <<patch,apply the patches>>.

[#patch]
== Patch a cluster
Patching a cluster updates the ThoughtSpot services and allows for bug fixes. The process is similar to upgrading a cluster. To patch your cluster, follow these steps:
[cols="5,~",grid=none,frame=none]
|===
| &#10063; | <<patch-step-1,Step 1: Obtain cluster patch>>
| &#10063; | <<patch-step-2,Step 2: Verify patch integrity>>
| &#10063; | <<patch-step-3,Step 3: Apply the patch to the cluster>>
| &#10063; | <<patch-step-4,Step 4: Finalize installation>>
|===

[#patch-step-1]
=== Step 1: Obtain cluster patch
Download the patch or patches for the version you are running, and move it to a folder in your ThoughtSpot node. If you just upgraded to a new version, the release bundle you downloaded and copied to your ThoughtSpot node should contain the patches you need to apply.

WARNING: Do not put the patch files in the `/home/admin` or `/home/thoughtspot` directories. You should put the patch files in one of the bigger hard disks/volumes on one node in the cluster. Typically, this is `/export/sdb1/` for hardware appliances, VMware and GCP, `/export/sdc1/` for Azure, and `/export/xvdb1/` for AWS.

To download the patch files, use one of two methods:

* Download the patch files from Egnyte, and use `winscp` or a similar secure copy method to copy the downloaded patch bundle from your Downloads folder to any path in the `/export` folder of your ThoughtSpot node that has enough space.
+
<<download-scp-patch, To download using secure copy, follow these steps>>.

* If your ThoughtSpot cluster has internet access and allows access to Egnyte, you can download the files directly to any path in the `/export` folder of your ThoughtSpot node that has enough space, using a `wget` command.
+
<<download-wget-patch,To download using wget, follow these steps>>.

[#download-scp-patch]
==== Download using secure copy
. Navigate to [PATCH LINK].
. Download the patch folder for the version you would like to upgrade to. This includes the patches, the `Md5checksum`, and the `capture_cluster_information.sh` script. This script inventories a ThoughtSpot cluster for use in audit or recovery, if necessary.
. In your terminal application, log in to your ThoughtSpot node using `ssh`.
. Copy the downloaded patch bundle from your Downloads folder to any path in the `/export` folder of your ThoughtSpot node that has enough space, using winscp or a similar secure copy method.

[#download-wget-patch]
==== Download using wget
. In your terminal application, log in to your ThoughtSpot node using `ssh`.
. Navigate to any path in the `/export` folder of your ThoughtSpot node that has enough space.
. If your ThoughtSpot cluster has internet access and allows access to Egnyte, you can download the patch files directly to the node. Use the following `wget` command:
+
[source,bash]
----
 $ wget <EGNYTE PATCH LINK THAT I WILL PROVIDE WHEN I HAVE IT> -c -O <patch-bundle-name>
----

[#patch-step-2]
=== Step 2: Verify integrity of patch files
To verify the integrity of the patch files, check the checksum for each patch, as explained in step 4 of <<upgrade-step-4,Step 4: Check the cluster's health and integrity of provided software>>.

[#patch-step-3]
=== Step 3: Apply the patch to the cluster
Run `tscli patch apply <patch-name>` for each patch, one file at a time.
[source,bash]
----
 $ tscli patch apply <patch-name>
----
The patch process for each patch takes about 10 minutes. Once a patch has been applied successfully, you can proceed with the next patch immediately, without waiting for any services to restart and without carrying out any extra checks.

[#patch-step-4]
=== Step 4: Finalize installation
Ensure that ThoughtSpot applied the patches successfully by running the following commands.

. Ensure that the new patches you applied appear in the `tscli patch ls` output.
+
[source,bash]
----
 $ tscli patch ls
----

. To check that the cluster is ready, run `tscli cluster status`.
+
[source,bash]
----
 $ tscli cluster status
----
+
Ensure that the `DATABASE` and `SEARCH ENGINE` fields in the `tscli cluster status` command output show `READY`, and that the output reports no errors. It may take up to an hour for the `DATABASE` and `SEARCH ENGINE` fields to show `READY`, depending on how much data you have.

. Run `tscli cluster check` to ensure there are no component failures.
+
[source,bash]
----
 $ tscli cluster check
----
+
Make sure that the output for each component is `SUCCESS`.

[#error-recovery]
== Error recovery

[#fsimage]
=== HDFS fsimage check failure
During the upgrade process, after you run `tscli cluster update <filename>`, the `HDFS fsimage check` may return `FAILURE`.  If this happens, there is an issue with the DNS resolution.

. Add the cluster hostname to `/etc/hosts`.

. Try to resume the upgrade with the following command:
+
[source,bash]
----
 $ tscli cluster resume-update
----

. If the `HDFS fsimage check` fails again, contact {support-url}.

[#tscli-cluster-update]
=== Upgrade failure during tscli cluster update
During the upgrade process, after you run `tscli cluster update <filename>`, the upgrade may fail with a message similar to `Update failed for cluster <cluster-name>`.

. Try to resume the upgrade with the following command:
+
[source,bash]
----
 $ tscli cluster resume-update
----
. If the `resume-update` command does not work, and you see an error you have fixed with the help of {support-url} before, make a note of it and fix the error in the same way that {support-url} did, and run `tscli cluster resume-update` again. Do *NOT* try to fix any errors that you have not fixed with {support-url} in previous upgrades.
. If the upgrade fails again, contact {support-url}.