= Upgrade or patch a cluster
:last_updated: 01/10/2020
:linkattrs:
:page-aliases: /admin/system-admin/upgrade-a-cluster.adoc
:experimental:

Learn how to upgrade a single-node, ThoughtSpot-managed CentOS cluster to a new release, or patch a cluster to update services and allow for bug fixes.

'''
> **ThoughtSpot Training**
>
> * For best results in upgrading or patching ThoughtSpot, take the following ThoughtSpot U course: https://training.thoughtspot.com/create-upgrade-patch-a-thoughtspot-cluster/431164[Upgrade & Patch a Cluster^].
> * See other training resources at https://training.thoughtspot.com/[ThoughtSpot U^].

'''

NOTE: This article teaches you how to upgrade a single-node, ThoughtSpot-managed CentOS cluster. To upgrade multi-node clusters, or clusters that use customer-managed xref:rhel.adoc[RHEL], xref:rhel.adoc[OEL], or xref:al2.adoc[Amazon Linux 2], contact {support-url}.

== About cluster upgrades and patches
ThoughtSpot is installed or updated from a release tarball that contains the ThoughtSpot application (binaries and configuration), third-party software, and Operating System image.
Third party software includes licensed software components necessary for operation of the ThoughtSpot application.
These include Java, Boost C{pp} libraries, Google protocol buffers, and so on.

ThoughtSpot patches the Operating System at the time of upgrades.
Installation and upgrade use the same process, replacing the older OS image on a node by the new image delivered in the release tarball.

ThoughtSpot Support will contact you to schedule an update when a minor or major upgrade becomes available.

== View available releases

NOTE: This feature is now deprecated. You may not use it starting with the 7.2.1 release. For details, see xref:deprecation.adoc[Deprecation Announcements].

You can also view available releases from the Admin Console.
To view new releases, navigate to the Admin Console by clicking on the *Admin* tab from the top navigation bar.
Select *Upgrade* from the side navigation bar that appears.

The *Upgrade* page shows your cluster's current version, and any new releases that are available.

== Upgrade a cluster
To upgrade your cluster, follow these steps:
[cols="5,~",grid=none,frame=none]
|===
| &#10063; | <<upgrade-step-1,Step 1: Check cluster health>>
| &#10063; | <<upgrade-step-2,Step 2: Download the release>>
| &#10063; | <<upgrade-step-3,Step 3: Upgrade the cluster>>
| &#10063; | <<upgrade-step-4,Step 4: Finalize installation>>
|===

NOTE: If any commands return errors, warnings, or failures while you upgrade, contact {support-url}.

[#upgrade-step-1]
=== Step 1: Check cluster health
. SSH into your cluster.
Run `ssh admin@<ThoughtSpotnodeIP>`.
+
Replace `ThoughtSpotnodeIP` with your specific network information.
+
[source,bash]
----
 $ ssh admin@<ThoughtSpotnodeIP>
----

. Run `tscli cluster status`. This tells you what version you are currently on, and ensures that the cluster is running and ready.
+
[source,bash]
----
 $ tscli cluster status
----
+
Make sure that the output says `Cluster: RUNNING`, `Database: READY`, and `Search Engine: READY`.

. Run `tscli cluster check` to ensure there are no component failures.
+
[source,bash]
----
 $ tscli cluster check
----
+
Make sure that the output for each component is `SUCCESS`.

. If `tscli cluster status` or `tscli cluster check` return any errors, warnings, or failures, contact {support-url} before you proceed with the upgrade.

[#upgrade-step-2]
=== Step 2: Download the release
You can download the release and move it to the correct directory in one of two ways:

* using the <<fileserver,tscli fileserver>> command
* using the <<egnyte,Egnyte link and scp command>>

[#fileserver]
==== Download the release using tscli
Use `tscli fileserver download-release` to download the release bundle.

// should they cd to the specific export directory here?

. First, ensure that you already xref:tscli-command-ref.adoc#tscli-fileserver[configured the fileserver] by running `tscli fileserver show-config`.
+
[source,bash]
----
tscli fileserver show-config
----
If the fileserver is already configured, the output is `Fileserver is configured`.

.. If the fileserver is *not* configured, xref:tscli-command-ref.adoc#tscli-fileserver[configure the fileserver] by running `tscli fileserver configure --user USER --password PASSWORD`.
+
[source,bash]
----
tscli fileserver configure --user USER --password PASSWORD
----

. Download the release from the fileserver by running `tscli fileserver download-release <release-number> --user <username> --out <release-location>`.
+
[source,bash]
----
$ tscli fileserver download-release <release-number> --user <username> --out <release-location>
----
+
Note the following parameters:
+
`release-number`:: is the release number of your ThoughtSpot instance, such as 5.3, 5.3.1, 6.0, and so on.
`username`:: is the username for the fileserver that you set up earlier, when configuring the fileserver.
`release-location`:: is the location path of the release bundle on your local machine. For example, `/export/sdb1/TS_TASKS/install/6.0.tar.gz`.

[#egnyte]
==== Download the release using the Egnyte link
// should they cd to the specific export directory here?
. On a machine that can also access your ThoughtSpot cluster, navigate to [LINK].
. Select *Download*. [i'm not sure what this actually looks like on egnyte]
. Copy the downloaded release bundle to a specific path in the `/export` folder.
+
You must copy the bundle to a different path in the `/export` folder, depending on your deployment platform:
+
[#platform-export-path]
--
SMC, Dell, VMware, and GCP:: `/export/sdb1/TS_SRE_TASKS`
AWS:: `/export/xvdb1/TS_SRE_TASKS`
Azure:: `/export/sdc1/TS_SRE_TASKS`
--
+
Run `scp <release-number>.tar.gz admin@<hostname>:/export/<path>/TS_TASKS/install/<file-name>`.
+
[source,bash]
----
$ scp <release-number>.tar.gz admin@<hostname>:/export/<path>/TS_TASKS/install/<file-name>
----
+
Note the following parameters:
+
`release-number`:: is the release number of your ThoughtSpot instance, such as 5.3, 5.3.1, 6.0, and so on.
`hostname`:: is your specific hostname.
`path`:: is the path within the export folder. This differs based on your deployment platform; refer to <<platform-export-path, list of paths>>.
`file-name`:: is the name of the tarball file on your local machine.

NOTE: You can use another secure copy method, if you prefer a method other than the `scp` command.

[#upgrade-step-3]
=== Step 3: Upgrade the cluster
. Run `tscli cluster update <release-number>.tar.gz`.
+
Note the following parameters:

`release-number`:: is the release number of your ThoughtSpot installation, such as `6.0`, `5.3`, `5.3.1`, and so on.

. The nodes reboot one by one. Wait about 15 minutes before you log back in.

. To see which step the upgrade is in, run `tscli cluster status --tail`.
+
[source,bash]
----
$ tscli cluster status --tail
----
+
NOTE: During the upgrade process, some services may temporarily be unavailable. Their status in the `tscli cluster status --tail` command might be `FAILURE`. The service should return to `SUCCESS` as the upgrade continues. If a service continues to fail, xref:support-contact.adoc[contact ThoughtSpot Support].

. The upgrade takes about 1.5 hours to complete, including the objects upgrader.

[#upgrade-step-4]
=== Finalize installation
. After the upgrade completes, log out of the shell.
+
[source,bash]
----
$ logout
----

. `SSH` back into the cluster.
Run `ssh admin@<nodeIP>`.
+
Replace `nodeIP` with your specific network information.
+
[source,bash]
----
 $ ssh admin@<nodeIP>
----

. To check that the cluster is ready, run `tscli cluster status`.
+
[source,bash]
----
 $ tscli cluster status
----
+
Ensure that the `DATABASE` and `SEARCH ENGINE` fields in the `tscli cluster status` command show `READY`.

. Sign into the ThoughtSpot application on your browser.

== Patch a cluster
To patch your cluster, follow these steps:
[cols="5,~",grid=none,frame=none]
|===
| &#10063; | <<patch-step-1,Step 1: Obtain cluster patch>>
| &#10063; | <<patch-step-2,Step 2: Verify patch integrity>>
| &#10063; | <<patch-step-3,Step 3: Apply the patch to the cluster>>
| &#10063; | <<patch-step-4,Step 4: Finalize installation>>
|===

[#patch-step-1]
=== Obtain cluster patch
ThoughtSpot Support must provide you with the correct patch to apply. Do not apply any other patches. xref:support-contact.adoc[] to obtain the correct cluster patch.

After ThoughtSpot Support supplies you with the patch, copy it to your cluster.

[#patch-step-2]
=== Step 2: Verify patch integrity
To verify the integrity of the patch file, check the checksum.

Run `md5sum -c <patch-name>.tar.gz.MD5checksum`.

[source,bash]
----
 $ md5sum -c <patch-name>.tar.gz.MD5checksum
----

Your output says `ok` if you have the correct release.

[#patch-step-3]
=== Step 3: Apply the patch to the cluster
Run `tscli patch apply <patch-name>`.
[source,bash]
----
 $ tscli patch apply <patch-name
----
The patch process takes about 10 minutes.

[#patch-step-4]
=== Step 4: Finalize installation
Ensure that ThoughtSpot applied the patch successfully.

Run `tscli patch ls` and look for the new patch name.

[source,bash]
----
 $ tscli patch ls
----