[#upload-csv]
=== Upload a flat data file (CSV)

To upload a CSV file, follow these steps:

. Select *Data* in the top navigation bar.

. Select *Utilities* in the side navigation bar.

. Select *Upload CSV*.
+
Alternatively, navigate to step one of Setup, and click *upload CSV*.
. Upload the CSV or Excel file using one of these options:
** Click *Browse your files* and select the file.
** Drag and drop the file into the drop area.

. Answer the question *Are the column names already defined in the file header?*
. Answer the question *How are fields separated?*
. Click *Next.*
. If column names are missing, click the column header to add column names that describe the attributes or measures in the columns.
+
You can also change existing names to a simpler or more human-readable format.
. Click *Next*.
. Review the automatically-generated data types for each column, and make necessary changes.
+
There are eight data types: *Integer*, *Large Integer*, *Decimal*, *Text*, *Date*, *Date_Time*, and *Time*.
. Click *Upload*.

NOTE: Users have an upload limit of one CSV file.

=== Replace a CSV file

To replace your uploaded CSV file, follow these steps:

. Select *Data* in the top navigation bar.

. Click on your current CSV file in the list of data sources.

. Select *Replace CSV* in the top right corner of your screen.

. Answer the question *Are the column names already defined in the file header?*
. Answer the question *Do you want to append to the existing data or overwrite it?* To add this data to your existing CSV file, choose *Append*. To create a new CSV file, choose *Overwrite*.
. Answer the question *How are fields separated?*
. Click *Next*.
. Preview your data and click *Upload*.