The latest release of ThoughtSpot Cloud contains several new and enhanced features.

* <<8-7-0-cl-first,For the First User>>
* <<8-7-0-cl-analyst,For the Analyst>>
* <<8-7-0-cl-business-user,For the Business User>>
* <<8-7-0-cl-data-engineer,For the Data Engineer>>
* <<8-7-0-cl-it-ops-engineer,For the IT Ops Engineer>>
* <<8-7-0-cl-developer,For the Developer>>

[#8-7-0-cl-first]
=== For the First User

Getting started with ThoughtSpot Cloud::
The first user on the account has to complete a series of steps before other people can start using ThoughtSpot with your organization's data.
For these instructions, see xref:ts-cloud-getting-started.adoc[Getting Started with ThoughtSpot Cloud].

[#8-7-0-cl-analyst]
=== For the Analyst

Customizable colors for heatmap and treemap charts::
You can now customize the colors used for heatmap and treemap charts. Prior to this release, the only available heatmap color was teal in various shades, and the only available treemap color was green in various shades. Now you can choose any color in your color palette. For more information, see xref:chart-heatmap.adoc[] and xref:chart-treemap.adoc[].

[#8-7-0-cl-business-user]
=== For the Business User

Choose sources limitation::
You can no longer select more than 100 data sources to search on when searching data. This maximum of 100 sources improves performance and limits timeouts due to the selection of too many sources.

Geo charts enhancements::
This release includes several enhancements to all geo charts:
+
--
* A new *map type* option that allows you to customize the display of the parts of the geo chart map that do not contain data. The new map type options are Light, Dark, Outdoors, Streets, Satellite, and Satellite Streets. The default is Light.
* Improved street-level mapping. This includes faster map loading, better clarity, and more granular details when you zoom in.
--
See xref:chart-geo.adoc[].

[#8-7-0-cl-data-engineer]
=== For the Data Engineer

[#8-7-0-cl-developer]
=== For the Developer

ThoughtSpot Everywhere:: For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].
