The latest release of ThoughtSpot Cloud contains several new and enhanced features.

* <<8-4-0-cl-first,For the First User>>
* <<8-4-0-cl-analyst,For the Analyst>>
* <<8-4-0-cl-business-user,For the Business User>>
* <<8-4-0-cl-data-engineer,For the Data Engineer>>
* <<8-4-0-cl-it-ops-engineer,For the IT Ops Engineer>>
* <<8-4-0-cl-developer,For the Developer>>

[#8-4-0-cl-first]
=== For the First User

Getting started with ThoughtSpot Cloud::
The first user on the account has to complete a series of steps before other people can start using ThoughtSpot with your organization's data.
For these instructions, see xref:ts-cloud-getting-started.adoc[Getting Started with ThoughtSpot Cloud].

[#8-4-0-cl-analyst]
=== For the Analyst

Liveboard and answer download footer::
This release introduces the ability for admins to specify a standard footer to add to all Liveboard and answer downloads. Use this functionality to add a confidentiality disclaimer, for example.
+
This feature is part of the xref:answer-experience-new.adoc[new answer experience] and the xref:liveboard-experience-new.adoc[new Liveboard experience]. If you are using the classic experiences, you cannot set a standard download footer. If you are using only the new answer experience, you can only set a standard download footer for answers, *_not_* Liveboards.
+
For more information, refer to xref:search-spotiq-settings.adoc[].

[#8-4-0-cl-business-user]
=== For the Business User

[#8-4-0-cl-data-engineer]
=== For the Data Engineer

[#8-4-0-cl-it-ops-engineer]
=== For the IT Ops Engineer

[#8-4-0-cl-developer]
=== For the Developer

ThoughtSpot Everywhere:: For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].
