The latest release of ThoughtSpot Cloud contains several new and enhanced features.

* <<8-6-0-cl-first,For the First User>>
* <<8-6-0-cl-analyst,For the Analyst>>
* <<8-6-0-cl-business-user,For the Business User>>
* <<8-6-0-cl-data-engineer,For the Data Engineer>>
* <<8-6-0-cl-it-ops-engineer,For the IT Ops Engineer>>
* <<8-6-0-cl-developer,For the Developer>>

[#8-6-0-cl-first]
=== For the First User

Getting started with ThoughtSpot Cloud::
The first user on the account has to complete a series of steps before other people can start using ThoughtSpot with your organization's data.
For these instructions, see xref:ts-cloud-getting-started.adoc[Getting Started with ThoughtSpot Cloud].

[#8-6-0-cl-analyst]
=== For the Analyst

New Liveboard experience::
The xref:liveboard-experience-new.adoc[new Liveboard experience] is now GA and on by default. It contains multiple new features and feature enhancements.
It is part of ThoughtSpot's move to a new stack.
To learn how to manage its enablement, refer to xref:liveboard-experience-new.adoc[].
+
The new Liveboard experience contains the following new features:

include::partial$new-liveboard-experience-features.adoc[]

include::partial$new-liveboard-experience-deprecations.adoc[]

TML import improvements::
You can now import xref:tml.adoc[TML] files that contain certain errors. During the import process, ThoughtSpot removes the part of the object that contains errors, and allows you to import the rest of the object. These errors include the following:
+
--
* Some Liveboard visualizations contain errors, but the overall Liveboard is valid: ThoughtSpot removes the visualizations that contain errors and imports the Liveboard.
* Some Liveboard filters contain errors, but the overall Liveboard is valid: ThoughtSpot removes the filters that contain errors and imports the Liveboard.
* Destination tables for some joins in a table do not exist, but the overall table is valid: ThoughtSpot removes the joins that do not have destination tables and imports the table.
--
+
Refer to xref:scriptability.adoc#migrate-object[Migrate an object].


[#8-6-0-cl-business-user]
=== For the Business User

[#8-6-0-cl-data-engineer]
=== For the Data Engineer

[#join-deletion]
Delete a join even if it has dependents::
You can now delete a join from the ThoughtSpot UI even if the join has dependents. This allows you to delete a join and create it again in the other direction, without invalidating or deleting any dependent objects.
+
Refer to xref:relationship-delete.adoc[].

[#8-6-0-cl-it-ops-engineer]
=== For the IT Ops Engineer

[#okta]
Okta authentication::

Okta authentication is now GA and on by default. In this release, ThoughtSpot switched to a new, industry-standard cloud authentication method through Okta. ThoughtSpot now powers its internal authentication with Okta, which is the industry-leading authentication platform. This change is internal and has no impact on customers. After we enable this feature by default, all user authentication will automatically use the internal Okta service.
+
This switch involves several external improvements to authentication, including security enhancements:

* Ability to map IDP attributes from the ThoughtSpot Admin Console (username, email, and display name).
* Account activation monitoring from the Users section of the Admin Console: if a user still needs to activate their account, administrators can see that information in the Users section and re-send their activation email.
* Only Okta interacts with your IDP. Your ThoughtSpot cluster does not directly interact with your IDP.
* Local users create their own password during activation. Administrators do not create the password prior to activation.

[#8-6-0-cl-developer]
=== For the Developer

ThoughtSpot Everywhere:: For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].
