The latest release of ThoughtSpot Cloud contains several new and enhanced features.

* <<8-7-0-cl-first,For the First User>>
* <<8-7-0-cl-analyst,For the Analyst>>
* <<8-7-0-cl-business-user,For the Business User>>
* <<8-7-0-cl-data-engineer,For the Data Engineer>>
* <<8-7-0-cl-it-ops-engineer,For the IT Ops Engineer>>
* <<8-7-0-cl-developer,For the Developer>>

[#8-7-0-cl-first]
=== For the First User

Getting started with ThoughtSpot Cloud::
The first user on the account has to complete a series of steps before other people can start using ThoughtSpot with your organization's data.
For these instructions, see xref:ts-cloud-getting-started.adoc[Getting Started with ThoughtSpot Cloud].

[#8-7-0-cl-analyst]
=== For the Analyst

[#8-7-0-cl-business-user]
=== For the Business User

Choose sources limitation::
You can no longer select more than 100 data sources to search on when searching data. This maximum of 100 sources improves performance and limits timeouts due to the selection of too many sources.

Support for OR in contains operator::
ThoughtSpot now offers the option to `OR` multiple `contains` clauses for the same attribute in a search, instead of combining them with `AND`, which is the default. For example, with the optional new `OR` behavior, `country name contains 'a' country name contains 'b'` returns results such as `Azerbaijan`, `Bahrain`, `North America`, and `Canada`. With the default `AND` behavior, that search returns `Azerbaijan` and `Bahrain`, but *_not_* `North America` or `Canada`.
+
To enable this feature, contact {support-url}.

[#8-7-0-cl-data-engineer]
=== For the Data Engineer

[#8-7-0-cl-developer]
=== For the Developer

ThoughtSpot Everywhere:: For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].
