The latest release of ThoughtSpot Cloud contains several new and enhanced features.

* <<9-3-0-cl-first,For the First User>>
* <<9-3-0-cl-analyst,For the Analyst>>
* <<9-3-0-cl-business-user,For the Business User>>
* <<9-3-0-cl-data-engineer,For the Data Engineer>>
* <<9-3-0-cl-it-ops-engineer,For the IT Ops Engineer>>
* <<9-3-0-cl-developer,For the Developer>>

[#9-3-0-cl-first]
=== For the First User

Getting started with ThoughtSpot Cloud::
The first user on the account has to complete a series of steps before other people can start using ThoughtSpot with your organization's data.
For these instructions, see xref:ts-cloud-getting-started.adoc[Getting Started with ThoughtSpot Cloud].

[#9-3-0-cl-analyst]
=== For the Analyst

Liveboard note tiles::

The Liveboard note tiles feature is now GA. Add notes to your Liveboards, so that viewers of your Liveboards can quickly understand how to use the data and visualizations you gathered. Note tiles can provide an overview of a Liveboard or visualization, company branding through images, definitions of terms used in the Liveboard, and so on. See xref:liveboard-note-tiles.adoc[Liveboard note tiles].

[#9-3-0-cl-business-user]
=== For the Business User

Liveboard cross filters::

Liveboard cross filters are now GA. Click on any data point in your Liveboard and easily filter the entire Liveboard by that value. For example, if you select *California* in a geo chart on your Liveboard, and then select *Filter*, all the other visualizations only show data from California. A visualization for *Total sales by city*, for example, would only show sales for cities in California. This feature is also called _brushing and linking_. For more information, see
xref:liveboard-filters.adoc#cross-filter[Liveboard filters].

Access the contextual menu on left click::

Accessing the contextual menu for visualization data points on left-click is now GA. Instead of right-clicking on a data point to include or exclude it, drill down on it, or show underlying data, now you can access the menu more easily, with a single left-click.

[#9-3-0-cl-data-engineer]
=== For the Data Engineer

[#9-3-0-cl-it-ops-engineer]
=== For the IT/Ops Engineer


[#9-3-0-cl-developer]
=== For the Developer

ThoughtSpot Everywhere:: For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].
