The latest release of ThoughtSpot Cloud contains several new and enhanced features.

* <<8-1-0-cl-first,For the First user>>
* <<8-1-0-cl-analyst,For the Analyst>>
* <<8-1-0-cl-business-user,For the Business User>>
* <<8-1-0-cl-data-engineer,For the Data Engineer>>
* <<8-1-0-cl-it-ops-engineer,For the IT Ops Engineer>>
* <<8-1-0-cl-developer,For the Developer>>

[#8-1-0-cl-first]
=== For the First User

Getting started with ThoughtSpot Cloud::
The first user on the account has to complete a series of steps before other people can start using ThoughtSpot with your organization's data.
For these instructions, see xref:ts-cloud-getting-started.adoc[Getting Started with ThoughtSpot Cloud].

[#8-1-0-cl-analyst]
=== For the Analyst

[#spotapps]
ServiceNow SpotApp::
SpotApps are ThoughtSpot's new out-of-the-box solution templates built for specific use cases and data sources. They are built on Blocks, which are pre-built pieces of code that are easy to download and implement directly from the product. This release introduces the ServiceNow SpotApp and Analytics Blocks. Analytics Blocks include pre-built Worksheet, Answer, and Liveboard Blocks.
+
The ServiceNow SpotApp mimics the ServiceNow data model. After you connect to your ServiceNow data in your cloud data warehouse, ThoughtSpot maps that data to SpotApp columns, and creates pre-built but still customizable worksheets, answers, and Liveboards, based on your ServiceNow data.
+
This feature is in beta and off by default. It is part of the <<data-tab,Data tab redesign>>, which is also in beta and off by default. To enable SpotApps and the Data tab redesign, contact {support-url}.

SQL-based views::
This release introduces beta support for SQL-based views. Users can create views based on SQL queries, and use those views as data sources. This type of view has the same functionality as a view based on searching your data.
+
This feature is in beta and off by default. To enable it, contact {support-url}.

[#data-tab]
Data tab redesign::
This release redesigns the *Data* section of the product. To access this part of the product, select *Data* from the top navigation bar. The redesign introduces several new features, such as SQL-based views and SpotApps, and makes the UI more intuitive.
+
This feature is in beta and off by default. To enable it,  contact {support-url}.

[#8-1-0-cl-business-user]
=== For the Business User

Reset button for saved answers::
The reset button allows you to reset a saved answer to its last saved state after you edit it. This buttons appears to the right of the search bar in a saved answer, next to the *undo* and *redo* buttons. Note that the reset button is only available for saved answers.
+
The reset button is only available in the xref:answer-experience-new.adoc[new answer experience].

[#8-1-0-cl-data-engineer]
=== For the Data Engineer

[#connections-flow-data-portal]
New connection creation flow with data tab redesign::
If you have the new redesigned data tab enabled, you'll see the new Data Portal page. To start creating a connection, you click *Connections* and then click the connection type you want to create. Also with the new data tab enabled, you have the option to create a connection without selecting tables or columns. On the Data Portal page you can create a SQL-based view from a connection.

[#connections-redshift-oauth]
OAuth for Amazon Redshift::
Redshift connections now support OAuth. See xref:connections-redshift-oauth.adoc[Configure OAuth for a Redshift connection].

[#connections-azure-oauth]
OAuth for Microsoft Azure Synapse::
Synapse connections now support OAuth. See xref:connections-synapse-oauth.adoc[Configure OAuth for an Azure Synapse connection].

[#aws-region-japan]
New Japan cloud region::
ThoughtSpot Cloud is now available in Japan. See xref:ts-cloud-requirements-support.adoc[ThoughtSpot Cloud requirements and support]. 

[#8-1-0-cl-it-ops-engineer]
=== For the IT Ops Engineer

[#okta]
Okta authentication::

In this release, ThoughtSpot switched to a new, industry-standard cloud authentication method through Okta. Okta is now ThoughtSpot’s internal authentication service. This change is internal and has no impact on customers. After we enable this feature by default, all user authentication will automatically use the internal Okta service.
+
This new Okta authentication feature is in *Beta*, and off by default. To enable it, contact {support-url}.
+
This switch involves several external improvements to authentication, including security enhancements:
+
* Ability to map IDP attributes from the ThoughtSpot Admin Console (username, email, and display name)
* Account activation monitoring from the Users section of the Admin Console: if a user still needs to activate their account, you can see that information in the Users section and re-send their activation email
* Only Okta interacts with your IDP. Your ThoughtSpot cluster does not directly interact with your IDP.
* Local users create their own password during activation. Administrators do not create the password prior to activation.

[#encryption-at-rest]
Encryption at rest::
ThoughtSpot provides advanced data encryption at rest (EAR) that allows for granular user and folder level controls for encrypting your persistent data. EAR is currently a beta feature. To enable EAR in your environment, contact {support-url}.

[#8-1-0-cl-developer]
=== For the Developer

ThoughtSpot Everywhere:: For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].
