The latest release of ThoughtSpot Cloud contains several new and enhanced features.

* <<january-cloud-2022-first,For the First user>>
* <<january-cloud-2022-analyst,For the Analyst>>
* <<january-cloud-2022-business-user,For the Business User>>
* <<january-cloud-2022-data-engineer,For the Data Engineer>>
* <<january-cloud-2022-it-ops-engineer,For the IT Ops Engineer>>
* <<january-cloud-2022-developer,For the Developer>>

[#january-cloud-2022-first]
=== For the First User

Getting started with ThoughtSpot Cloud::
The first user on the account has to complete a series of steps before other people can start using ThoughtSpot with your organization's data.
For these instructions, see xref:ts-cloud-getting-started.adoc[Getting Started with ThoughtSpot Cloud].

[#january-cloud-2022-analyst]
=== For the Analyst

New answer experience::
The xref:answer-experience-new.adoc[new answer experience] is now GA and on by default. The new answer experience contains the following features:
include::partial$new-answer-experience-features.adoc[]

include::partial$new-answer-experience-deprecations.adoc[]

[#january-cloud-2022-business-user]
=== For the Business User

[#workspace-one]
Support for VMware Workspace One::
ThoughtSpot now supports use of the VMware Workspace One browser for the ThoughtSpot Mobile App. ThoughtSpot supports all versions of VMware Workspace One.

[#auto-select-data-source]
Auto-select search data source for new users::
When a new user uses xref:search-data.adoc[Search Data], ThoughtSpot intelligently selects a data source for them to search on. ThoughtSpot chooses the most popular data source in the cluster that the user has access to. This allows users to begin to search data easily, without looking through all the existing data sources on their cluster.

[#eureka-japanese]
Support for searching answers in Japanese [.badge.badge-update]#Beta#::
ThoughtSpot now supports Search Answers in Japanese.
+
This feature is in beta and on by default.

[#january-cloud-2022-data-engineer]
=== For the Data Engineer


[#january-cloud-2022-it-ops-engineer]
=== For the IT Ops Engineer

[#vpn]
OpenVPN support for Snowflake on Azure connections::
ThoughtSpot now supports secure access from ThoughtSpot Cloud to your data in Snowflake on Azure, through your OpenVPN server.
ThoughtSpot supports the following OpenVPN server implementations:

* https://openvpn.net/community-downloads/[OpenVPN Community Edition^]
* https://docs.microsoft.com/en-us/azure/vpn-gateway/vpn-gateway-howto-openvpn-clients[Azure VPN^]
* https://docs.aws.amazon.com/vpn/latest/clientvpn-admin/what-is.html[AWS Client VPN^]

To learn how to configure a VPN connection for your Snowflake on Azure connection, refer to xref:connections-synapse-open-vpn.adoc[OpenVPN for Azure Synapse and Snowflake on Azure].

[#encryption-at-rest]
Encryption at rest::
ThoughtSpot provides advanced data encryption at rest (EAR) that allows for granular user and folder level controls for encrypting your persistent data. EAR is currently a beta feature. To enable EAR in your environment, https://community.thoughtspot.com/customers/s/contactsupport[contact ThoughtSpot Support^].

[#january-cloud-2022-developer]
=== For the Developer

ThoughtSpot Everywhere:: For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].
