The latest release of ThoughtSpot Cloud contains several new and enhanced features.

* <<8-7-0-cl-first,For the First User>>
* <<8-7-0-cl-analyst,For the Analyst>>
* <<8-7-0-cl-business-user,For the Business User>>
* <<8-7-0-cl-data-engineer,For the Data Engineer>>
* <<8-7-0-cl-it-ops-engineer,For the IT Ops Engineer>>
* <<8-7-0-cl-developer,For the Developer>>

[#8-7-0-cl-first]
=== For the First User

Getting started with ThoughtSpot Cloud::
The first user on the account has to complete a series of steps before other people can start using ThoughtSpot with your organization's data.
For these instructions, see xref:ts-cloud-getting-started.adoc[Getting Started with ThoughtSpot Cloud].

[#8-7-0-cl-analyst]
=== For the Analyst

Customizable colors for heatmap and treemap charts::
You can now customize the colors used for heatmap and treemap charts. Prior to this release, the only available heatmap color was teal in various shades, and the only available treemap color was green in various shades. Now you can choose any color in your color palette. For more information, see xref:chart-heatmap.adoc[] and xref:chart-treemap.adoc[].

Liveboard tabs::
ThoughtSpot now supports separating Liveboards into multiple tabs. This allows you to group specific visualizations together within a Liveboard. For example, you may have a *Sales* Liveboard with different visualizations for each region you sell in. You can create tabs for each region, such as *Sales -- East* and *Sales -- West*, and move the visualizations for each region to the relevant tab. For more information, refer to xref:liveboard-tabs.adoc[Liveboard tabs].

[#8-7-0-cl-business-user]
=== For the Business User

Choose sources limitation::
You can no longer select more than 100 data sources to search on when searching data. This maximum of 100 sources improves performance and limits timeouts due to the selection of too many sources.

Support for OR in contains operator::
ThoughtSpot now offers the option to `OR` multiple `contains` clauses for the same attribute in a search, instead of combining them with `AND`, which is the default. For example, with the optional new `OR` behavior, `country name contains 'a' country name contains 'b'` returns results such as `Azerbaijan`, `Bahrain`, `North America`, and `Canada`. With the default `AND` behavior, that search returns `Azerbaijan` and `Bahrain`, but *_not_* `North America` or `Canada`.
+
To enable this feature, contact {support-url}.

Geo charts enhancements::
This release includes several enhancements to all geo charts:
+
--
* Improved map quality: This includes faster map loading, better clarity, and more granular details down to the street level when you zoom in. This applies to background maps (the parts of the map with no data) as well.
* A new *map type* option that allows you to customize the display of the parts of the geo chart map that do not contain data. The new map type options are Light, Dark, Outdoors, Streets, Satellite, and Satellite Streets. The default is Light.

--
See xref:chart-geo.adoc[].

[#8-7-0-cl-data-engineer]
=== For the Data Engineer

[#8-7-0-cl-developer]
=== For the Developer

ThoughtSpot Everywhere:: For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].
