The latest release of ThoughtSpot Cloud contains several new and enhanced features.

* <<8-9-0-cl-first,For the First User>>
* <<8-9-0-cl-analyst,For the Analyst>>
* <<8-9-0-cl-business-user,For the Business User>>
* <<8-9-0-cl-data-engineer,For the Data Engineer>>
* <<8-9-0-cl-it-ops-engineer,For the IT Ops Engineer>>
* <<8-9-0-cl-developer,For the Developer>>

[#8-9-0-cl-first]
=== For the First User

Getting started with ThoughtSpot Cloud::
The first user on the account has to complete a series of steps before other people can start using ThoughtSpot with your organization's data.
For these instructions, see xref:ts-cloud-getting-started.adoc[Getting Started with ThoughtSpot Cloud].

[#8-9-0-cl-analyst]
=== For the Analyst







[#8-9-0-cl-business-user]
=== For the Business User

Discoverable answers and Liveboards:: The discoverable answers and Liveboards feature is now GA and on by default. You can now make content easily available to your team members when you save or share an answer or Liveboard. Use the *Make this [answer | Liveboard] discoverable* checkbox that appears when you save or share an answer or Liveboard to grant _view_ access to your teammates. Any user who has access to the underlying data source (worksheet, table, view), and is part of the same user group as the author of the content, will be able to  discover and access the answer or Liveboard in *Search Answers*. Note that discoverable answers and Liveboards you have viewed appear on your home page, but not under the **Answers** or **Liveboards** tabs.
+
Select this checkbox to publish your content in the list of relevant results when a teammate uses the *Search Answers* feature, or de-select to keep your content private.

[#8-9-0-cl-data-engineer]
=== For the Data Engineer



[#8-9-0-cl-it-ops-engineer]
=== For the IT/Ops Engineer



[#8-9-0-cl-developer]
=== For the Developer

ThoughtSpot Everywhere:: For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].
