The latest release of ThoughtSpot Cloud contains several new and enhanced features.

* <<8-10-0-cl-first,For the First User>>
* <<8-10-0-cl-analyst,For the Analyst>>
* <<8-10-0-cl-business-user,For the Business User>>
* <<8-10-0-cl-data-engineer,For the Data Engineer>>
* <<8-10-0-cl-it-ops-engineer,For the IT Ops Engineer>>
* <<8-10-0-cl-developer,For the Developer>>

[#8-10-0-cl-first]
=== For the First User

Getting started with ThoughtSpot Cloud::
The first user on the account has to complete a series of steps before other people can start using ThoughtSpot with your organization's data.
For these instructions, see xref:ts-cloud-getting-started.adoc[Getting Started with ThoughtSpot Cloud].

[#8-10-0-cl-analyst]
=== For the Analyst


[#8-10-0-cl-business-user]
=== For the Business User

ThoughtSpot Sync Salesforce connection::

ThoughtSpot Sync Salesforce connection is now GA and on by default. You can now sync data directly from an answer or custom SQL view to Salesforce. Using ThoughtSpot Sync, you can push insights directly to Salesforce, notify your teams, and view data in context. ThoughtSpot Sync automatically establishes a secure pipeline to the destination app and thus eliminates the need for building custom connectors. For more information, see xref:sync-salesforce.adoc[Sync data to Salesforce].




[#8-10-0-cl-data-engineer]
=== For the Data Engineer


[#8-10-0-cl-it-ops-engineer]
=== For the IT/Ops Engineer

Multiple AWS PrivateLinks::

ThoughtSpot now supports multiple AWS PrivateLinks in your environment, using any combination of the cloud data warehouses that ThoughtSpot supports for PrivateLink. If you have data in multiple cloud data warehouses that needs an additional layer of security and network reliability, you can set up an AWS PrivateLink between each CDW, for a maximum of five PrivateLinks.
+
For more information, see xref:connections-private-link-intro.adoc[].

[#8-10-0-cl-developer]
=== For the Developer

ThoughtSpot Everywhere:: For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].
