The latest release of ThoughtSpot Cloud contains several new and enhanced features.

* <<9-2-0-cl-first,For the First User>>
* <<9-2-0-cl-analyst,For the Analyst>>
* <<9-2-0-cl-business-user,For the Business User>>
* <<9-2-0-cl-data-engineer,For the Data Engineer>>
* <<9-2-0-cl-it-ops-engineer,For the IT Ops Engineer>>
* <<9-2-0-cl-developer,For the Developer>>

[#9-2-0-cl-first]
=== For the First User

Getting started with ThoughtSpot Cloud::
The first user on the account has to complete a series of steps before other people can start using ThoughtSpot with your organization's data.
For these instructions, see xref:ts-cloud-getting-started.adoc[Getting Started with ThoughtSpot Cloud].

[#9-2-0-cl-analyst]
=== For the Analyst

Liveboard note tiles [.badge.badge-early-access-relnotes]#Early Access#::

Add notes to your Liveboards, so that viewers of your Liveboards can quickly understand how to use the data and visualizations you gathered. Note tiles can provide an overview of a Liveboard or visualization, definitions of terms used in the Liveboard, and so on. This feature must be enabled by your administrator. See xref:liveboard-note-tiles.adoc[Liveboard note tiles].

Search suggestions on columns with many values::
For any column with a high cardinality, which is defined as more than 100,000 unique column values, ThoughtSpot does not index the column if the index type is `DEFAULT`. This means the column values do not show up in search suggestions. Previously, this limit was 1 million unique column values. This change improves performance, and reduces index times and memory usage.
+
If you have existing columns with a cardinality between 100,000 and 1 million, and you use these columns' search suggestions regularly, ThoughtSpot will continue to index these columns.
+
For more information, see xref:data-modeling-index.adoc#high-cardinality[High cardinality and performance].

[#9-2-0-cl-business-user]
=== For the Business User

Parameters at the Answer level::

Any user can now create parameters at the Answer level to optimize their data inquiries. Use parameters to run different scenarios with adjustable values, without creating or modifying the constants in formulas for each new value. See xref:parameters-create.adoc#answer[Creating Answer parameters] and xref:parameters-use.adoc[Using parameters].

[#9-2-0-cl-data-engineer]
=== For the Data Engineer



[#9-2-0-cl-it-ops-engineer]
=== For the IT/Ops Engineer

[#9-2-0-cl-developer]
=== For the Developer

ThoughtSpot Everywhere:: For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].
