The latest release of ThoughtSpot Cloud contains several new and enhanced features.

* <<8-8-0-cl-first,For the First User>>
* <<8-8-0-cl-analyst,For the Analyst>>
* <<8-8-0-cl-business-user,For the Business User>>
* <<8-8-0-cl-data-engineer,For the Data Engineer>>
* <<8-8-0-cl-it-ops-engineer,For the IT Ops Engineer>>
* <<8-8-0-cl-developer,For the Developer>>

[#8-8-0-cl-first]
=== For the First User

Getting started with ThoughtSpot Cloud::
The first user on the account has to complete a series of steps before other people can start using ThoughtSpot with your organization's data.
For these instructions, see xref:ts-cloud-getting-started.adoc[Getting Started with ThoughtSpot Cloud].

[#8-8-0-cl-analyst]
=== For the Analyst

Formula function search bar::
The formula editor assistant now contains a search bar for formula functions. Use it to search for specific functions to include in your formula. Refer to xref:formula-add.adoc[].

year_name function::
The new `year_name` formula function returns the year in string format for a given date. This improves the behavior of formulas involving years when using a custom calendar with year values that are not in integer format. Refer to xref:formula-reference.adoc#year_name[Formula function reference].

[#8-8-0-cl-business-user]
=== For the Business User

Apply tags from the Home page::
You can now apply and edit tags on Liveboards and answers directly from the Home page, as well as from the *Answers* and *Liveboards* tabs. To edit a tag from the Home page, select the checkbox next to the name(s) of the answer(s) or Liveboard(s) you would like to tag and click the *Apply tags* button that appears. In the tags pop-up window, enter the name(s) of the tag(s) you would like to apply, or select the *x* icon to remove a tag, then click *Save*. For more information, see xref:thoughtspot-one-homepage.adoc#object-tag[Home page].

Show underlying data improvements::
We have made the following improvements to the *Show underlying data* feature:

* When you right-click on a table and select *Show underlying data*, ThoughtSpot displays only the visualized columns.
* You can now open the *Show underlying data* pop-up and click *Edit columns* to add or remove columns from your query.
* When you open the *Edit columns* pop-up, you can now search for column names using the search bar.
* The *Show underlying data* pop-up no longer disables columns by default. To disable columns from your query, click *Edit columns* and deselect the column name(s).

Improvements to German keywords::
This release improves the translated German keywords. See xref:keywords-de-DE.adoc[].

[#8-8-0-cl-data-engineer]
=== For the Data Engineer

[#join-deletion]
Delete joins that have dependents::
You can now delete a join from the ThoughtSpot UI even if the join has dependents. Deleting the join does not delete the dependents. This allows you to delete a join and create it again in the other direction, without invalidating or deleting any dependent objects.
+
Refer to xref:relationship-delete.adoc[].

[#8-8-0-cl-it-ops-engineer]
=== For the IT/Ops Engineer


[#8-8-0-cl-developer]
=== For the Developer

ThoughtSpot Everywhere:: For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].
