The latest release of ThoughtSpot Cloud contains several new and enhanced features.

* <<8-8-0-cl-first,For the First User>>
* <<8-8-0-cl-analyst,For the Analyst>>
* <<8-8-0-cl-business-user,For the Business User>>
* <<8-8-0-cl-data-engineer,For the Data Engineer>>
* <<8-8-0-cl-it-ops-engineer,For the IT Ops Engineer>>
* <<8-8-0-cl-developer,For the Developer>>

[#8-8-0-cl-first]
=== For the First User

Getting started with ThoughtSpot Cloud::
The first user on the account has to complete a series of steps before other people can start using ThoughtSpot with your organization's data.
For these instructions, see xref:ts-cloud-getting-started.adoc[Getting Started with ThoughtSpot Cloud].

[#8-8-0-cl-analyst]
=== For the Analyst


[#8-8-0-cl-business-user]
=== For the Business User

Apply tags from the Home page::
You can now apply and edit tags on Liveboards and answers directly from the Home page, as well as from the *Answers* and *Liveboards* tabs. To edit a tag from the Home page, select the checkbox next to the name(s) of the answer(s) or Liveboard(s) you would like to tag and click the *Apply tags* button that appears. In the tags pop-up window, enter the name(s) of the tag(s) you would like to apply, or select the *x* icon to remove a tag, then click *Save*. For more information, see xref:thoughtspot-one-homepage.adoc#object-tag[Home page].

[#8-8-0-cl-data-engineer]
=== For the Data Engineer

[#join-deletion]
Delete joins that have dependents::
You can now delete a join from the ThoughtSpot UI even if the join has dependents. Deleting the join does not delete the dependents. This allows you to delete a join and create it again in the other direction, without invalidating or deleting any dependent objects.
+
Refer to xref:relationship-delete.adoc[].

[#8-8-0-cl-it-ops-engineer]
=== For the IT/Ops Engineer


[#8-8-0-cl-developer]
=== For the Developer

ThoughtSpot Everywhere:: For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].
