The latest release of ThoughtSpot Cloud contains several new and enhanced features.

* <<8-3-0-cl-first,For the First User>>
* <<8-3-0-cl-analyst,For the Analyst>>
* <<8-3-0-cl-business-user,For the Business User>>
* <<8-3-0-cl-data-engineer,For the Data Engineer>>
* <<8-3-0-cl-it-ops-engineer,For the IT Ops Engineer>>
* <<8-3-0-cl-developer,For the Developer>>

[#8-3-0-cl-first]
=== For the First User

Getting started with ThoughtSpot Cloud::
The first user on the account has to complete a series of steps before other people can start using ThoughtSpot with your organization's data.
For these instructions, see xref:ts-cloud-getting-started.adoc[Getting Started with ThoughtSpot Cloud].

[#8-3-0-cl-analyst]
=== For the Analyst

Integration with dbt::
ThoughtSpot now offers an integration with dbt. You can provide your existing dbt models and automatically create worksheets in ThoughtSpot that you can use to perform searches on your data.
+
This feature is in beta and off by default. It is part of the <<data-tab,Data tab redesign>>, which is also in beta and off by default. To enable dbt integration and the Data tab redesign, contact {support-url}.

Jira Issue Management SpotApp::
This release introduces the Jira Issue Management SpotApp. ThoughtSpot maps your Jira data to SpotApp columns, and creates pre-built but still customizable worksheets, answers, and Liveboards, based on your data.
+
This feature is in beta and off by default. It is part of the <<data-tab,Data tab redesign>>, which is also in beta and off by default. To enable SpotApps and the Data tab redesign, contact {support-url}.

New SpotIQ experience::
The new SpotIQ experience is now available. The functionality remains the same, but we reorganized the UI to make it more intuitive. The new experience is on by default. You can manage your individual SpotIQ experience xref:user-profile.adoc[from your profile]. Note that the new SpotIQ experience is dependent on the xref:answer-experience-new.adoc[new answer experience]; to use the new SpotIQ experience, you must first enable the new answer experience. For more information, refer to xref:spotiq-custom.adoc[].

[#8-3-0-cl-business-user]
=== For the Business User

Recently viewed Liveboard and answer suggestions::
When you xref:search-answers.adoc[search across existing answers and Liveboards], ThoughtSpot now offers suggestions based on Liveboards and answers you recently viewed or interacted with, not just popular objects. This allows you to quickly return to an object you were working on or looking at in a previous session.

// make sure this is going to be GA

Open Search data in a new tab::
You can now open *Search data* in a new tab by right-clicking on the *Search data* option in the top navigation bar.

[#8-3-0-cl-data-engineer]
=== For the Data Engineer

OAuth for Databricks  [.badge.badge-new]#New!#::
Databricks connections now support OAuth. See xref:connections-databricks-oauth.adoc[Configure OAuth for a Databricks connection].

Oracle connections support Exadata and ADW [.badge.badge-new]#New!#::
In this release, the Oracle ADW connection is renamed to Oracle. Existing ADW connections continue to work. There are now two options: Cloud for ADW connections, and On Premise for Exadata or on-prem database connections. For details, see xref:connections-adw.adoc[Oracle].

Dremio connector [.badge.badge-new]#New!#::
In the release, Dremio is a new connection type. For details, see xref:connections-dremio.adoc[Dremio]. Dremio supports OAuth. For details, see xref:connections-dremio-oauth.adoc[Configure OAuth for a Dremio connection].




[#8-3-0-cl-it-ops-engineer]
=== For the IT Ops Engineer

[#encryption-at-rest-ga]
Advanced encryption at rest::
xref:security-thoughtspot-lifecycle.adoc#advanced-data-ear[Advanced data encryption at rest] is now GA. ThoughtSpot provides advanced data encryption at rest (EAR) that allows for granular user and folder level controls for encrypting your persistent data.
+
To enable Advanced EAR in your environment, contact {support-url}.

[#8-2-0-cl-developer]
=== For the Developer

ThoughtSpot Everywhere:: For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].
