The latest release of ThoughtSpot Cloud contains several new and enhanced features.

* <<8-4-0-cl-first,For the First User>>
* <<8-4-0-cl-analyst,For the Analyst>>
* <<8-4-0-cl-business-user,For the Business User>>
* <<8-4-0-cl-data-engineer,For the Data Engineer>>
* <<8-4-0-cl-it-ops-engineer,For the IT Ops Engineer>>
* <<8-4-0-cl-developer,For the Developer>>

[#8-4-0-cl-first]
=== For the First User

Getting started with ThoughtSpot Cloud::
The first user on the account has to complete a series of steps before other people can start using ThoughtSpot with your organization's data.
For these instructions, see xref:ts-cloud-getting-started.adoc[Getting Started with ThoughtSpot Cloud].

[#8-4-0-cl-analyst]
=== For the Analyst

SpotApps::
This release introduces several new SpotApps. ThoughtSpot maps your data from external applications, such as HubSpot, to SpotApp columns, and creates pre-built but still customizable worksheets, answers, and Liveboards, based on your data.
+
This release introduces the following new SpotApps:
+
--
* Okta
* Google Analytics
* HubSpot Marketing Email
* Snowflake Consumption Version 2
* Jira Sprint Management
--
+
The SpotApps feature is in beta and off by default. It is part of the <<data-tab,Data tab redesign>>, which is also in beta and off by default. To enable SpotApps and the Data tab redesign, contact {support-url}.

[#8-4-0-cl-business-user]
=== For the Business User

[#8-4-0-cl-data-engineer]
=== For the Data Engineer

[#8-4-0-cl-it-ops-engineer]
=== For the IT Ops Engineer

[#8-4-0-cl-developer]
=== For the Developer

ThoughtSpot Everywhere:: For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].
