The latest release of ThoughtSpot Cloud contains several new and enhanced features.

* <<8-5-0-cl-first,For the First User>>
* <<8-5-0-cl-analyst,For the Analyst>>
* <<8-5-0-cl-business-user,For the Business User>>
* <<8-5-0-cl-data-engineer,For the Data Engineer>>
* <<8-5-0-cl-it-ops-engineer,For the IT Ops Engineer>>
* <<8-5-0-cl-developer,For the Developer>>

[#8-5-0-cl-first]
=== For the First User

Getting started with ThoughtSpot Cloud::
The first user on the account has to complete a series of steps before other people can start using ThoughtSpot with your organization's data.
For these instructions, see xref:ts-cloud-getting-started.adoc[Getting Started with ThoughtSpot Cloud].

[#8-5-0-cl-analyst]
=== For the Analyst

Conditional and number formatting for downloaded tables::
When you download a table in `XLSX` format, the downloaded table now shows the same conditional and number formatting as the table in ThoughtSpot. Refer to xref:search-download.adoc#table-formatting[Download your search].

[#8-5-0-cl-business-user]
=== For the Business User

Threshold-based alerts for KPI charts [.badge.badge-update]#Beta#::
You can now use the Monitor feature to receive alerts when your KPI satisfies a given threshold condition. For example, create a condition to receive an alert when your Sales KPI becomes `greater than 200,000`, or when your KPI for Sales weekly `increases by 2%`. For more information, see xref:monitor.adoc#threshold-based-alert[Create a threshold-based alert].
+
This feature is in beta and off by default. To enable threshold-based alerts, contact {support-url}.

Make content discoverable::
You can now make content easily available to your team members when you save or share an answer. By default, the *Make content discoverable* checkbox that appears when you save or share an answer grants view access to any teammate with access to the answer’s underlying worksheet. Your answer appears in the list of relevant answers when a teammate uses the *Search Answer* feature.

[#8-5-0-cl-data-engineer]
=== For the Data Engineer

Okta OAuth for Snowflake connections::
You can now use Okta as your authorization server for external OAuth. For details, see xref:connections-snowflake-okta-oauth.adoc[Configure Okta OAuth for a Snowflake connection].


[#8-5-0-cl-it-ops-engineer]
=== For the IT Ops Engineer

[#8-5-0-cl-developer]
=== For the Developer

ThoughtSpot Everywhere:: For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].
