The latest release of ThoughtSpot Cloud contains several new and enhanced features.

* <<8-9-0-cl-first,For the First User>>
* <<8-9-0-cl-analyst,For the Analyst>>
* <<8-9-0-cl-business-user,For the Business User>>
* <<8-9-0-cl-data-engineer,For the Data Engineer>>
* <<8-9-0-cl-it-ops-engineer,For the IT Ops Engineer>>
* <<8-9-0-cl-developer,For the Developer>>

[#8-9-0-cl-first]
=== For the First User

Getting started with ThoughtSpot Cloud::
The first user on the account has to complete a series of steps before other people can start using ThoughtSpot with your organization's data.
For these instructions, see xref:ts-cloud-getting-started.adoc[Getting Started with ThoughtSpot Cloud].

[#8-9-0-cl-analyst]
=== For the Analyst

Custom sizes for visualizations in Liveboards GA [.badge.badge-early-access-relnotes]#Early Access#::
Custom tile sizes for visualizations within Liveboards are now generally available. In addition to the 5 predetermined visualization sizes, you can now customize your Liveboard visualizations to be any size. See xref:liveboard-layout-edit.adoc#size[Edit the layout of a Liveboard].

Visualization GUID support in TML files::
Liveboard ThoughtSpot Modeling Language (TML) files now contain distinct GUIDs for each visualization in the Liveboard by default. This ensures that the GUID for the visualization stays the same after you import or export it. See the xref:tml#viz_guid[TML viz_guid] parameter.

Pinboard to Liveboard change in TML::
ThoughtSpot changed the `pinboard` parameter in Liveboard TML files to `liveboard`, consistent with our rebrand of pinboards as Liveboards.
+
For more information, see xref:tml.adoc#syntax-liveboards[Syntax of the Liveboard TML file].

[#8-9-0-cl-business-user]
=== For the Business User

Discoverable answers and Liveboards:: The discoverable answers and Liveboards feature is now GA and on by default. You can now make content easily available to your team members. Use the *Make this [answer | Liveboard] discoverable* checkbox that appears when you save or share an answer or Liveboard to grant _view_ access to your teammates.
+
Select this checkbox to publish your content in the list of relevant results when a teammate uses the *Search Answers* feature, or de-select to keep your content private.

Edit your display name::
You can now edit your display name by clicking the profile icon in the top-right corner of the screen. see xref:user-profile.adoc[Edit display name,window=_blank].

[#8-9-0-cl-data-engineer]
=== For the Data Engineer

Tag enhancements::

This release includes the following updates to the xref:tags.adoc[tags] feature in the xref:data-workspace.adoc[]:
+
--
* Add tags to multiple objects at a time
* Administrators can create new tags from the *Edit tags* modal
--
+
For more information, see xref:tags#data-workspace-apply[Apply a tag] and xref:tags#data-workspace-create[Create a tag].

[#8-9-0-cl-it-ops-engineer]
=== For the IT/Ops Engineer

[#high-availability]
High Availability::
ThoughtSpot now supports High Availability through deployment spanning multiple Availability Zones. This ensures that the ThoughtSpot Cloud application experiences near-zero downtime in the case of AWS Availability Zone (AZ) failures. To learn how to enable High Availability in your environment, see xref:high-availability.adoc[].

[#8-9-0-cl-query-based-pricing]
Query Stats Liveboard::

The new Query Stats Liveboard allows administrators of customers who have signed up for a query-based usage subscription, to track the number of queries of their users. To view the Query Stats Liveboard, go to *Liveboards* and select *Query Stats Liveboard*. Query-based usage is part of consumption-based pricing. For more information, see xref:consumption-pricing-query-based.adoc[Query-based usage].


[#8-9-0-cl-developer]
=== For the Developer

ThoughtSpot Everywhere:: For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].
