The latest release of ThoughtSpot Cloud contains several new and enhanced features.

* <<8-3-0-cl-first,For the First User>>
* <<8-3-0-cl-analyst,For the Analyst>>
* <<8-3-0-cl-business-user,For the Business User>>
* <<8-3-0-cl-data-engineer,For the Data Engineer>>
* <<8-3-0-cl-it-ops-engineer,For the IT Ops Engineer>>
* <<8-3-0-cl-developer,For the Developer>>

[#8-3-0-cl-first]
=== For the First User

Getting started with ThoughtSpot Cloud::
The first user on the account has to complete a series of steps before other people can start using ThoughtSpot with your organization's data.
For these instructions, see xref:ts-cloud-getting-started.adoc[Getting Started with ThoughtSpot Cloud].

[#8-3-0-cl-analyst]
=== For the Analyst

Integration with dbt::
ThoughtSpot now offers an integration with dbt. You can provide your existing dbt models and automatically create worksheets in ThoughtSpot that you can use to perform searches on your data.
+
This feature is in beta and off by default. It is part of the <<data-tab,Data tab redesign>>, which is also in beta and off by default. To enable dbt integration and the Data tab redesign, contact {support-url}.

Jira Issue Management SpotApp::
This release introduces the Jira Issue Management SpotApp. ThoughtSpot maps your Jira data to SpotApp columns, and creates pre-built but still customizable worksheets, answers, and Liveboards, based on your data.
+
This feature is in beta and off by default. It is part of the <<data-tab,Data tab redesign>>, which is also in beta and off by default. To enable SpotApps and the Data tab redesign, contact {support-url}.

[#8-3-0-cl-business-user]
=== For the Business User

Previously viewed object suggestions::
When you xref:search-answers.adoc[search across existing answers and Liveboards], ThoughtSpot now offers object suggestions based on objects you previously viewed or interacted with, not just popular objects. This allows you to quickly return to an object you were working on or looking at in a previous session.

// make sure this is going to be GA

Open Search data in a new tab::
You can now open *Search data* in a new tab by right-clicking on the *Search data* option in the top navigation bar.

[#8-3-0-cl-data-engineer]
=== For the Data Engineer

OAuth for Databricks::
Databricks connections now support OAuth. See xref:connections-databricks-oauth.adoc[Configure OAuth for a Databricks connection].


[#8-3-0-cl-it-ops-engineer]
=== For the IT Ops Engineer

[#encryption-at-rest-ga]
Encryption at rest::
xref:security-thoughtspot-lifecycle.adoc#advanced-data-ear[Advanced data encryption at rest] is now GA. ThoughtSpot provides advanced data encryption at rest (EAR) that allows for granular user and folder level controls for encrypting your persistent data.
+
To enable EAR in your environment, contact {support-url}.

[#8-2-0-cl-developer]
=== For the Developer

ThoughtSpot Everywhere:: For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].
