The latest release of ThoughtSpot Cloud contains several new and enhanced features.

* <<8-3-0-cl-first,For the First User>>
* <<8-3-0-cl-analyst,For the Analyst>>
* <<8-3-0-cl-business-user,For the Business User>>
* <<8-3-0-cl-data-engineer,For the Data Engineer>>
* <<8-3-0-cl-it-ops-engineer,For the IT Ops Engineer>>
* <<8-3-0-cl-developer,For the Developer>>

[#8-3-0-cl-first]
=== For the First User

Getting started with ThoughtSpot Cloud::
The first user on the account has to complete a series of steps before other people can start using ThoughtSpot with your organization's data.
For these instructions, see xref:ts-cloud-getting-started.adoc[Getting Started with ThoughtSpot Cloud].

[#8-3-0-cl-analyst]
=== For the Analyst

New Liveboard experience::
The xref:liveboard-experience-new.adoc[new Liveboard experience] is now available. It contains multiple new features and feature enhancements.
It is part of ThoughtSpot's move to a new stack.
To learn how to enable it, refer to xref:liveboard-experience-new.adoc[].
+
The new Liveboard experience contains the following new features:

include::partial$new-liveboard-experience-features.adoc[]

include::partial$new-liveboard-experience-deprecations.adoc[]


[#8-3-0-cl-business-user]
=== For the Business User

Search suggestions::
When you xref:search-answers.adoc[search across existing answers and Liveboards], ThoughtSpot now offers object suggestions based on objects you previously viewed or interacted with, not just popular objects. This allows you to quickly return to an object you were working on or looking at in a previous session.

// make sure this is going to be GA

[#8-3-0-cl-data-engineer]
=== For the Data Engineer

[#8-3-0-cl-it-ops-engineer]
=== For the IT Ops Engineer

[#8-2-0-cl-developer]
=== For the Developer

ThoughtSpot Everywhere:: For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].
