= Español (España) Keyword reference
:last_updated: 11/19/2019
:linkattrs:
:experimental:
:page-aliases: /reference/keywords-es-ES.adoc
:description: Use keywords to help define a search.

{% include note.html content="This content is still under review, and might have incremental changes until this message is removed."%}

You can use keywords when asking a question to help define your search.
This reference lists the various keywords.

|===
| _xref:keywords.adoc[< Back to English Keywords page]_
|===

== General

{% include content/keywords-translate/es-ES/keywords-general-es-ES.md %}

== Date

{% include content/keywords-translate/es-ES/keywords-date-es-ES.md %}

== Time

{% include content/keywords-translate/es-ES/keywords-time-es-ES.md %}

== Text

{% include content/keywords-translate/es-ES/keywords-text-es-ES.md %}

== Number

{% include content/keywords-translate/es-ES/keywords-number-es-ES.md %}

== Comparative

{% include content/keywords-translate/es-ES/keywords-comparative-es-ES.md %}

////
## Location

{% include content/keywords-translate/es-ES/keywords-location-es-ES.md %}
////

== Period

{% include content/keywords-translate/es-ES/keywords-period-es-ES.md %}

////
## Help

{% include content/keywords-translate/es-ES/keywords-help-es-ES.md %}
////
