= Formula function reference
:last_updated: 11/19/2019
:permalink: /:collection/:path.html
:sidebar: mydoc_sidebar

Learn the operators and functions you can use to create formulas in ThoughtSpot.

ThoughtSpot allows you to create derived columns in worksheets using formulas.
You create these columns by building formulas using the *Formula Assistant*.
An individual formula is constructed from _n_ combination of operators and functions.

This reference lists the various operators and functions you can use to create formulas.

[#operators]
== Operators

include::includes:partial$operators.adoc[]

[#aggregate-functions]
== Aggregate functions (group aggregate)

Use the following functions to aggregate data.

include::includes:partial$aggregate.adoc[]

[#conversion-functions]
== Conversion functions

Use these functions to convert data from one data type into another data type.

ThoughtSpot does not support _date_ data type conversion.

include::includes:partial$conversion-func.adoc[]

[#date-functions]
== Date functions

include::includes:partial$date-func.adoc[]

[#mixed-functions]
== Mixed functions

These functions can be used with text and numeric data types.

include::includes:partial$mixed-func.adoc[]

[#number-functions]
== Number functions

include::includes:partial$number-func.adoc[]

[#text-functions]
== Text functions

include::includes:partial$text-func.adoc[]
