= ["Introduction to monitoring"]
:last_updated: 11/05/2021
:permalink: /:collection/:path.html
:sidebar: mydoc_sidebar
:summary: Learn how to monitor your system.

{% include content/liveboards-announcement.md %}

ThoughtSpot Cloud provides several out-of-the-box system monitoring worksheets, views, and Liveboards.
From these worksheets and views, you can create your own custom visualizations and Liveboards.
This page introduces these features and directs you towards more detailed information.

== Admin Console

From the Admin Console, you can view the link:{{ site.baseurl }}/admin/ts-cloud/user-adoption.html[User Adoption] system Liveboard, and view upcoming link:{{ site.baseurl }}/admin/ts-cloud/scheduled-maintenance.html[application maintenance].

Navigate to the Admin Console by selecting *Admin* from the top navigation bar.

== System worksheets, views, and Liveboards

Administrators can view existing system Liveboards, or create their own, custom boards that reflect system data in ways that are meaningful to specific departments or groups.
For more information, see the following documentation:

* link:{{ site.baseurl }}/admin/system-monitor/worksheets.html[System worksheets and views]
* link:{{ site.baseurl }}/admin/system-monitor/monitor-pinboards.html[System Liveboards]
